### ISSUE TITLE
match: nested / error: `is` can only be used with interfaces and sum types

### ISSUE THREAD

**Issue by aheissenberger** [vlang/v#10379] opened 2021-06-07 13:09 UTC
OS: macos, macOS, 11.4, 20F71
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
CC version: Apple clang version 12.0.5 (clang-1205.0.22.9)

getwd: /Users/ah/SVN-Checkouts/TST/vlang-test
vmodules: /Users/ah/.vmodules
vroot: /usr/local/Cellar/vlang/0.2.2/libexec
vexe: /usr/local/Cellar/vlang/0.2.2/libexec/v
vexe mtime: 2021-06-06 21:30:18
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 f4486d7.114c382

Git version: git version 2.32.0
Git vroot status: weekly.2021.22-52-g114c382c (8 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 689c8a02

**What did you do?**

access value of variable after type check

**What did you expect to see?**

no error
 
**What did you see instead?**

```
v run types-match_is_only.v
types-match_is_only.v:13:10: error: `is` can only be used with interfaces and sum types
   11 | fn isok(a DataStruct, b DataStruct) bool {
   12 |     if a.y is Text {
   13 |         if b.y is Text {
      |                ~~
   14 |             return a.y == b.y
   15 |         }
```

source `types-match_is_only.v`:
```v
struct Empty {}

type Text = string

type SumTypeB = Empty | Text

struct DataStruct {
	y SumTypeB
}

fn isok(a DataStruct, b DataStruct) bool {
	if a.y is Text {
		if b.y is Text {
			return a.y == b.y
		}
	}
	return false
}

a := DataStruct{
	y: Text('da')
}
b := DataStruct{
	y: Text('da')
}
assert isok(a, b)
```

**Comment by dumblob** [comment] 2021-06-09 08:44
Related to (or even duplicate of something from) https://github.com/vlang/v/issues/9305 .

**Closed** 2021-06-18 11:49 UTC
Labels: Bug
