### ISSUE TITLE
Json: Too many arguments in call to json.decode (2 instead of 0)

### ISSUE THREAD

**Issue by fatihkizmaz** [vlang/v#4459] opened 2020-04-17 10:05 UTC
**V version:** V 0.1.26 402e55d
**OS:** Win10 x64

**What did you do?**
Basic json example in examples folder does not work. Also could not compile vpm, because of json related errors.

**What did you see instead?**
![image](https://user-images.githubusercontent.com/17065192/79557736-b9038500-80ab-11ea-9cbc-1abc6f5da00c.png)

**Comment by JalonSolov** [comment] 2020-04-17 13:38
#4273

**Comment by lutherwenxu** [comment] 2020-04-23 00:48
Duplicate of #4273.

**Closed by lutherwenxu** 2020-04-23 00:48 UTC
Labels: Bug
