### ISSUE TITLE
Optional Regression

### ISSUE THREAD

**Issue by radare** [vlang/v#4386] opened 2020-04-13 10:14 UTC
**V version:** V 0.1.26 83289d7.d691f46
**OS:** macOS 10.15

**What did you do?**

```
pmb:ns-tester pancake$ cat opt.v
fn main() {
	mut c := 0
	c = 'foo'.index('o') or {
		42
	}
	println(c)
}
pmb:ns-tester pancake$ v run opt.v
==================
^
/private/var/folders/fp/qqm5m5nj0ll0xtljv1306h5r0000gn/T/v/opt.tmp.c:4627:21: error: assigning to 'int' from incompatible type 'Option_int' (aka 'struct Option')
        Option_int tmp1 =c = string_index(tos3("foo"), tos3("o"));
                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/fp/qqm5m5nj0ll0xtljv1306h5r0000gn/T/v/opt.tmp.c:5001:4: warning: initializer overrides prior initialization of this subobject [-Winitializer-overrides]
                .u = 0,
                ~^
/private/var/folders/fp/qqm5m5nj0ll0xtljv1306h5r0000gn/T/v/opt.tmp.c:5000:2: note: previous initialization is here
        0,
        ^
/private/var/folders/fp/qqm5m5nj0ll0xtljv1306h5r0000gn/T/v/opt.tmp.c:5240:4: warning: initializer overrides prior initialization of this subobject [-Winitializer-overrides]
                .u = 0,
...
==================
(Use `v -cg` to print the entire error message)

builder error: C error.

Please make sure that:
- You have all V dependencies installed.
- You did not declare a C function that was not included. (Try commenting your code that involves C interop)
- You are running the latest version of V. (Try running `v up` and rerunning your command)

If you're confident that all of the above is true, please try running V with the `-cg` option which enables more debugging capabilities.

```

**What did you expect to see?**

the thing to compile
 
**What did you see instead?**

the thing failing because c is of type int, but then the optional assignment tries to set ?int because the or is not unwrapping the type in case of success. also its not clear what value will be set in case of fail

**Comment by alexesprit** [comment] 2020-04-14 17:35
Duplicate of #3389.

**Closed** 2020-04-16 15:45 UTC
Labels: Bug
