### ISSUE TITLE
Type reserved words (eg, int) are allowed to be names of variables

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#2669] opened 2019-11-06 16:11 UTC
**V version:** 
V playground

**OS:** 
N/A

**What did you do?**
```V
fn main() {
    int := 10
    println(int)
} 
```

**What did you expect to see?**
An error. It shouldn't be allowed to use reserved words as names of vars.
 
**What did you see instead?**
Successful compilation. Printed 10.

**This issue also applies to other type reserved words such as f64, f32, bool, etc.**

**Comment by LorenzoPirro** [comment] 2019-11-07 15:33
@SleepyRoy i've tested all the cases (with the last PR that has to be seen) :
```
int ok := 6
byteptr := \'string\'
if rune := http.get('https://vlang.io') { println(rune.text) }
for string := 0; string < 5; string++ { println(string) }
```
All works!

**Comment by M4SSD35TRUCT10N** [comment] 2019-11-07 18:17
Looks promising. @LorenzoPirro Are you still working on that? Or do you wait for review and merge?

Your friendly issue janitor.

**Comment by M4SSD35TRUCT10N** [comment] 2019-11-07 18:25
@LorenzoPirro Should I close this issue after @SleepyRoy confirmed the fix, since you PR was merged?
@SleepyRoy Please confirm solution/fix so that we can close this issue.

**Comment by SleepyRoy** [comment] 2019-11-07 18:49
@M4SSD35TRUCT10N Thanks.
@LorenzoPirro Thanks for your work. I just tested all through V playground and some are still problematic.
int := 10, byteptr := 'string' - **Correctly blocked. Nice work!**
int ok := 6 - **A wrong decalration? Var names shouldn't contain spaces.**
if rune := http.get('https://vlang.io') { println(rune.text) } - **Playground doesn't support imports for now so I didn't test it.**
for string := 0; string < 5; string++ { println(string) } - **Still able to compile and printed 0 to 4.**

**Comment by M4SSD35TRUCT10N** [comment] 2019-11-07 19:15
@SleepyRoy REPL seems to need some more love. Could you test it with regular v file and run or compilation instead of REPL? This would narrow it  further down.

Thank you in advance for your efforts!

**Comment by LorenzoPirro** [comment] 2019-11-08 12:01
@SleepyRoy 
<img width="662" alt="Schermata 2019-11-08 alle 12 55 09" src="https://user-images.githubusercontent.com/17650857/68475149-9a10e500-0227-11ea-855d-7b1ba612093a.png">
Use `v up` and than try, it's the result from my repl (Manjaro and MacOs Catalina). if optional causes a little problem on repl but it works well with standard compilation.
Confirm :) please

**Closed** 2019-11-08 13:05 UTC
Labels: bug
