### ISSUE TITLE
checker: use `any` for type casting

### ISSUE THREAD

**Issue by Hunam6** [vlang/v#15003] opened 2022-07-09 21:26 UTC
```
OS: macos, macOS, 12.4, 21F79
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

getwd: /Users/hunam/Documents/dev/testing-v
vmodules: /Users/hunam/.vmodules
vroot: /Applications/v
vexe: /Applications/v/v
vexe mtime: 2022-07-09 15:02:55
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 946da55.1ae11b4

Git version: git version 2.32.1 (Apple Git-133)
Git vroot status: 0.3-82-g1ae11b41
.git/config present: true
thirdparty/tcc status: thirdparty-macos-arm64 173c526e

```

**What did you do?**
```v
a := any(123)
```

**What did you expect to see?**
I don't quite know at which point any is a valid type in V.
 
**What did you see instead?**
```c
/tmp/v_501/c.18404743079384999127.tmp.c:2116:4: warning: expression result unused [-Wunused-value]
  (*(int*)_t1.data);
   ^~~~~~~~~~~~~~~
/tmp/v_501/c.18404743079384999127.tmp.c:12017:2: error: use of undeclared identifier 'any'
        any a = ((any)(123));
        ^
1 warning and 1 error generated.
```

**Comment by medvednikov** [comment] 2022-07-11 08:35
Duplicate of https://github.com/vlang/v/issues/12623

**Closed by medvednikov** 2022-07-11 08:35 UTC
Labels: Bug
