### ISSUE TITLE
v watch doesnt print out

### ISSUE THREAD

**Issue by Corallus-Caninus** [vlang/v#14710] opened 2022-06-06 23:44 UTC
V version:
OS:
OS: windows, Microsoft Windows 10 Home v19044 64-bit
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 3600 6-Core Processor
CC version: (built by Brecht Sanders) clang version 14.0.3

getwd: C:\Users\wardj\OneDrive\Desktop\V_Code\tensorflow-v
vmodules: C:\Users\wardj.vmodules
vroot: C:\Users\wardj\OneDrive\Desktop\V_Code\v
vexe: C:\Users\wardj\OneDrive\Desktop\V_Code\v\v.exe
vexe mtime: 2022-06-06 05:12:56
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 https://github.com/vlang/v/commit/ce771876a38a94064e834f5b2a2499504ec63257

Git version: git version 2.33.1.windows.1
Git vroot status: weekly.2022.22-54-gce771876-dirty
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 125e21e2

What did you do?
created a .v file with main that prints with println
then ran v watch myfile.v
also tried v watch .

It builds with warnings but never prints to stdout

What did you expect to see?
my printed out string

What did you see instead?
reload cycles with no stdout prints

v run prints correctly

**Comment by Corallus-Caninus** [comment] 2022-06-07 07:28
can anyone reproduce this?

**Comment by ChAoSUnItY** [comment] 2022-06-07 11:49
You probaly want to try out `v watch run myfile.v`, `v watch myfile.v` only compiles myfile.v into executable when myfile.v has been edited. Meanwhile, `v watch run myfile.v` compiles and runs myfile.v when myfile.v has been edited

**Comment by Calinou** [comment] 2022-06-19 05:26
Duplicate of https://github.com/vlang/v/issues/14693 (it was reopened).

**Closed** 2022-06-19 12:37 UTC
Labels: Bug
