### ISSUE TITLE
JSON decoding/encoding

### ISSUE THREAD

**Issue by nasali** [vlang/v#3341] opened 2020-01-06 03:06 UTC
**V version:** 
Playground
**OS:** 
Mac
**What did you do?**
In the Playground, clicked `JSON decoding/encoding` then clicked `Run` without any modifications.

**What did you expect to see?**
The list of users.
 
**What did you see instead?**
Warning: 'v' is a directory
addr2line: Warning: 'v' is a directory

<img width="1672" alt="Screen Shot 2020-01-05 at 8 02 42 PM" src="https://user-images.githubusercontent.com/1334585/71792654-cc0bb100-2ff6-11ea-8e7e-a0398799c5d7.png">

Thank you.

**Comment by cliserkad** [comment] 2020-01-06 03:15
This is a duplicate of #3327
None of the examples at https://vlang.io/play are working for me. Windows 10, Firefox 71.0 (64 bit)

**Comment by nedpals** [comment] 2020-01-06 03:42
Duplicate of #3327

**Closed** 2020-01-06 03:41 UTC
Labels: bug
