### ISSUE TITLE
Can't download package

### ISSUE THREAD

**Issue by bogdanbankov** [vlang/v#4664] opened 2020-05-01 08:26 UTC
**V version:** V 0.1.26 50a8373.1fabb7d
**OS:** Windows 10 Pro 1909
**What did you do?** v install ui
**What did you expect to see?** 
it downloads
**What did you see instead?**
C:\v\cmd\tools\vpm.v:466:15: error: too many arguments in call to `json.decode` (2 instead of 0)
  464|             continue
  465|         }
  466|         mod := json.decode(Mod,s) or {
                           ~~~~~~~~~~~~~
  467|             errors << 'Skipping module "$name", since its information is not in json format.'
  468|             continue
C:\v\cmd\tools\vpm.v:470:16: error: `voidptr` is not a struct
  468|             continue
  469|         }
  470|         if '' == mod.url || '' == mod.name {
                            ~~~
  471|             errors << 'Skipping module "$name", since it is missing name or url information.'
  472|             continue‘

**Comment by spytheman** [comment] 2020-05-01 09:12
Duplicate of https://github.com/vlang/v/issues/4256

**Closed** 2020-05-01 09:31 UTC
Labels: Bug

**Comment by bogdanbankov** [comment] 2020-05-01 10:01
This is not a duplicate, because in issue #4256 is another error. I am having a problem with installing ALL packages, not only ui

**Comment by nedpals** [comment] 2020-05-01 10:03
@bogdanbankov Still, it is related to the JSON module used by the VPM.

**Comment by bogdanbankov** [comment] 2020-05-01 10:05
@nedpals and what I need to do?

**Comment by nedpals** [comment] 2020-05-01 10:07
@bogdanbankov Wait for the fix. Four minutes ago, the first part for the JSON fix has been pushed to upstream.

**Comment by bogdanbankov** [comment] 2020-05-01 10:07
@nedpals ok. Thanks!

**Comment by medvednikov** [comment] 2020-05-01 10:07
will be fixed today, I've pushed the first json.decode fix
