### ISSUE TITLE
Too many expr levels

### ISSUE THREAD

**Issue by trufae** [vlang/v#5535] opened 2020-06-27 18:35 UTC
**V version:** 
**OS:** 

**What did you do?**

when iu found this bug it was segfaulting the compiler now it seems to set a recursivity limit, but iu dont think it should be recursing..

```go
module main

struct Stru {
mut:
	a int
	i Iface2
}

interface Iface {
	result() &Iface2
}

interface Iface2 {
	result2() Iface
}

pub fn (s Stru)result() &Iface2 {
	return &Stru{}
}

pub fn (s Stru)result2() Iface {
	return &Stru{}
}

fn main() {
	println('hello world')
	poo := Stru{
		a: 123
		i: poo.result()
	}
 	println('$poo')
}
```

**What did you expect to see?**

working program
 
**What did you see instead?**

```
$ v run q.v
q.v:27:9: error: checker: too many expr levels: 201
   25 | fn main() {
   26 |     println('hello world')
   27 |     poo := Stru{
      |            ~~~~~
   28 |         a: 123
   29 |         i: poo.result()
```

**Comment by Dialga** [comment] 2020-12-26 16:34
#6217 is a duplicate of this.
Simplified testcase:

` v := 'hi'.index('i') or { v[0] }`

**Comment by JalonSolov** [comment] 2021-05-14 19:00
Still failing with latest version `V 0.2.2 20a2245`
```
baz.v:1:2: warning: unused variable: `v`
    1 | v := 'hi'.index('i') or { v[0] }
      |  ^
    2 |
baz.v:1:27: error: checker: too many expr levels: 201
    1 | v := 'hi'.index('i') or { v[0] }
      |                           ^
    2 |
```

**Comment by Dialga** [comment] 2021-08-02 09:03
More testcases:
```
>>> v := v.v
error: checker: too many expr levels: 151
    5 | import math
    6 |
    7 | v := v.v
      |        ^
>>> v := v[0]
error: checker: too many expr levels: 151
    5 | import math
    6 |
    7 | v := v[0]
      |       ~~~
```

**Comment by yuyi98** [comment] 2022-02-16 14:14
```vlang
	poo := Stru{
		a: 123
		i: poo.result()
	}
```
I think it should be error `poo is undefined` and cannot work.

**Closed** 2022-02-17 07:21 UTC
Labels: Bug
