### ISSUE TITLE
Builder Error:  cannot convert 'struct main__Stack *' to 'struct main__Stack'

### ISSUE THREAD

**Issue by AjayTheWizard** [vlang/v#15199] opened 2022-07-24 10:58 UTC
**V version:**  0.3.0 12d57e8 
**OS:** Windows 10 10240

When I was building a Compiler for my un named JS Framework,
```
C:/Users/Admin/AppData/Local/Temp/v_0/main.5701473161230140117.tmp.c:17423: warning: assignment from incompatible pointer type
C:/Users/Admin/AppData/Local/Temp/v_0/main.5701473161230140117.tmp.c:17525: error: cannot convert 'struct main__Stack *' to 'struct main__Stack'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```
I am new vlang ( I learn it yesterday, Today building compiler 2 days only! ) and I have no experience with C or C++
I think It's problem in my `Stack` struct, I can't show my full coding because, It's hard to read ( It's code of a compiler ) So I just showing some struct code,
```
struct Stack {
	mut: value []string
}

fn (s Stack) len() int {
	return s.value.len
}

fn (s Stack) is_empty() bool {
	return s.len() == 0
}

fn (s Stack) last() string {
	return s.value[s.len() - 1]
}

fn (mut s Stack) pop() {
	s = s[..s.len() - 1]
}

fn (mut s Stack) push(str string) {
	s.value << str
}

struct Attributes {
	key string
	value string
	is_static bool = true
}

struct Node {
	mut: name string
	attributes []Attributes
	children ?[]Node // <- Is any error here?
}
```

**Comment by medvednikov** [comment] 2022-07-25 11:51
Structs cannot have optional fields for now.

We'll fix it soon.

Duplicate of https://github.com/vlang/v/issues/6717

**Closed by medvednikov** 2022-07-25 11:51 UTC
Labels: Bug, Unit: Compiler, Status: Confirmed
