### ISSUE TITLE
vweb json method error

### ISSUE THREAD

**Issue by floscodes** [vlang/v#15566] opened 2022-08-27 15:34 UTC
**V doctor:**
```
OS: macos, macOS, 12.1, 21C52
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
CC version: Apple clang version 12.0.0 (clang-1200.0.31.1)

getwd: /Users/florian/Desktop/Code/v/server
vmodules: /Users/florian/.vmodules
vroot: /Users/florian/Desktop/Code/v/v
vexe: /Users/florian/Desktop/Code/v/v/v
vexe mtime: 2022-08-27 13:37:43
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 d75c62b

Git version: git version 2.24.3 (Apple Git-128)
Git vroot status: weekly.2022.34-38-gd75c62b8
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 46662e20

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg server.v`
```v
module main

import vweb

struct App {
    vweb.Context
}

struct Json {
	message string
}

fn main() {
	mut app:=App{}
    vweb.run(app, 8080)
}

fn (mut app App) index() vweb.Result {
	return app.text('First successful test in V!')
}

fn (mut app App) json() vweb.Result {
	json_res := Json{"First successful json-test with v!"}
	return app.json(json_res)
}


```

**What did you expect to see?**

according to the documentation https://modules.vlang.io/vweb.html#Context.json the json-method should take one argument. But the compiler throws an error saying that 0 arguments were expected.

**What did you see instead?**
```
server.v:24:18: error: expected 0 arguments, but got 1
   22 | fn (mut app App) json() vweb.Result {
   23 |     json_res := Json{"First successful json-test with v!"}
   24 |     return app.json(json_res)
      |                     ~~~~~~~~
   25 | }
   26 |
```

**Comment by WoodyAtHome** [comment] 2022-08-27 22:04
It's not a bug. You're not allowed to name your function 'json()'. Then the compiler want to call your function. Your function doesn't expect a argument.
Just rename your function, e.g:

```
module main

import vweb

struct App {
    vweb.Context
}

struct Json {
	message string
}

fn main() {
	mut app:=App{}
    vweb.run(app, 8080)
}

fn (mut app App) index() vweb.Result {
	return app.text('First successful test in V!')
}

fn (mut app App) get_json() vweb.Result {
	json_res := Json{"First successful json-test with v!"}
	return app.json(json_res)
}
```

**Comment by alwint3r** [comment] 2022-08-28 03:56
> It's not a bug. You're not allowed to name your function 'json()'. Then the compiler want to call your function. Your function doesn't expect an argument. Just rename your function, e.g:
> 
> ```
> module main
> 
> import vweb
> 
> struct App {
>     vweb.Context
> }
> 
> struct Json {
> 	message string
> }
> 
> fn main() {
> 	mut app:=App{}
>     vweb.run(app, 8080)
> }
> 
> fn (mut app App) index() vweb.Result {
> 	return app.text('First successful test in V!')
> }
> 
> fn (mut app App) get_json() vweb.Result {
> 	json_res := Json{"First successful json-test with v!"}
> 	return app.json(json_res)
> }
> ```
> 
> Btw: You might `import json` and then send a valid json string with
> 
> ```
> fn (mut app App) get_json() vweb.Result {
> 	json_res := Json{"First successful json-test with v!"}
> 	return app.json(json.encode(json_res))
> }
> ```

`app.json(json.encode(json_res))` is redundant though, `app.json(json_res)` should be enough.

**Comment by WoodyAtHome** [comment] 2022-08-28 06:26
You'are right and it was wrong what I wrote after 'BTW'.

app.json(json_res) should is enough, it was very late a I didn't check `examples/vweb/vweb_example.v`

**Comment by floscodes** [comment] 2022-08-28 10:35
> 

Oh yes, I am so sorry! Of course I sould never name my function like this... Thanks!

**Comment by floscodes** [comment] 2022-08-28 10:35
Yes, now I think this can be closed.

**Comment by WoodyAtHome** [comment] 2022-08-28 11:34
@floscodes  You have to close it. I have not the permissions to close foreign issues.

**Closed** 2022-08-28 17:10 UTC
