### ISSUE TITLE
V panic: not used variable

### ISSUE THREAD

**Issue by SewerynKaminski** [vlang/v#1711] opened 2019-08-22 17:16 UTC
**V version**: 0.1.18
**OS**:Ubuntu 18.04 64bit

**What did you do?**
compile a simple test case
```
mut a:=0
//a=0 // uncomment to succesfull compilation
```

**What did you expect to see?**
succesfull compilation or not used variable error

 
**What did you see instead?**
V panic: string index out of range: 10 / 10

**Comment by mvlootman** [comment] 2019-08-22 17:18
duplicate of #1707

**Comment by mvlootman** [comment] 2019-08-23 17:08
This issue can be closed, its fixed with the latest version.

**Comment by medvednikov** [comment] 2019-08-23 17:15
@mvlootman just added you to the dev team, you can now close issues ;)

**Closed by medvednikov** 2019-08-23 17:15 UTC
Labels: bug
