### ISSUE TITLE
could not generate string method anon_98_18_18_str

### ISSUE THREAD

**Issue by radare** [vlang/v#4911] opened 2020-05-16 00:43 UTC
**V version:** V 0.1.27 465f0dd
**OS:** macOS 10.15

**What did you do?**

```go
$ v  fmt a.v
fn main() {
	x := ['pop', 'foo', 'var']
	bar := fn (b string) string {
		return b[1..]
	}
	println(x.map(bar))
}
$ v run a.v
cgen error: could not generate string method anon_98_18_18_str for type 'anon_98_18_18'
$
```
**What did you expect to see?**
```
$ v run a.v
cgen error: could not generate string method anon_98_18_18_str for type 'anon_98_18_18'
$
```
 
**What did you see instead?**

**Comment by yuyi98** [comment] 2020-05-17 08:21
```v
fn main() {
	x := ['pop', 'foo', 'var']
	a := x.map(it[1..])
	println(a)
}
```
It can work. Above is the problem with the anonymous function.

**Comment by dkull** [comment] 2020-05-18 17:05
No, the issue is about the way you use map. 
Map currently does not take a callable and apply the `it`, instead map expects a full expression.
This works:
```v
fn main() {
        x := ['pop', 'foo', 'var']
        bar := fn (b string) string {
                return b[1..]
        }
        println(x.map(bar(it)))
}
```

@medvednikov should map be able take a function as a single argument?

**Comment by radare** [comment] 2020-05-19 10:25
filter does, so map should imho

**Comment by spytheman** [comment] 2020-05-20 16:07
Filter is buggy when you pass it just the name of a function, it just uses its value to compare it that it is not 0, so it returns the original list.

**Comment by dkull** [comment] 2020-05-20 16:27
I'm confused. You merged my fix for this issue a few hours ago https://github.com/vlang/v/pull/4959
Or are you just discussing the issue? :)
But map and filter need many extra checks for the parameters. Currently you can pass in functions that take multiple arguments etc.

**Comment by spytheman** [comment] 2020-05-20 17:47
@dkull , I was just commenting on the underlying problem, and thinking by writing. 
Sorry for the ramblings :-) .

**Closed** 2020-06-09 08:14 UTC
Labels: Bug
