### ISSUE TITLE
println - unhandled sprintf format trying to print nested struct

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vlang/v#4094] opened 2020-03-21 15:44 UTC
**V version:** 0.1.25 79077b0
**OS:** Ubuntu x86_64

**What did you do?**
I was playing with the path tracer example and came with this minimal code:
```v
struct Vec {                                                                     
    mut: x f64 = f64(0.0)                                                        
}                                                                                
                                                                                 
struct Ray {                                                                     
    o Vec                                                                        
}                                                                                
                                                                                 
fn main() {                                                                      
    cam := Ray{Vec{50}}                                                          
                                                                                 
    println(Ray{cam.o})                                                          
}
```

**What did you expect to see?**
I expected to see the structs printed.
 
**What did you see instead?**
```
...
/home/USERNAME/.cache/v/path_tracing.tmp.c:6769: undefined reference to `Vec_str'
collect2: error: ld returned 1 exit status
V error: 
==================
C error. This should never happen.
```

On the web playground (https://vlang.io/play) it outputs `unhandled sprintf format "Vec"`.

**Comment by Naheel-Azawy** [comment] 2020-03-22 16:23
Same as #4074

**Comment by nedpals** [comment] 2020-03-25 10:42
Closed. Duplicate of #4074

**Closed by nedpals** 2020-03-25 10:42 UTC
Labels: Type: Bug
