### ISSUE TITLE
A string with " \" " doesn't compile or show an error

### ISSUE THREAD

**Issue by Stopfield** [vlang/v#3797] opened 2020-02-21 00:56 UTC
**V version:** 
**OS:** 
The V playground -> https://vlang.io/play

**What did you do?**
Tried to run the following code:
```
fn main(){
	test := "aasldjsa\"test\""
	println(test)
}
```

**What did you expect to see?**
Expected to see the string with the `" "`.
 
**What did you see instead?**
It didn't compile. If the using of `\"` is wrong, the compiler must warn the user. I don't know if `\"` is considered a special character by it though.

I've tried with different strings and I've found out that the compiler crashes when the user puts `\` outside and inside a nested `""`
`"string 1\"string2\""` -> Apparently this cannot be compiled. If you change the position, it shows the error.

**Comment by alexesprit** [comment] 2020-02-27 09:44
Duplicate of #2216.

**Closed by alexesprit** 2020-02-27 09:44 UTC
Labels: Type: Bug
