### ISSUE TITLE
news_fetcher.v never quits

### ISSUE THREAD

**Issue by logTom** [vlang/v#2961] opened 2019-12-03 09:06 UTC
**0.1.23:** 
**Linux Solus** 

**v run news_fetcher.v**

**10 news items being displayed and then the program quits.**

 
**10 news items being displayed and the programm running endless with 100 % cpu utilization on 1 core.**

**Comment by spytheman** [comment] 2019-12-03 10:48
Possible duplicate of #2874 .

**Comment by medvednikov** [comment] 2019-12-03 12:52
Should work fine now @logTom

**Comment by logTom** [comment] 2019-12-03 13:13
Thanks, can confirm that it works now.

**Comment by medvednikov** [comment] 2019-12-03 13:42
Thanks @spytheman 

Looks like it was optimized without even -O2

**Closed by medvednikov** 2019-12-03 13:42 UTC
Labels: bug
