### ISSUE TITLE
programming microcontroller and SBC

### ISSUE THREAD

**Issue by ghost** [vlang/v#1886] opened 2019-09-07 08:56 UTC
compiler and standard library support for programming microcontrollera and single board computes.

**Comment by dumblob** [comment] 2019-09-07 09:07
Duplicate of https://github.com/vlang/v/issues/590 ?

**Comment by lithic** [comment] 2019-09-08 17:22
@dumblob , i don't think so

**Comment by lithic** [comment] 2019-09-08 17:24
This is a matter of running program in a resource constraint environment

**Comment by lithic** [comment] 2019-09-08 17:29
@medvednikov ?

**Comment by lithic** [comment] 2019-09-15 14:33
@medvednikov ?

**Comment by nedpals** [comment] 2020-03-30 03:39
Closed. Will be redirecting the issue to #4115 as it has more information than this one.

**Closed by nedpals** 2020-03-30 03:39 UTC
Labels: Feature Request
