### ISSUE TITLE
Variable example didn't work on playground

### ISSUE THREAD

**Issue by kokizzu** [vlang/v#3463] opened 2020-01-16 14:30 UTC
**V version:** not sure
**OS:** not sure

**What did you do?**
run example on Variable section
```
name := 'Bob'
age := 20
large_number := i64(9999999999)
println(name)
println(age)
println(large_number)
```

**What did you expect to see?**
compiled correctly
 
**What did you see instead?**
```
cannot use type `void` as type `string` in first argument to `println()`
    2| age := 20
```

**Comment by kokizzu** [comment] 2020-01-16 14:32
next example also error:
```
mut age := 20
println(age)
age = 21
println(age)
```

the error:
```
cannot use type `void` as type `string` in first argument to `println()`
    1| mut age := 20
```

**Comment by kokizzu** [comment] 2020-01-16 14:35
The Strings section also error:
```
name := 'Bob'
println('Hello, $name!')  // `$` is used for string interpolation
println(name.len)

bobby := name + 'by' // + is used to concatenate strings
println(bobby) // "Bobby" 

println(bobby[1..3]) // "ob" 
mut s := 'hello '
s += 'world' // `+=` is used to append to a string
println(s) // "hello world" 
```

the error:
```
cannot interpolate this value
    1| name := 'Bob'
```

**Comment by kokizzu** [comment] 2020-01-16 14:38
The Array section also error:
```
mut nums := [1, 2, 3]
println(nums) // "[1, 2, 3]"
println(nums[1]) // "2"

nums << 4
println(nums) // "[1, 2, 3, 4]"

nums << [5, 6, 7]
println(nums) // "[1, 2, 3, 4, 5, 6, 7]"

mut names := ['John']
names << 'Peter'
names << 'Sam'
// names << 10  <-- This will not compile. `names` is an array of strings.
println(names.len) // "3"
println('Alex' in names) // "false"

names = [] // The array is now empty

// We can also preallocate a certain amount of elements.
ids := [0].repeat(50) // This creates an array with 50 zeros
```

the error:
```
cannot use type `void` as type `string` in first argument to `println()`
    1| mut nums := [1, 2, 3]
```

**Comment by kokizzu** [comment] 2020-01-16 14:40
The Maps section also error:
```
mut m := map[string]int // Only maps with string keys are allowed for now 
m['one'] = 1
m['two'] = 2
println(m['one']) // "1" 
println(m['bad_key']) // "0" 
println('bad_key' in m) // Use `in` to detect whether such key exists
m.delete('two')

numbers := {
	'one': 1,
	'two': 2,
}
```
the error:
```
syntax error: unexpected `'one'`, expecting `name`
    1| mut m := map[string]int // Only maps with string keys are allowed for now 
```

**Comment by kokizzu** [comment] 2020-01-16 14:41
The If section also error:
```
a := 10
b := 20
if a < b {
	println('$a < $b')
} else if a > b {
	println('$a > $b')
} else {
	println('$a == $b')
}
```
the error:
```
cannot interpolate this value
    2| b := 20
```

but it's ok when wrapped with `fn main()`

**Comment by muraray** [comment] 2020-01-24 04:25
> **V version:** not sure
> **OS:** not sure
> 
> **What did you do?**
> run example on Variable section
> 
> ```
> name := 'Bob'
> age := 20
> large_number := i64(9999999999)
> println(name)
> println(age)
> println(large_number)
> ```
> 
> **What did you expect to see?**
> compiled correctly
> 
> **What did you see instead?**
> 
> ```
> cannot use type `void` as type `string` in first argument to `println()`
>     2| age := 20
> ```

Appreciate if you could enclose the code within the main block 

```
module main

fn main() {
	name := 'Bob'
	age := 20
	large_number := i64(9999999999999999)

	println(name)
	println(age.str())
	println(large_number.str())	
}

```

this should work, i tested other examples as well seems works fine for me.

**Comment by warpdesign** [comment] 2020-01-26 08:33
The tutorial suggests, at the very beginning:

> fn main() declaration can be skipped in one file programs. This is useful when writing small programs, "scripts", or just learning the language. For brevity, fn main() will be skipped in this tutorial.

I guess it should be updated then since following this suggestion appears to break lots of examples.

**Comment by warpdesign** [comment] 2020-01-26 08:59
This code (extracted from the documentation) also appears to produce an error:

```
fn main() {
  numbers := {
	'one': 1,
	'two': 2,
  }
}
```

> next token = `}`
test.v:14:1: syntax error: unexpected `}`, expecting `STR`
   12|  'two': 2,
   13| }
   14| }

**Comment by fsmiamoto** [comment] 2020-03-08 19:58
This issue probably has to do with this from the [docs](https://vlang.io/docs#vars):
> Unlike most other languages, V only allows defining variables in functions. Global (module level) variables are not allowed. There's no global state in V.

Nonetheless, I also think the examples should be updated to reflect that

**Comment by spytheman** [comment] 2020-03-09 06:48
@warpdesign , this is a regression bug in v:
```v
fn main() {
  numbers := {
	'one': 1,
	'two': 2,
  }
}
```
It will be fixed soon (it errors because of the trailing `,` after 2).

**Comment by spytheman** [comment] 2020-03-09 06:52
Just a reminder: github issues work *best*, when they are focused on a *single* problem.
If you find *another* problem, even if it is in the same general area, it is better to have a *new issue* opened, so that we can track it more easily, and close it when a solution is found.

**Comment by hachi8833** [comment] 2020-03-10 00:31
Most of samples now works fine on "V 0.1.25 876b73f"

```v
name := 'Bob'
age := 20
large_number := i64(9999999999)
println(name)
println(age)
println(large_number)
```

```v
mut age := 20
println(age)
age = 21
println(age)
```

```v
name := 'Bob'
println('Hello, $name!')  // `$` is used for string interpolation
println(name.len)

bobby := name + 'by' // + is used to concatenate strings
println(bobby) // "Bobby" 

println(bobby[1..3]) // "ob" 
mut s := 'hello '
s += 'world' // `+=` is used to append to a string
println(s) // "hello world" 
```

```v
mut nums := [1, 2, 3]
println(nums) // "[1, 2, 3]"
println(nums[1]) // "2"

nums << 4
println(nums) // "[1, 2, 3, 4]"

nums << [5, 6, 7]
println(nums) // "[1, 2, 3, 4, 5, 6, 7]"

mut names := ['John']
names << 'Peter'
names << 'Sam'
// names << 10  <-- This will not compile. `names` is an array of strings.
println(names.len) // "3"
println('Alex' in names) // "false"

names = [] // The array is now empty

// We can also preallocate a certain amount of elements.
ids := [0].repeat(50) // This creates an array with 50 zeros
```

```v
a := 10
b := 20
if a < b {
	println('$a < $b')
} else if a > b {
	println('$a > $b')
} else {
	println('$a == $b')
}
```

------------

The following Map example still causes an error:

```v
mut m := map[string]int // Only maps with string keys are allowed for now 
m['one'] = 1
m['two'] = 2
println(m['one']) // "1" 
println(m['bad_key']) // "0" 
println('bad_key' in m) // Use `in` to detect whether such key exists
m.delete('two')

numbers := {
	'one': 1,
	'two': 2,
}
```

> next token = `]`
test.v:2:8: syntax error: unexpected `'one'`, expecting `name`
    1| mut m := map[string]int // Only maps with string keys are allowed for now
    2| m['one'] = 1
              ^

**Comment by Ivo-Balbaert** [comment] 2020-05-23 13:53
All of the cited examples work fine in the current playground.

**Closed by Ivo-Balbaert** 2020-05-23 13:53 UTC
Labels: Bug, OS: Playground, Unit: Documentation
