### ISSUE TITLE
Question: Bug or normal behavior?

### ISSUE THREAD

**Issue by stefanos82** [vlang/v#535] opened 2019-06-24 20:44 UTC
**V version:** 

0.1.0 (git: `02edf86c4a3ea2c55998a230b6d82d4ccfdfff4e`)

**OS:**

Debian testing 64-bit fully updated on daily basis.

**C compiler version:** 

GCC 8.3.0-6

**What did you do?**
```bash
stefanos@debian:~/code/v/compiler [master]$ ./v
V 0.1.0
Use Ctrl-D to exit
For now you have to use println() to print values, this will be fixed soon

>>> print('testing'")
(char code=34) pos=19 len=40
panic: vrepl.v:1
invalid character `"`
```
Is this the expected behavior or is a bug?

**Comment by Undumendil** [comment] 2019-06-24 20:50
`'testing'"` is not a valid string; `'testing"'` is. As expected.

**Comment by Bowero** [comment] 2019-06-24 20:51
This is completely expected behaviour.

**Comment by stefanos82** [comment] 2019-06-24 20:53
Yes, but should it kick me out of REPL or throw an error message and allow me to continue?

**Comment by Bowero** [comment] 2019-06-24 21:14
All errors in REPL throw you out of it. It is a good question, however, if that is what we want.

**Comment by stefanos82** [comment] 2019-06-24 21:27
Yeah, that's why I asked whether it's a bug or the expected behavior; coming from Python I don't get this kind of behavior and frankly it's annoying.

**Comment by Bowero** [comment] 2019-06-24 21:34
I must admit that I was looking at Python right now to research their solutions. I am reopening this because I hope to stimulate a discussion about REPL.

Right now, it waits until you want to print something. If you do, it decides to generate a file, compiles that and output the results. This is good enough as a temporary fix, but needs research.

**Comment by stefanos82** [comment] 2019-06-24 21:41
By the way, can we add a third option for tickets call "Other", because my case wasn't clear enough whether it fell under Bug category or normal behavior.

I'm sure people would have more generic questions to ask and "Bug" and Feature" templates are a bit restrictive.

**Comment by Bowero** [comment] 2019-06-24 21:44
You can choose for a custom issue (it's a small link under the templates) if you have something else.

**Comment by stefanos82** [comment] 2019-06-24 21:47
Ah I didn't see it :+1:

**Comment by Glitchfix** [comment] 2019-07-05 04:13
@stefanos82 @Bowero @medvednikov 
I am doing a PR for the third time but no one noticed it yet.
https://github.com/vlang/v/pull/997

This makes the vrepl more interactive now. Try it out please.

**Comment by nedpals** [comment] 2019-07-07 02:58
PR #997 has been merged. @stefanos82 let us know about the REPL if it's still has a similar issue/behavior prior to the PR.

**Comment by stefanos82** [comment] 2019-07-07 10:09
Just fetched the latest HEAD; I run the original code from this ticket and does not print anything. Anyway...I'm off.

Keep up the good work.

**Comment by Bowero** [comment] 2019-08-26 14:07
Now it does. Thanks everyone!

**Closed by Bowero** 2019-08-26 14:07 UTC
Labels: discussion, needs more info, question
