### ISSUE TITLE
vfmt Segmentation fault

### ISSUE THREAD

**Issue by earoc** [vlang/v#5651] opened 2020-07-04 08:52 UTC
**V version:**  V 0.1.28 9569655
**OS:**  Ubuntu 18.04

**What did you do?**
vfmt my file.

**What did you expect to see?**
vfmt success or report errors
 
**What did you see instead?**
`V panic: array.get: index out of range (i == 9, a.len == 9)
vfmt.tmp.c:?:                                  |       0x404ea2 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x443800 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x44c84f | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x44af41 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x444218 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x446e44 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x4406bb | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x44b6b3 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x444606 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x441252 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x44b6b3 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x444606 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x441252 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x44b6b3 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x444606 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x441252 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x4419e1 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x44b6b3 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x444606 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x441252 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x4419e1 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x44b6b3 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x444606 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x441252 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x447955 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x4412ff | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x44006f | /home/user/apps/v/cmd/tools/vfmt() 
vfmt.tmp.c:?:                                  |       0x47137a | /home/user/apps/v/cmd/tools/vfmt() 
vfmt.tmp.c:?:                                  |       0x470194 | /home/user/apps/v/cmd/tools/vfmt() 
                                               |       0x465954 | /home/user/apps/v/cmd/tools/vfmt() 
                                               | 0x7f89e0ebbb97 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) 
                                               |       0x401dca | /home/user/apps/v/cmd/tools/vfmt() 
Segmentation fault

Encountered a total of: 1 errors.`

**Comment by nedpals** [comment] 2020-07-04 09:15
@earoc can you share your code that you want to format?

**Comment by earoc** [comment] 2020-07-04 10:22
> @earoc can you share your code that you want to format?

Sorry, the code is about 500 lines and related to my biz. I cannot share it out. But I can compile it and run it properly while can't be VFMTed.
Looks like it's because of the code itself. Maybe I should close this issue report.

**Comment by nedpals** [comment] 2020-07-04 11:13
No it's cool. We just want to reproduce it by ourselves so that we can find out the cause.

**Comment by medvednikov** [comment] 2020-07-06 19:47
Can you run 

```v -cg self && v fmt file.v```

**Comment by earoc** [comment] 2020-07-07 10:43
Looks like no more details generated.

```
user@user-vme5:~/gits/msy_v$ v -cg self && v fmt vdemain.v
V self compiling (-cg)...
V panic: array.get: index out of range (i == 9, a.len == 9)
vfmt.tmp.c:?:                                  |       0x404ea2 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x443800 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x44c84f | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x44af41 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x444218 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x446e44 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x4406bb | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x44b6b3 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x444606 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x441252 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x44b6b3 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x444606 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x441252 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x44b6b3 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x444606 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x441252 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x4419e1 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x44b6b3 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x444606 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x441252 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x4419e1 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x44b6b3 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x444606 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x441252 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x443a9b | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x447955 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x4412ff | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x44006f | /home/user/apps/v/cmd/tools/vfmt()
vfmt.tmp.c:?:                                  |       0x47137a | /home/user/apps/v/cmd/tools/vfmt()
vfmt.tmp.c:?:                                  |       0x470194 | /home/user/apps/v/cmd/tools/vfmt()
                                               |       0x465954 | /home/user/apps/v/cmd/tools/vfmt()
                                               | 0x7fd8ea7cfb97 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)
                                               |       0x401dca | /home/user/apps/v/cmd/tools/vfmt()
Segmentation fault

Encountered a total of: 1 errors.

```

**Comment by serkonda7** [comment] 2020-11-06 12:34
@earoc could you please run `v up` and see if the segfault is fixed.

**Comment by serkonda7** [comment] 2020-11-18 21:35
Closing this due to no respond. If you encounter this bug again please open a new issue.

**Closed by serkonda7** 2020-11-18 21:35 UTC
Labels: Bug, Status: Needs More Info, Unit: vfmt
