### ISSUE TITLE
Cross compile under Ubuntu does not work

### ISSUE THREAD

**Issue by resch512** [vlang/v#1789] opened 2019-08-29 22:43 UTC
**V version:** 0.1.18
**OS:** Ubuntu
clang and winroot is installed

**What did you do?**
v -os windows hello_world.v

**What did you expect to see?**
compile for windows
 
**What did you see instead?**
Cross compiling for Windows...
clang: error: no such file or directory: '/home/andreas//.vmodules///home/andreas/v/examples/hello_world.tmp.c'
clang: error: no input files
Cross compilation for Windows failed. Make sure you have clang installed.

**Comment by Danil-Lapirow** [comment] 2019-08-30 12:36
Path to .c file is broken.
winroot's `#include`s are broken.
When I fixed winroot, linking still doesnt work.
`lld-link command is not found`. Also I cant install lld-link on ubuntu 18.

**Comment by Danil-Lapirow** [comment] 2019-08-30 12:51
Also it's a duplicate of https://github.com/vlang/v/issues/920

**Comment by Bowero** [comment] 2019-09-10 17:30
Closed as a duplicate of #920.

**Closed by Bowero** 2019-09-10 17:30 UTC
Labels: bug
