### ISSUE TITLE
Option limits

### ISSUE THREAD

**Issue by radare** [vlang/v#3108] opened 2019-12-16 13:02 UTC
**V version:** V 0.1.23 9dd86a2
**OS:** macOS 10.15

**What did you do?**

try to return a big optional struct with many strings and arrays of strings inside which makes it bigger than 300 bytes..

**What did you expect to see?**

no issueas at all because option should keep a pointer to the data and provide function pointers to manage it

**What did you see instead?**

 ```
 16 fn opt_ok(data voidptr, size int) Option {
 17         if size >= 300 {
 18                 panic('option size too big: $size (max is 300), this is a temporary limit')
 19         }
```

**Comment by lutherwenxu** [comment] 2020-05-24 05:28
Duplicate of #1709.

**Closed by lutherwenxu** 2020-05-24 05:28 UTC
Labels: Bug, Unit: vlib
