### ISSUE TITLE
error: use of undeclared identifier 

### ISSUE THREAD

**Issue by mstfe** [vlang/v#10845] opened 2021-07-17 18:05 UTC
**V doctor:**
```
OS: macos, macOS, 11.4, 20F71
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
CC version: Apple clang version 12.0.5 (clang-1205.0.22.9)

getwd: /Users/mustafaekicim
vmodules: /Users/mustafaekicim/.vmodules
vroot: /Users/mustafaekicim/Projects/v
vexe: /Users/mustafaekicim/Projects/v/v
vexe mtime: 2021-07-17 17:48:17
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 6edfb2c

Git version: git version 2.30.1 (Apple Git-130)
Git vroot status: weekly.2021.28-63-g6edfb2c7
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 689c8a02
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg /Users/mustafaekicim/Projects/vlang-sample/Untitled-1.v`
```v
module main

import vweb

struct App {
	vweb.Context
}

fn main() {
	vweb.run(&App{}, 8081)
}

pub fn (mut app App) index() vweb.Result {
	return app.text('Hello world from vweb!')
}
```

**What did you expect to see?**

**What did you see instead?**
```
==================
     ^
/tmp/v/Untitled-1.5197793490418595140.tmp.c:20827:20: error: use of undeclared identifier 'OPENSSL_INIT_LOAD_SSL_STRINGS'
                OPENSSL_init_ssl(OPENSSL_INIT_LOAD_SSL_STRINGS, 0);
                                 ^
/tmp/v/Untitled-1.5197793490418595140.tmp.c:21170:29: error: implicit declaration of function 'TLS_method' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        SSL_CTX* ctx = SSL_CTX_new(TLS_method());
                                   ^
/tmp/v/Untitled-1.5197793490418595140.tmp.c:21170:29: note: did you mean 'TLSv1_method'?
/opt/local/include/openssl/ssl.h:1870:19: note: 'TLSv1_method' declared here
const SSL_METHOD *TLSv1_method(void);           /* TLSv1.0 */
                  ^
/tmp/v/Untitled-1.5197793490418595140.tmp.c:21170:29: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const SSL_METHOD *' (aka 'const struct ssl_method_st *') [-Wint-conversion]
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

**Comment by danieldaeschle** [comment] 2021-07-23 20:45
I can't reproduce it. Do you have OpenSSL installed?

**Comment by spaceface777** [comment] 2021-07-23 21:28
Closing as a duplicate of #10869.

**Comment by danieldaeschle** [comment] 2021-07-23 21:52
@medvednikov this OS is not old

**Closed** 2022-07-14 06:52 UTC
