### ISSUE TITLE
[Bug] Structure method in variable

### ISSUE THREAD

**Issue by valipan** [vlang/v#5411] opened 2020-06-18 08:15 UTC
**V version:** 0.1.27 b806fff
**OS:** linux amd64

**What did you do?**
```
struct Structure {
}
fn (s Structure) method(){
}

fn main() {
	s := Structure{}
	var_mtd := s.method
	var_mtd()
}
```

**What did you expect to see?**
I expected the program to compile successfully.
 
**What did you see instead?**
```
fn_method_var.v:13:15: error: type `Structure` has no field or method `method`
   11 |     s := Structure{}
   12 |
   13 |     var_mtd := s.method
      |                  ~~~~~~
   14 |
   15 |     var_mtd()
fn_method_var.v:15:2: error: unknown function: var_mtd
   13 |     var_mtd := s.method
   14 |
   15 |     var_mtd()
      |     ~~~~~~~~~
   16 |
   17 | }
```

**Comment by spytheman** [comment] 2020-06-18 10:31
It is not clear to me, what that should do... We do not have closures yet, and struct methods need the struct instance as its first parameter.

**Comment by medvednikov** [comment] 2020-06-18 10:40
This will be supported, it isn't yet.

**Comment by ntrel** [comment] 2020-08-19 11:16
Duplicate of #4090

**Closed by ntrel** 2020-08-19 11:16 UTC
Labels: Bug
