### ISSUE TITLE
for loop error

### ISSUE THREAD

**Issue by sh0f** [vlang/v#5562] opened 2020-06-29 14:27 UTC
**V version:** 0.1.28.1
**OS:** linux

**What did you do?**
```v
m := {'a': 'b', 'c': 'd'}
mut arr := []string{}
for k, _ in m {
	arr << k
}
println(arr)
```
**What did you expect to see?**
```v
['a', 'c']
```
**What did you see instead?**
```v
['
```

**Comment by yuyi98** [comment] 2020-06-29 15:15
```v
m := {'a': 'b', 'c': 'd'}
mut arr := []string{}
for k, _ in m {
	arr << k.clone()
}
println(arr)
```
It can work.

**Comment by Ivo-Balbaert** [comment] 2020-06-30 09:32
I'm seeing the same issue too; moreover on Windows, this code example outputs:
['P', 'c']     

I'm sure this is a regression. It worked on a V 0.1.28 of some days ago!

**Comment by spytheman** [comment] 2020-07-01 07:36
I can confirm that is a regression. It works in 7be9526 and does:
```
0[10:34:06]delian@nemesis: /ssd2/opt/v_linux/v $ /dev/shm/v_at_7be9526/v run /v/vvvv/aa.v
['a', 'c']
```
I am still bisecting where it regressed.

**Comment by spytheman** [comment] 2020-07-01 07:46
It regressed in 1848eb09 :
![regression commit](https://url4e.com/gyazo/images/6eb01c40.png)

**Comment by yuyi98** [comment] 2020-07-01 07:57
There's a real problem in this, and this PR exposes the problem because the memory has been freed.

**Comment by spytheman** [comment] 2020-07-01 07:59
I agree. The keys array is freed after the loop, but the values are used in the << operation.

**Comment by spytheman** [comment] 2020-07-01 08:00
Yesterday, there was another bug that was fixed by doing `g.optionals << styp.clone()` too. I think the fix should be in the implementation of `<<`

**Comment by spytheman** [comment] 2020-07-01 08:02
@yuyi98 why did you close https://github.com/vlang/v/pull/5592 ? I think you were on the right track to solving it. Was there another problem?

**Comment by yuyi98** [comment] 2020-07-01 08:02
I add `array_clone` in it, but memory leak.

**Comment by spytheman** [comment] 2020-07-01 08:02
with -autofree ?

**Comment by yuyi98** [comment] 2020-07-01 08:03
no -autofree

**Comment by yuyi98** [comment] 2020-07-01 08:05
I don't know how to solve this problem. Is it resolved in the parser stage?

**Comment by spytheman** [comment] 2020-07-01 08:31
hm, you are right; doing an implicit clone will need much more work and analysis

**Comment by spytheman** [comment] 2020-07-01 08:44
I think I have a working solution for the `for k,v in map {} case only.

**Comment by spytheman** [comment] 2020-07-01 08:52
Fixed in ca1f47a :
![for k,v in map{} fix](https://url4e.com/gyazo/images/1cdfeb15.png)

**Closed by spytheman** 2020-07-01 08:52 UTC
Labels: Bug
