### ISSUE TITLE
CompIf is not working well under script mode

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#7757] opened 2020-12-31 16:27 UTC
**V version:** 
latest master 

**OS:** 
win10

**What did you do?**
Save below as .v, compile with `-cc gcc`, run exe
```V
	$if gcc {
		println('using gcc')
	} $else $if tinyc {
		println('using tcc')
	} $else $if msvc {
		println('using msvc')
	}
```

**What did you expect to see?**
show `using gcc`
 
**What did you see instead?**
```
C:\Users\Roy\AppData\Local\Temp\v\sample.4853079811961913305.tmp.c:356:18: error: expected declaration specifiers or '...' before '(' token
 #define _SLIT(s) ((string){.str=(byteptr)("" s), .len=(sizeof(s)-1), .is_lit=1})
                  ^
C:\Users\Roy\AppData\Local\Temp\v\sample.4853079811961913305.tmp.c:8412:10: note: in expansion of macro '_SLIT'
  println(_SLIT("using gcc"));
          ^~~~~
```

**Note**
if main() is added, as following, then it works as expected
```V
fn main() {
	$if gcc {
		println('using gcc')
	} $else $if tinyc {
		println('using tcc')
	} $else $if msvc {
		println('using msvc')
	}
}
```

**Comment by spaceface777** [comment] 2020-12-31 16:38
Duplicate of #6419, see that issue for more info.

**Closed by spaceface777** 2020-12-31 16:38 UTC
Labels: Bug
