### ISSUE TITLE
WHEN *embed struct* is coming? I am right here waitting for you.

### ISSUE THREAD

**Issue by changrui** [vlang/v#5905] opened 2020-07-21 03:00 UTC
*embed struct* is very useful for vOOP programming, I am just here waitting for you.

thx.

**Comment by Delta456** [comment] 2020-07-21 03:14
@changrui I think this will be in roadmap of 0.3. If you want to implement this then you can give it a try.

**Comment by nedpals** [comment] 2020-07-22 10:21
Closed. Duplicate of #170.

**Closed by nedpals** 2020-07-22 10:21 UTC
Labels: Feature Request
