### ISSUE TITLE
V has trouble comparing arrays

### ISSUE THREAD

**Issue by Trivaxy** [vlang/v#2531] opened 2019-10-24 17:55 UTC
**V version:** 0.1.21-580abe0
**OS:** Windows

**What did you do?**
```v
quad := vquad.Quadratic{-76.345779901, 22283.225145, 852393.346132}
assert quad.roots() == [45.276032118195971, 246.59635655731913]
```
`quad.roots()` returns a `[]f64`.

**What did you expect to see?**
The `assert` should evaluate to true.
 
**What did you see instead?**
V complains with the following error:
```
vquad\tests\vquad_test.v:20:2: expected type `[]f64`, but got `[]f32`
   19|  assert quad.roots() == [45.276032118195971, 246.59635655731913]
   20|
        ^
```
Switching both operands produces the same error.

Wrapping the floats like so:
```v
assert quad.roots() == [f64(45.276032118195971), f64(246.59635655731913)]
```
Produces an internal C error:
```
C compiler=gcc
all .v files:
["C:\Users\itsme\v\vlib\builtin\array.v", "C:\Users\itsme\v\vlib\builtin\builtin.v", "C:\Users\itsme\v\vlib\builtin\float.v", "C:\Users\itsme\v\vlib\builtin\hashmap.v", "C:\Users\itsme\v\vlib\builtin\int.v", "C:\Users\itsme\v\vlib\builtin\map.v", "C:\Users\itsme\v\vlib\builtin\option.v", "C:\Users\itsme\v\vlib\builtin\string.v", "C:\Users\itsme\v\vlib\builtin\utf8.v", "C:\Users\itsme\v\vlib\strings\builder_c.v", "C:\Users\itsme\v\vlib\strings\similarity.v", "C:\Users\itsme\v\vlib\strings\strings.v", "C:\Users\itsme\v\vlib\strconv\atoi.v", "C:\Users\itsme\v\vlib\math\bits.v", "C:\Users\itsme\v\vlib\math\const.v", "C:\Users\itsme\v\vlib\math\math.v", "C:\Users\itsme\v\vlib\math\unsafe.v", "C:\Users\itsme\Desktop\Workspace\vquad\vquad.v", "C:\Users\itsme\Desktop\Workspace\vquad\tests\vquad_test.v"]
C:\Users\itsme\Desktop\Workspace\vquad\tests\vquad_test.v: In function 'main__test_roots':
C:\Users\itsme\Desktop\Workspace\vquad\tests\vquad_test.v:19:46: error: invalid operands to binary == (have 'array_f64' {aka 'struct array'} and 'array' {aka 'struct array'})
  assert quad.roots() == [f64(45.276032118195971), f64(246.59635655731913)]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
V error: C error. This should never happen.
```
Doing the following:
```v
quad := vquad.Quadratic{-76.345779901, 22283.225145, 852393.346132}
mut x := []f64
x << 45.276032118195971
x << 246.59635655731913
assert quad.roots() == x
```
generates the same C error as before.

According to @LorenzoPirro this issue happens with all types.

**Comment by LorenzoPirro** [comment] 2019-10-26 19:42
@Trivaxy actually whatever comparison with `[T] == [T]` doesn't work. I've tried int, string, f32 ecc

**Comment by Trivaxy** [comment] 2019-10-27 14:03
@LorenzoPirro Thanks for the confirmation, I updated the issue title and description.

**Comment by medvednikov** [comment] 2019-10-27 14:13
Comparing arrays is not supported yet, but it will be.

**Comment by Danil-Lapirow** [comment] 2019-10-28 06:27
> Comparing arrays is not supported yet, but it will be.

Compile time code generation?

**Comment by Danil-Lapirow** [comment] 2019-10-28 06:29
Unsupported feature is not a bug, so in order to close this issue we need to block people from comparing arrays. You can create a new feature request.

**Closed** 2019-10-28 07:26 UTC
Labels: bug
