### ISSUE TITLE
Playgroud test code not compile

### ISSUE THREAD

**Issue by carlosjustino** [vlang/v#4565] opened 2020-04-23 18:05 UTC
**V version:** 
playground online
**OS:** 
windows 10, chrome Versão 81.0.4044.122 (Versão oficial) 64 bits

**What did you do?**
I execute the code from Playground example

```
import json

struct User {
	name          string
	age           int
mut: 
	is_registered bool
}

fn main() {
	s := '[{ "name":"Frodo", "age":25}, {"name":"Bobby", "age":10}]'
	mut users := json.decode( []User, s) or {
		eprintln('Failed to parse json')
		return 
	}
	for user in users {
		println('$user.name: $user.age')
	}
	println('')
	for i, user in users {
		println('$i) $user.name')
		if !user.can_register() {
			println('Cannot register $user.name, they are too young')
			continue 
		}
		users[i].register() // 'user' is immutable, we have to modify the array 
	}
	// Let's encode users again just for fun
	println('')
	println(json.encode(users))
}

fn (u User) can_register() bool {
        return u.age >= 16
}

fn (u mut User) register() {
        u.is_registered = true
}
```
**What did you expect to see?**
the result
 
**What did you see instead?**
The page ask me to open this issue
![v](https://user-images.githubusercontent.com/12814105/80133454-a2f63880-8573-11ea-9415-7943e2cace1e.png)

> You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

[playground](https://vlang.io/play

)

**Comment by lutherwenxu** [comment] 2020-04-24 02:08
Duplicate of #4273. Closing.

**Closed by lutherwenxu** 2020-04-24 02:08 UTC
Labels: Bug
