### ISSUE TITLE
Playground Example of Json Encoding Fails to Run

### ISSUE THREAD

**Issue by Brainz456** [vlang/v#3573] opened 2020-01-27 14:05 UTC
**V version:**  Unsure
**OS:**  Ubuntu - Firefox

**What did you do?**
Tried to run the JSON example on the playground site

**What did you expect to see?**
The playground compiles and run the Example program
 
**What did you see instead?**
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by elimisteve** [comment] 2020-01-31 05:02
Fix created! https://github.com/vlang/website/pull/126 . Just waiting for @medvednikov to merge it in. Thanks for the report :+1: .

**Comment by exastencil** [comment] 2020-02-05 10:05
@elimisteve Alex said it's live, so I think this can be closed now.

**Comment by exastencil** [comment] 2020-02-05 10:32
That pull request has been merged, but I just checked on the playground and it is still broken. I've run the code locally on the latest V without issue, so maybe something is up with the `/compiler` endpoint? Perhaps it isn't using the latest build.

**Comment by elimisteve** [comment] 2020-02-05 11:11
@exastencil Oops, sorry; I fixed 2 _other_ examples, but the JSON one still doesn't work -- you are right.

Strangely, this example has compiled just fine for me using the last several versions of V, but in the V Playground it still says:

> You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by exastencil** [comment] 2020-02-05 11:14
Yeah, I had a look to see what happens when `/compile` is hit, but it's not in `vlang/website` as far as I can tell. And it builds for me, so I'm not sure what the error is, or how to find it.

**Comment by alexesprit** [comment] 2020-02-26 10:00
Closed as a duplicate of #3327.

**Closed by alexesprit** 2020-02-26 10:00 UTC
Labels: OS: Playground, Status: Duplicate, Type: Bug
