### ISSUE TITLE
Single-File Reflection C Builder Error

### ISSUE THREAD

**Issue by Cons-Cat** [vlang/v#10766] opened 2021-07-11 20:48 UTC
**V version:** V 0.2.2 477d442.9d241f7
**OS:** Void Linux

**What did you do?**
`cat dump.v`
```v
module main

const condition = true

$if condition {
	println('true')
} $else {
	println('false')
}
```

**What did you expect to see?**
Run `v run dump.v` and see printed out `true`, because this is the only file in this V program.
 
**What did you see instead?**
```v
==================
/usr/lib64/crt1.o: error: Invalid relocation entry [14] '.rela.debug_info' @ 000004f6
tcc: error: file 'crt1.o' not found
/tmp/v/dump.6284794107231855788.tmp.c:10177: error: identifier expected
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.
```
If the $if-$else body is all wrapped in `fn main() {}`, it works correctly. Specifying `module main` has no effect on the error. If `condition` is false, this compiles, but has the same issue as #10767.

**Comment by spaceface777** [comment] 2021-07-14 14:29
Duplicate of #6419.

**Closed by spaceface777** 2021-07-14 14:29 UTC
Labels: Bug
