### ISSUE TITLE
const of array of function does not compile

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#3027] opened 2019-12-10 11:06 UTC
**V version:** 
**OS:** 
https://vlang.io/play
**What did you do?**
```
fn rgb(r, g, b int) { 
	return 
} 

const (
cl = [rgb,rgb]
)

fn main() {
}  
```
error:
```
You just found a bug. V should either compile this program or return an error. 

Please create a GitHub issue.

This program has been saved, and the bug will be fixed asap.
```

**Comment by lutherwenxu** [comment] 2020-01-12 12:26
The two lines generated that is invalid is:
```
  600 | array_fn (int,int,int) main__cl;
 3890 | main__cl = new_array_from_c_array(2, 2, sizeof(fn (int,int,int)), EMPTY_ARRAY_OF_ELEMS( fn (int,int,int), 2 ) {  main__rgb ,  main__rgb  });
```

It would seem like V is assuming the types in V would work directly in C.

**Comment by lutherwenxu** [comment] 2020-01-12 12:29
Closing as it's a duplicate of #2991.

**Closed by lutherwenxu** 2020-01-12 12:29 UTC
Labels: bug, playground
