### ISSUE TITLE
v up failure if not executed in VROOT dir

### ISSUE THREAD

**Issue by wh-timme** [vlang/v#2269] opened 2019-10-09 11:04 UTC
**V version:** V 0.1.20 104e4c9
**OS:** Win10 1809

**What did you do?**
C:\Users\Administrator\Desktop>v up
(Not Executed in VROOT)

**What did you expect to see?**
successful build, even outside VROOT
 
**What did you see instead?**
```
Updating V...
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
   104e4c9..80a6d78  master     -> origin/master
Updating 104e4c9..80a6d78
Fast-forward
 .github/PULL_REQUEST_TEMPLATE                    |    4 +-
 .github/workflows/ci.yml                         |   49 +-
 .gitignore                                       |    9 +-
 .travis.yml                                      |    9 +-
 CHANGELOG.md                                     |   18 +-
 CONDUCT.md => CODE_OF_CONDUCT.md                 |    3 +
 CONTRIBUTING.md                                  |   24 +-
 Makefile                                         |    9 +-
 README.md                                        |   44 +-
 compiler/cc.v                                    |  130 +-
 compiler/cflags.v                                |   75 +-
 compiler/cgen.v                                  |   22 +-
 compiler/cheaders.v                              |   20 +-
 compiler/compile_errors.v                        |  270 ++
 compiler/comptime.v                              |   73 +-
 compiler/fn.v                                    |  543 +--
 compiler/gen_c.v                                 |  141 +-
 compiler/gen_js.v                                |   31 +-
 compiler/live.v                                  |   56 +-
 compiler/main.v                                  |  720 ++--
 compiler/module_header.v                         |  219 ++
 compiler/modules.v                               |   30 +-
 compiler/msvc.v                                  |  170 +-
 compiler/optimization.v                          |   40 +
 compiler/parser.v                                | 1288 ++++---
 compiler/parser2.v                               |    6 +-
 compiler/query.v                                 |    6 +-
 compiler/repl.v                                  |   78 +-
 compiler/scanner.v                               |  265 +-
 compiler/table.v                                 |  171 +-
 compiler/tests/fixed_array_test.v                |   32 +
 compiler/tests/fn_multiple_returns_test.v        |   19 +
 compiler/tests/fn_test.v                         |   69 +-
 compiler/tests/fn_variadic_test.v                |   15 +
 compiler/tests/module_test.v                     |    2 +-
 compiler/tests/mut_test.v                        |   32 +-
 compiler/tests/option_test.v                     |    8 +
 compiler/tests/repl/.gitignore                   |    2 +
 compiler/tests/repl/chained_fields.repl          |   18 +-
 compiler/tests/repl/error_nosave.repl            |    2 +-
 compiler/tests/repl/immutable_len_fields.repl    |    6 +-
 compiler/tests/repl/runner/runner.v              |   23 +-
 compiler/tests/return_voidptr_test.v             |   23 +
 compiler/tests/str_gen_test.v                    |    6 +-
 compiler/tests/struct_test.v                     |  144 +-
 compiler/token.v                                 |  233 +-
 compiler/vfmt.v                                  |    4 +-
 compiler/vhelp.v                                 |    7 +-
 compiler/vtest.v                                 |  182 +
 examples/.gitignore                              |    1 +
 examples/hot_reload/graph.v                      |   20 +-
 examples/hot_reload/message.v                    |   11 +-
 examples/tetris/tetris.v                         |    1 -
 examples/vcasino/VCasino.v                       |    8 +-
 make.bat                                         |    5 +-
 october.plan                                     |   22 +
 september.plan                                   |   34 +-
 thirdparty/freetype                              |    1 -
 thirdparty/openssl/include/openssl/aes.h         |  149 -
 thirdparty/openssl/include/openssl/asn1.h        | 1424 --------
 thirdparty/openssl/include/openssl/asn1_mac.h    |  579 ---
 thirdparty/openssl/include/openssl/asn1t.h       |  973 -----
 thirdparty/openssl/include/openssl/bio.h         |  883 -----
 thirdparty/openssl/include/openssl/blowfish.h    |  130 -
 thirdparty/openssl/include/openssl/bn.h          | 1015 ------
 thirdparty/openssl/include/openssl/buffer.h      |  125 -
 thirdparty/openssl/include/openssl/camellia.h    |  132 -
 thirdparty/openssl/include/openssl/cast.h        |  107 -
 thirdparty/openssl/include/openssl/cmac.h        |   82 -
 thirdparty/openssl/include/openssl/cms.h         |  555 ---
 thirdparty/openssl/include/openssl/comp.h        |   83 -
 thirdparty/openssl/include/openssl/conf.h        |  268 --
 thirdparty/openssl/include/openssl/conf_api.h    |   89 -
 thirdparty/openssl/include/openssl/crypto.h      |  661 ----
 thirdparty/openssl/include/openssl/des.h         |  257 --
 thirdparty/openssl/include/openssl/des_old.h     |  497 ---
 thirdparty/openssl/include/openssl/dh.h          |  412 ---
 thirdparty/openssl/include/openssl/dsa.h         |  335 --
 thirdparty/openssl/include/openssl/dso.h         |  451 ---
 thirdparty/openssl/include/openssl/dtls1.h       |  272 --
 thirdparty/openssl/include/openssl/e_os2.h       |  328 --
 thirdparty/openssl/include/openssl/ebcdic.h      |   26 -
 thirdparty/openssl/include/openssl/ec.h          | 1282 -------
 thirdparty/openssl/include/openssl/ecdh.h        |  134 -
 thirdparty/openssl/include/openssl/ecdsa.h       |  335 --
 thirdparty/openssl/include/openssl/engine.h      |  960 -----
 thirdparty/openssl/include/openssl/err.h         |  390 --
 thirdparty/openssl/include/openssl/evp.h         | 1630 ---------
 thirdparty/openssl/include/openssl/hmac.h        |  109 -
 thirdparty/openssl/include/openssl/idea.h        |  105 -
 thirdparty/openssl/include/openssl/krb5_asn.h    |  240 --
 thirdparty/openssl/include/openssl/kssl.h        |  197 -
 thirdparty/openssl/include/openssl/lhash.h       |  240 --
 thirdparty/openssl/include/openssl/md4.h         |  119 -
 thirdparty/openssl/include/openssl/md5.h         |  119 -
 thirdparty/openssl/include/openssl/mdc2.h        |   94 -
 thirdparty/openssl/include/openssl/modes.h       |  163 -
 thirdparty/openssl/include/openssl/obj_mac.h     | 4194 ----------------------
 thirdparty/openssl/include/openssl/objects.h     | 1143 ------
 thirdparty/openssl/include/openssl/ocsp.h        |  637 ----
 thirdparty/openssl/include/openssl/opensslconf.h |  273 --
 thirdparty/openssl/include/openssl/opensslv.h    |   97 -
 thirdparty/openssl/include/openssl/ossl_typ.h    |  213 --
 thirdparty/openssl/include/openssl/pem.h         |  618 ----
 thirdparty/openssl/include/openssl/pem2.h        |   70 -
 thirdparty/openssl/include/openssl/pkcs12.h      |  342 --
 thirdparty/openssl/include/openssl/pkcs7.h       |  481 ---
 thirdparty/openssl/include/openssl/pqueue.h      |   99 -
 thirdparty/openssl/include/openssl/rand.h        |  150 -
 thirdparty/openssl/include/openssl/rc2.h         |  103 -
 thirdparty/openssl/include/openssl/rc4.h         |   88 -
 thirdparty/openssl/include/openssl/ripemd.h      |  105 -
 thirdparty/openssl/include/openssl/rsa.h         |  664 ----
 thirdparty/openssl/include/openssl/safestack.h   | 2672 --------------
 thirdparty/openssl/include/openssl/seed.h        |  149 -
 thirdparty/openssl/include/openssl/sha.h         |  214 --
 thirdparty/openssl/include/openssl/srp.h         |  179 -
 thirdparty/openssl/include/openssl/srtp.h        |  147 -
 thirdparty/openssl/include/openssl/ssl.h         | 3164 ----------------
 thirdparty/openssl/include/openssl/ssl2.h        |  265 --
 thirdparty/openssl/include/openssl/ssl23.h       |   84 -
 thirdparty/openssl/include/openssl/ssl3.h        |  774 ----
 thirdparty/openssl/include/openssl/stack.h       |  107 -
 thirdparty/openssl/include/openssl/symhacks.h    |  518 ---
 thirdparty/openssl/include/openssl/tls1.h        |  810 -----
 thirdparty/openssl/include/openssl/ts.h          |  865 -----
 thirdparty/openssl/include/openssl/txt_db.h      |  112 -
 thirdparty/openssl/include/openssl/ui.h          |  415 ---
 thirdparty/openssl/include/openssl/ui_compat.h   |   88 -
 thirdparty/openssl/include/openssl/whrlpool.h    |   41 -
 thirdparty/openssl/include/openssl/x509.h        | 1330 -------
 thirdparty/openssl/include/openssl/x509_vfy.h    |  652 ----
 thirdparty/openssl/include/openssl/x509v3.h      | 1055 ------
 thirdparty/vschannel/vschannel.c                 |  217 +-
 thirdparty/vschannel/vschannel.h                 |    8 +-
 tools/gen_vc.v                                   |    2 +-
 tools/performance_compare.v                      |  205 ++
 tools/vget.v                                     |   64 +-
 vlib/benchmark/benchmark.v                       |   26 +-
 vlib/benchmark/tests/always_imported.v           |   96 +
 vlib/bitfield/bitfield.v                         |    2 +-
 vlib/builtin/array.v                             |   64 +
 vlib/builtin/array_test.v                        |   80 +-
 vlib/builtin/builtin.v                           |   14 +-
 vlib/builtin/hashmap.v                           |   84 +
 vlib/builtin/hashmap_test.v                      |   33 +
 vlib/builtin/int.v                               |   85 +-
 vlib/builtin/int_test.v                          |   36 +
 vlib/builtin/js/array.v                          |    5 +
 vlib/builtin/js/hashmap.v                        |   13 +
 vlib/builtin/map.v                               |    2 +-
 vlib/builtin/map_test.v                          |    2 +-
 vlib/builtin/string.v                            |   95 +-
 vlib/builtin/string_test.v                       |   18 +
 vlib/crypto/aes/aes.v                            |    1 -
 vlib/crypto/aes/aes_cbc.v                        |    2 +-
 vlib/crypto/aes/block_generic.v                  |   52 +-
 vlib/crypto/aes/cypher_generic.v                 |    4 +-
 vlib/crypto/md5/md5.v                            |   15 +-
 vlib/crypto/rand/rand.v                          |    2 +-
 vlib/crypto/rand/utils.v                         |    4 +-
 vlib/crypto/rc4/rc4.v                            |    8 +-
 vlib/crypto/sha1/sha1.v                          |   11 +-
 vlib/crypto/sha1/sha1block_generic.v             |   12 +-
 vlib/crypto/sha256/sha256.v                      |   11 +-
 vlib/crypto/sha256/sha256block_generic.v         |    7 +-
 vlib/crypto/sha512/sha512.v                      |   15 +-
 vlib/crypto/sha512/sha512block_generic.v         |   15 +-
 vlib/darwin/darwin.v                             |   25 +-
 vlib/encoding/base64/base64_test.v               |   38 +-
 vlib/encoding/binary/binary.v                    |   24 +-
 vlib/encoding/csv/reader.v                       |    2 +-
 vlib/flag/flag.v                                 |  116 +-
 vlib/flag/flag_test.v                            |   16 +-
 vlib/freetype/freetype.v                         |    7 +-
 vlib/gl/1shader.v                                |    2 +-
 vlib/gl/gl.v                                     |    3 +
 vlib/glfw/glfw.v                                 |    9 +
 vlib/glm/glm_test.v                              |    4 +-
 vlib/http/backend_nix.v                          |   16 +-
 vlib/http/backend_win.v                          |    5 +-
 vlib/http/download_nix.v                         |    2 -
 vlib/http/http.v                                 |    1 +
 vlib/http/http_test.v                            |   11 +-
 vlib/json/json_test.exp                          |  Bin 10713 -> 0 bytes
 vlib/json/json_test.lib                          |  Bin 18400 -> 0 bytes
 vlib/math/bits/bits.v                            |   98 +-
 vlib/math/math_test.v                            |    6 +-
 vlib/mysql/mysql.v                               |    6 +-
 vlib/net/socket.v                                |   21 +-
 vlib/net/socket_test.v                           |   23 +-
 vlib/net/socket_udp_test.v                       |    2 +-
 vlib/net/urllib/urllib.v                         |    6 +-
 vlib/os/os.v                                     |  112 +-
 vlib/os/os_win.v                                 |   14 +-
 vlib/os2/os2_mac.v                               |   32 +
 vlib/os2/os2_test.v                              |   11 +
 vlib/pg/pg.v                                     |    7 +-
 vlib/rand/pcg32.v                                |   58 +
 vlib/rand/pcg32_test.v                           |   27 +
 vlib/rand/splitmix64.v                           |   42 +
 vlib/rand/splitmix64_test.v                      |   26 +
 vlib/readline/readline_lin.v                     |  118 +-
 vlib/stbi/stbi.v                                 |    3 +-
 vlib/strings/{builder.v => builder_c.v}          |    2 +-
 vlib/strings/builder_js.v                        |   43 +
 vlib/strings/similarity.v                        |    3 +-
 vlib/strings/strings.v                           |    7 +-
 vlib/sync/sync_win.v                             |    1 -
 vlib/szip/szip.v                                 |   10 +-
 vlib/term/can_show_color.v                       |   27 +
 vlib/term/can_show_color_nix.v                   |   11 +
 vlib/term/can_show_color_win.v                   |   10 +
 vlib/term/colors.v                               |    2 -
 vlib/term/colors_win.v                           |    2 -
 vlib/time/time.v                                 |    9 +-
 vlib/ui/examples/users_gui/users.v               |  105 +-
 vlib/ui/ui_mac.v                                 |    2 -
 vlib/vweb/assets/assets.v                        |    2 +-
 vlib/vweb/tmpl/tmpl.v                            |    2 +-
 vlib/vweb/vweb.v                                 |    1 -
 221 files changed, 5414 insertions(+), 41349 deletions(-)
 rename CONDUCT.md => CODE_OF_CONDUCT.md (54%)
 create mode 100644 compiler/compile_errors.v
 create mode 100644 compiler/module_header.v
 create mode 100644 compiler/optimization.v
 create mode 100644 compiler/tests/fixed_array_test.v
 create mode 100644 compiler/tests/fn_multiple_returns_test.v
 create mode 100644 compiler/tests/fn_variadic_test.v
 create mode 100644 compiler/tests/return_voidptr_test.v
 create mode 100644 compiler/vtest.v
 create mode 100644 october.plan
 delete mode 160000 thirdparty/freetype
 delete mode 100644 thirdparty/openssl/include/openssl/aes.h
 delete mode 100644 thirdparty/openssl/include/openssl/asn1.h
 delete mode 100644 thirdparty/openssl/include/openssl/asn1_mac.h
 delete mode 100644 thirdparty/openssl/include/openssl/asn1t.h
 delete mode 100644 thirdparty/openssl/include/openssl/bio.h
 delete mode 100644 thirdparty/openssl/include/openssl/blowfish.h
 delete mode 100644 thirdparty/openssl/include/openssl/bn.h
 delete mode 100644 thirdparty/openssl/include/openssl/buffer.h
 delete mode 100644 thirdparty/openssl/include/openssl/camellia.h
 delete mode 100644 thirdparty/openssl/include/openssl/cast.h
 delete mode 100644 thirdparty/openssl/include/openssl/cmac.h
 delete mode 100644 thirdparty/openssl/include/openssl/cms.h
 delete mode 100644 thirdparty/openssl/include/openssl/comp.h
 delete mode 100644 thirdparty/openssl/include/openssl/conf.h
 delete mode 100644 thirdparty/openssl/include/openssl/conf_api.h
 delete mode 100644 thirdparty/openssl/include/openssl/crypto.h
 delete mode 100644 thirdparty/openssl/include/openssl/des.h
 delete mode 100644 thirdparty/openssl/include/openssl/des_old.h
 delete mode 100644 thirdparty/openssl/include/openssl/dh.h
 delete mode 100644 thirdparty/openssl/include/openssl/dsa.h
 delete mode 100644 thirdparty/openssl/include/openssl/dso.h
 delete mode 100644 thirdparty/openssl/include/openssl/dtls1.h
 delete mode 100644 thirdparty/openssl/include/openssl/e_os2.h
 delete mode 100644 thirdparty/openssl/include/openssl/ebcdic.h
 delete mode 100644 thirdparty/openssl/include/openssl/ec.h
 delete mode 100644 thirdparty/openssl/include/openssl/ecdh.h
 delete mode 100644 thirdparty/openssl/include/openssl/ecdsa.h
 delete mode 100644 thirdparty/openssl/include/openssl/engine.h
 delete mode 100644 thirdparty/openssl/include/openssl/err.h
 delete mode 100644 thirdparty/openssl/include/openssl/evp.h
 delete mode 100644 thirdparty/openssl/include/openssl/hmac.h
 delete mode 100644 thirdparty/openssl/include/openssl/idea.h
 delete mode 100644 thirdparty/openssl/include/openssl/krb5_asn.h
 delete mode 100644 thirdparty/openssl/include/openssl/kssl.h
 delete mode 100644 thirdparty/openssl/include/openssl/lhash.h
 delete mode 100644 thirdparty/openssl/include/openssl/md4.h
 delete mode 100644 thirdparty/openssl/include/openssl/md5.h
 delete mode 100644 thirdparty/openssl/include/openssl/mdc2.h
 delete mode 100644 thirdparty/openssl/include/openssl/modes.h
 delete mode 100644 thirdparty/openssl/include/openssl/obj_mac.h
 delete mode 100644 thirdparty/openssl/include/openssl/objects.h
 delete mode 100644 thirdparty/openssl/include/openssl/ocsp.h
 delete mode 100644 thirdparty/openssl/include/openssl/opensslconf.h
 delete mode 100644 thirdparty/openssl/include/openssl/opensslv.h
 delete mode 100644 thirdparty/openssl/include/openssl/ossl_typ.h
 delete mode 100644 thirdparty/openssl/include/openssl/pem.h
 delete mode 100644 thirdparty/openssl/include/openssl/pem2.h
 delete mode 100644 thirdparty/openssl/include/openssl/pkcs12.h
 delete mode 100644 thirdparty/openssl/include/openssl/pkcs7.h
 delete mode 100644 thirdparty/openssl/include/openssl/pqueue.h
 delete mode 100644 thirdparty/openssl/include/openssl/rand.h
 delete mode 100644 thirdparty/openssl/include/openssl/rc2.h
 delete mode 100644 thirdparty/openssl/include/openssl/rc4.h
 delete mode 100644 thirdparty/openssl/include/openssl/ripemd.h
 delete mode 100644 thirdparty/openssl/include/openssl/rsa.h
 delete mode 100644 thirdparty/openssl/include/openssl/safestack.h
 delete mode 100644 thirdparty/openssl/include/openssl/seed.h
 delete mode 100644 thirdparty/openssl/include/openssl/sha.h
 delete mode 100644 thirdparty/openssl/include/openssl/srp.h
 delete mode 100644 thirdparty/openssl/include/openssl/srtp.h
 delete mode 100644 thirdparty/openssl/include/openssl/ssl.h
 delete mode 100644 thirdparty/openssl/include/openssl/ssl2.h
 delete mode 100644 thirdparty/openssl/include/openssl/ssl23.h
 delete mode 100644 thirdparty/openssl/include/openssl/ssl3.h
 delete mode 100644 thirdparty/openssl/include/openssl/stack.h
 delete mode 100644 thirdparty/openssl/include/openssl/symhacks.h
 delete mode 100644 thirdparty/openssl/include/openssl/tls1.h
 delete mode 100644 thirdparty/openssl/include/openssl/ts.h
 delete mode 100644 thirdparty/openssl/include/openssl/txt_db.h
 delete mode 100644 thirdparty/openssl/include/openssl/ui.h
 delete mode 100644 thirdparty/openssl/include/openssl/ui_compat.h
 delete mode 100644 thirdparty/openssl/include/openssl/whrlpool.h
 delete mode 100644 thirdparty/openssl/include/openssl/x509.h
 delete mode 100644 thirdparty/openssl/include/openssl/x509_vfy.h
 delete mode 100644 thirdparty/openssl/include/openssl/x509v3.h
 create mode 100644 tools/performance_compare.v
 create mode 100644 vlib/benchmark/tests/always_imported.v
 create mode 100644 vlib/builtin/hashmap.v
 create mode 100644 vlib/builtin/hashmap_test.v
 create mode 100644 vlib/builtin/js/hashmap.v
 delete mode 100644 vlib/json/json_test.exp
 delete mode 100644 vlib/json/json_test.lib
 create mode 100644 vlib/os2/os2_mac.v
 create mode 100644 vlib/os2/os2_test.v
 create mode 100644 vlib/rand/pcg32.v
 create mode 100644 vlib/rand/pcg32_test.v
 create mode 100644 vlib/rand/splitmix64.v
 create mode 100644 vlib/rand/splitmix64_test.v
 rename vlib/strings/{builder.v => builder_c.v} (94%)
 create mode 100644 vlib/strings/builder_js.v
 create mode 100644 vlib/term/can_show_color.v
 create mode 100644 vlib/term/can_show_color_nix.v
 create mode 100644 vlib/term/can_show_color_win.v
Current branch master is up to date.
Building V
git version 2.23.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
rebuild from source (twice, in case of C definitions changes)
vlib not found, downloading it...
fatal: destination path '.' already exists and is not an empty directory.
failed to `git clone` vlib
make sure you are online and have git installed
V error: compiler doesn't exist
v.exe failed to compile itself - Create an issue at 'https://github.com/vlang'
```
after all this, v is renamed to v_old.exe and no longer executable

**Comment by medvednikov** [comment] 2019-10-10 20:11
Works for me, looks like a Windows issue.

Will have a look, thanks.

**Comment by Ivo-Balbaert** [comment] 2019-12-11 11:30
When I try to do this from that folder in Windows 10, I get:

...
Now using V to build V...
C:\Users\CVO\AppData\Local\Temp\v\v.exe.tmp.c: In function 'os__init_os_args':
C:\Users\CVO\AppData\Local\Temp\v\v.exe.tmp.c:6425:13: warning: assignment to 'void **' from incompatible pointer type 'W...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
v.exe failed to compile itself - Create an issue at 'https://github.com/vlang'

**Comment by alexesprit** [comment] 2020-01-02 15:38
@wh-timme @Ivo-Balbaert could you check if `v up` works for us from the latest master? I'm on Windows 10, and `v up` works fine for me from non-VROOT dir, as well as from VROOT dir.

**Comment by Ivo-Balbaert** [comment] 2020-01-02 16:12
For me (Windows 10) it's now ok; v up worked from 3 different arbitrary directories on my system, success!

**Comment by alexesprit** [comment] 2020-01-08 21:26
@wh-timme I'm closing this one, as it's not reproducable on the latest master, and other people confirm it's fixed for them. Please, let us know if it still an issue for you.

**Closed by alexesprit** 2020-01-08 21:26 UTC
Labels: bug
