### ISSUE TITLE
vlib/vweb/vweb.v:286:6: error: unexpected `$`, expecting `name`

### ISSUE THREAD

**Issue by UedaTakeyuki** [vlang/v#4977] opened 2020-05-21 13:50 UTC
**V version:** 
V 0.1.27 74686d0

**OS:** 
Linux raspberrypi 4.19.50+ #896 Thu Jun 20 16:09:52 BST 2019 armv6l GNU/Linux

**What did you do?**
Following the [tutorials](https://github.com/vlang/v/blob/master/tutorials/building-a-simple-web-blog-with-vweb.md),
```
v run blog.v
```

**What did you expect to see?**
Running a Vweb app on http://localhost:8080 ...

 
**What did you see instead?**
```
pi@raspberrypi:~/blog $ v run blog.v
blog.v:15:9: warning: use `(mut f Foo)` instead of `(f mut Foo)` 
   13 | }
   14 | 
   15 | fn (app mut App) index() {
      |         ~~~
   16 |     app.vweb.text('Hello, world from vweb!')
   17 | }
/home/pi/v/vlib/vweb/vweb.v:286:6: error: unexpected `$`, expecting `name` 
  284 |         println('action=$action')
  285 |     }
  286 |     app.$action() or {
      |         ^
  287 |         conn.send_string(HTTP_404) or {}
  288 |     }
```

**Comment by nedpals** [comment] 2020-05-22 04:52
vweb is still in the works.

**Comment by lutherwenxu** [comment] 2020-05-24 11:23
Duplicate of #4393.

**Closed by lutherwenxu** 2020-05-24 11:23 UTC
Labels: Bug, Status: Duplicate, Unit: vweb
