### ISSUE TITLE
File not recognized when run a example

### ISSUE THREAD

**Issue by FedericoLeiva12** [vlang/v#1244] opened 2019-07-20 00:55 UTC
**V version:** V 0.1.15
**OS:** Windows 10

**What did you do?**
I wanted to compile and execute the example of tetris. I tryed with:
`v run tetris.v`
`v -os windows tetris.v`

**What did you expect to see?**
I want to execute that example!
 
**What did you see instead?**
```
C:\v/thirdparty/glfw/glfw3.dll: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
V panic: clang error
```

**Comment by medvednikov** [comment] 2019-07-22 11:29
This is caused by a wrong architecture of the glfw3.dll file.

This will be fixed once the package manager is out later this week.

**Closed** 2020-07-15 09:17 UTC
Labels: Bug
