### ISSUE TITLE
flag: Move to submodule under cli

### ISSUE THREAD

**Issue by nyx-litenite** [vlang/v#8732] opened 2021-02-14 02:48 UTC
There is currently a `flag` module that handles  command-line arguments and a `cli` module for easily developing command-line interfaces.... But `cli` declares it's own flag type. I think these two (flag) module should be consolidated into a submodule under `cli` to reduce redundancy.

**Comment by nedpals** [comment] 2021-02-14 04:32
Closed. Duplicate of #7410

**Closed by nedpals** 2021-02-14 04:32 UTC
Labels: Feature Request
