### ISSUE TITLE
Anonymous and high order functions with C error

### ISSUE THREAD

**Issue by salva09** [vlang/v#5695] opened 2020-07-06 06:08 UTC
**V version:** V 0.1.28 78e1127.c3614c0
**OS:** Artix linux

**What did you do?**
I created an anonymous function that executes other function that is passed as an argument. \
Example code
```v
fn main() {
	test_anon_fn(my_fn)
}

fn test_anon_fn(my_anon_fn fn(x int, y int) int) {
	run_anon := fn(z int, w int) int {
		return my_anon_fn(z, w)
	}
	run_anon(0, 0)
}

fn my_fn(x int, y int) int {
	println('$x $y')
	return 0
}

```

**What did you expect to see?**
That run_anon() executed my_anon_fn() and then returned its value. \
Expected output
```
0 0
```
 
**What did you see instead?**
It throws an builder error or C error. \
Actual output
```c
==================
/home/salva/.cache/v/test.tmp.c: In function ‘anon_153_7_7_7’:
/home/salva/.cache/v/test.tmp.c:1515:10: error: implicit declaration of function ‘my_anon_fn’ [-Werror=implicit-function-declaration]
 1515 |   return my_anon_fn(z, w);
      |          ^~~~~~~~~~
/home/salva/.cache/v/test.tmp.c: In function ‘strconv__v_sprintf’:
/home/salva/.cache/v/test.tmp.c:3940:7: warning: variable ‘th_separator’ set but not used [-Wunused-but-set-variable]
 3940 |  bool th_separator = false;
      |       ^~~~~~~~~~~~
/home/salva/.cache/v/test.tmp.c: In function ‘print_backtrace_skipping_top_frames_linux’:
/home/salva/.cache/v/test.tmp.c:5060:26: warning: passing argument 1 of ‘backtrace’ from incompatible pointer type [-Wincompatible-pointer-types]
 5060 |  int nr_ptrs = backtrace(buffer, 100);
      |                          ^~~~~~
...
==================
```

**Comment by nedpals** [comment] 2020-11-30 15:09
Closed. Duplicate of #5430.

**Closed by nedpals** 2020-11-30 15:10 UTC
Labels: Bug
