### ISSUE TITLE
'map2 := unsafe {map1}' should error

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#8602] opened 2021-02-06 09:33 UTC
**V version:**
master
 
**OS:** 
win10

**What did you do?**
```V
fn main() {
	unsafe{
		mut a := {'foo':1}
		mut b := a
		a['foo'] = 100
		println(a)
		println(b)
	}
}
```

**What did you expect to see?**
```
{'foo': 100}
{'foo': 1}
```
 
**What did you see instead?**
```
{'foo': 100}
{'foo': 100}
```

**Analysis**
With `map.clone()` as workaround you get expected results.
```V
fn main() {
	mut a := {'foo':1}
	mut b := a.clone()
	a['foo'] = 100
	println(a)
	println(b)
}
```
Both two cases should be added to tests to prevent regression.

**Comment by ntrel** [comment] 2021-02-09 18:17
> unsafe{

BTW you should not use `unsafe` for more code than is necessary. If you want to do an unsafe shallow copy, you only need an unsafe *expression*: `mut b := unsafe {a}`.


> Both two cases should be added to tests to prevent regression

Using `unsafe` is an escape hatch to tell the compiler to turn off memory-safety checking. It is by design that V allows you to shallow-copy a map with `unsafe`. That is useful because the programmer may know that neither the source map nor the shallow copy will be mutated whilst the copy is live (despite one or both being potentially mutable). There is at least one case of this in the compiler (I'm currently tightening the shallow copy check).

So I think we should close this issue.

BTW While thinking about this report, I have created a third option for *moving* a mutable map into a new variable/field, resetting the original map to empty, which is memory-safe: https://github.com/vlang/v/pull/8660

**Comment by SleepyRoy** [comment] 2021-02-10 01:45
@ntrel Thanks for introduction on how to use unsafe. But the point of this issue is, `map2 := map1` should get a deep copy while now we actually get a shallow copy (reference) in V. To get a shallow copy, programmers should write `map2 := &map1` instead.

**Comment by ntrel** [comment] 2021-02-10 10:32
> map2 := map1 should get a deep copy while now we actually get a shallow copy (reference) in V. 

A shallow copy means just copying the fields of the `map` struct, but not duplicating the heap memory for the pointer fields. Having a way to get a shallow copy is useful because it is far more efficient than `clone`, and sometimes `move` would not be appropriate because you don't want the source to be reset. I needed `unsafe` shallow copy for #8662 (WIP).

> To get a shallow copy, programmers should write map2 := &map1 instead.

That is a reference to a map, and is not memory safe.

**Comment by ntrel** [comment] 2021-02-10 10:34
> map2 := map1 should get a deep copy

I forgot to say that requiring people to write `clone` is good language design - `clone` is not a cheap operation so it should not be implicit. The programmer should be aware of it and try to avoid it where possible.

**Comment by medvednikov** [comment] 2021-02-10 10:36
@ntrel exactly, that was the reasoning.

**Comment by SleepyRoy** [comment] 2021-02-10 14:25
@ntrel Thanks for explaining. I just want to say please make sure the behavior of `map2 := map1.clone()`, `map2 := map1`, `map2 := &map1`, `map2 := &&map1` clear and easy to understand by programmers, which I think many languages fail to realize.

**Comment by SleepyRoy** [comment] 2021-02-10 14:28
IMO these should be well documented once decision of behavior is made.

**Comment by dumblob** [comment] 2021-02-10 14:32
Hm, I think @SleepyRoy got surprised by the following:

current behavior:
- `:=` makes a shallow copy (only the struct which on its own is opaque to the user and thus the user thinks it "doesn't" exist because the language forces her to do so by hiding all the `map` internals and making them hardly reachable if at all)
    - shallow copy is memory unsafe (making some map data invalid - e.g. emptying the whole map - makes the other shallow copy panicking) - but this "unsafety" is **invisible** (implicit instead of explicit)
    - shallow copy is still significantly slower than a reference
- `&mymap` gets a reference
    - very useful for accessing the map from a different place
    - makes it **explicit** (nothing hidden unlike shallow copy) that it's memory unsafe
    - is the fastest way to get to the "same map content" from a different place
    - it's easier to use (and thus safer) than shallow copy
- `.clone()` is slow, but sky-clear what it does
    - shouldn't be the default because making defaults slow is always bad
- all the points above will get rather difficult to understand once map will support full concurrency & parallelism

My recommendation would be to actually move away from the current behavior and encourage the use of reference to the map (it's **explicit** and it's also the fastest way possible to access the map data from another place) and add method `.shallow_copy()` for advanced users and disable `:= mymap` with the error message `use &mymap instead (or .shallow_copy() for advanced use)`.

This what I outlined shall be then replicated for all wannabe opaque structs, so that the "API" stays the same and is clear what happens.

Thoughts?

**Comment by ntrel** [comment] 2021-02-13 11:14
> shallow copy is still significantly slower than a reference

Depends, shallow copy is probably faster if you are doing enough operations on the map and only copying it to the stack once. 

> &mymap gets a reference
> makes it explicit (nothing hidden unlike shallow copy) that it's memory unsafe

At the moment `&mymap` does not require `unsafe`, but I think it should.

> encourage the use of reference to the map

I agree that is probably better than mentioning `unsafe` in the implicit copy error message. Perhaps we could remove support for shallow copy - if a user really needs it they could use a pointer cast to same type: `*unsafe {&map[K]V(&mymap)}`.

There might be library APIs that already rely on shallow copy, but really they should be fixed.

> add method .shallow_copy() for advanced users

`unsafe` is already for advanced users. You have to know what you're doing, which is hard. But removing support for shallow copy would indeed make using `unsafe` a bit easier.

**Comment by dumblob** [comment] 2021-02-13 21:04
>I agree that is probably better than mentioning `unsafe` in the implicit copy error message. Perhaps we could remove support for shallow copy - if a user really needs it they could use a pointer cast to same type: `*unsafe {&map[K]V(&mymap)}`.

This would actually be my preference - to remove shallow copy altogether (and maybe mention in the doc of `unsafe` another example - namely the cool "trick" `*unsafe {&map[K]V(&mymap)}`).

**Closed** 2021-02-17 04:19 UTC
Labels: Bug
