### ISSUE TITLE
Embed struct in initializing struct returns error

### ISSUE THREAD

**Issue by Nuciloco** [vlang/v#10555] opened 2021-06-24 04:36 UTC
**V version:** V 0.2.2 21fe91e
**OS:** windows, Microsoft Windows 10 Home v19042 64-bit

**What did you do?**
```
struct Widget {
mut:
	x int
	y int
}

struct Button {
	Widget
	title string
}
```
I used this code from the documentation and ran this code
```
mut button := Button{
title: 'Click me'
}
button.x = 3
```
and then this code
```
mut button := Button{
title: 'Click me'
x: 3
}
```

**What did you expect to see?**
I expected to see both codes work.
 
**What did you see instead?**
This codes works completely fine
```
mut button := Button{
title: 'Click me'
}
button.x = 3
```
But this code however returns an error
```
mut button := Button{
title: 'Click me'
x: 3
}
```
The error that it returns is this
```
papp\main.v:29:3: error: unknown field `x` in struct literal of type `papp.Button`
   27 |     mut button := Button{
   28 |         title: 'Click me'
   29 |         x: 3
      |         ~~~~
   30 |     }
   31 |
```
I expected to see the second code work instead of returning an error.
It would make sense that the ``x`` field wouldn't error out in the ``Button`` struct since the ``x``and ``y`` fields are already defined from the ``Widget`` struct.

**Comment by crthpl** [comment] 2021-06-29 20:33
Duplicate of #9931

**Closed by crthpl** 2021-06-29 20:33 UTC
Labels: Bug
