### ISSUE TITLE
Nested conditional assignment results in bad C

### ISSUE THREAD

**Issue by radare** [vlang/v#3263] opened 2019-12-29 21:58 UTC
```
$ v -v
V 0.1.23 482f4c1
$ cat nest.v
```
```v
fn main() {
	a := if (1 == 1) {
		if (2 == 2) {
			'win'
		} else {
			'fail'
		}
	} else {
		'fail'
	}
	println(a)
}
```
```
$ v run nest.v
/private/var/folders/12/517hk27n0pxbnbv9yxlh4jxm0000gn/T/v/nest.tmp.c:3918:95: error: expected ')'
 (( ( 1 == 1 ) ) ? ( (( ( 2 == 2 ) ) ? ( tos3("win") ) : ( tos3("fail") )) ) : ( tos3("fail") ;
    ...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
$
```

**Comment by spytheman** [comment] 2019-12-30 08:07
This is a possible duplicate of https://github.com/vlang/v/issues/3105 .

**Closed** 2020-01-12 11:40 UTC
Labels: bug
