### ISSUE TITLE
can not compile ui with -autofree

### ISSUE THREAD

**Issue by kahsa** [vlang/v#7670] opened 2020-12-29 04:24 UTC
**V version:V 0.2 ae5cfa7** 
**OS:archlinux** 

**What did you do?**
`v -autofree ~/.vmodules/ui/examples/message.v`

**What did you expect to see?**

 
**What did you see instead?**

```
/tmp/v/message.7693844928520143754.tmp.c: In function 'ui__listbox':
/tmp/v/message.7693844928520143754.tmp.c:28011:33: error: '_t831' undeclared (first use in this function); did you mean '_t830'?
28011 |   .y = /*experimental if expr*/ _t831 /*Z*/,
      |                                 ^~~~~
      |                                 _t830
```

**Comment by serkonda7** [comment] 2020-12-29 11:50
Duplicate of #6920

**Closed by serkonda7** 2020-12-29 11:50 UTC
Labels: Bug
