### ISSUE TITLE
Can't assign fixed size array returned from function (compiler error)

### ISSUE THREAD

**Issue by fiatjaf** [vlang/v#9550] opened 2021-04-01 01:55 UTC
**V version:** V 0.2.2 205fb88.63f835c
**OS:** linux, Linux version 5.7.11-arch1-1 (linux@archlinux) (gcc version 10.1.0 (GCC), GNU ld (GNU Binutils) 2.34.0) #1 SMP PREEMPT Wed, 29 Jul 2020 21:38:21 +0000

**What did you do?**
Tried to compile this:
```v
fn main() {
    x := get3()
    dump(x)
}

fn get3() [3]int {
    mut res := [3]int{}
    res[0] = 1
    res[1] = 2
    res[2] = 3
    return res
}
```

**What did you expect to see?**
A compilation success.
 
**What did you see instead?**
```
:! v run main.v
==================
/tmp/v/main.10192767264516768613.tmp.c:9242: error: character array initializer must be a
 literal, optionally enclosed in braces
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please raise an issue on
GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by spaceface777** [comment] 2021-04-01 05:48
Duplicate of #6051.

**Closed by spaceface777** 2021-04-01 05:48 UTC
Labels: Bug
