### ISSUE TITLE
json: skip fields if no value is explicitly set.

### ISSUE THREAD

**Issue by ghost** [vlang/v#16447] opened 2022-11-16 11:54 UTC
skipping fields if that field is not set.
```v
import json

struct Foo{
    bar int
    baz int
}

fn main() {
    f := Foo{
        bar: 3
    }
    j := json.encode(f)
    assert j == '{"bar":3}'
}
```
not `'{"bar":3,"baz":0}'`

**Comment by enghitalo** [comment] 2022-11-16 12:43
It is, maybe, because all var is struct need be initialized. So, this look, just need a error if the field in struct is not initialized.

I am waiting for optional fields in structs. So, i guess that will be possible do this easer.

```v
import json 
struct Foo{ 
    bar int 
    baz ?int 
} 

fn main() { 
    f := Foo{ bar: 3 } 
    j := json.encode(f) 
    assert j == '{"bar":3}' }
```

**Comment by kahsa** [comment] 2022-11-17 03:10
Yes. I would like to see that built into cjson as the default behavior.

**Comment by JalonSolov** [comment] 2022-11-17 03:18
cjson is a 3rd-party product.  Perhaps create an issue there.

Otherwise, hopefully x.json2 will be improved enough to replace it, then we could worry about what it does.

**Comment by kahsa** [comment] 2022-11-17 03:53
I don't mind either way, as long as it can be converted in one shot, like json.encode()/decode() can do now.

**Comment by kahsa** [comment] 2022-11-17 03:58
My point is that it can be used immediately and easily, without the need to do any implementation of your own.
Please guess and understand my intention.

**Comment by kahsa** [comment] 2022-11-17 04:05
And is json2 still maintained? It seems to have stopped being on the way for a long time now.
A project abandoned halfway through cannot be used for a business project.

**Comment by kahsa** [comment] 2022-11-17 04:13
@JalonSolov  I always thought you lacked any user perspective at all.
You are the type of engineer I hate. They always say it's impossible, it's too hard, etc., and then bring the business to a standstill.

**Comment by kahsa** [comment] 2022-11-17 04:17
Development of json2 has been halted for months in the middle of the project.
When in the world will it resume?
When in the world will the optional fields be incorporated?
How many more months do we have to wait?

**Comment by JalonSolov** [comment] 2022-11-17 12:57
I never said anything was impossible.  I said it wasn't our project.  I don't see any reason for us to create a fork of cJSON to give you this one feature, when improving x.json2 is a better option for V.

As for your questions about x.json2, you'll have to ask @nedpals - I'm sure he'll drop everything else he's working on to get this done just for you.  Especially since nobody else seems to want to contribute anything other than criticism.

**Comment by kahsa** [comment] 2022-11-17 13:01
@JalonSolov  You still don't understand my point. LOL.
You really are incapable of grasping people's intentions.
Stay out of my posts already. It's irritating.

**Comment by nedpals** [comment] 2022-11-17 13:12
i have awakened from the irl-world just to (nitpicking-ly, if a term like that exists) answer your questions

> Development of json2 has been halted for months in the middle of the project.
> When in the world will it resume?

json2 was never meant as a module to be maintained solely by one person (aka me). it's development is always active as long as there are people who would have the guts to hack it

> When in the world will the optional fields be incorporated?

idk ask the core maintainers about it. json2 only relies on features without the need for using "magical hacks" in the compiler. once optional fields are fully supported along with proper metaprogramming features that supports this, then most likely they will be implemented immediately (again, either by me or by someone else who is eager to do it)

**Comment by kahsa** [comment] 2022-11-17 13:13
Who brought up json2?

Was it me?

It was you, wasn't it?

I'm not going to demand that a stopped project be completed as soon as possible, so you expected cjson to be the one that is currently functioning.

To which you, in turn, brought up json2, didn't you? No?　@JalonSolov

**Comment by spytheman** [comment] 2022-11-17 13:19
> When in the world will the optional fields be incorporated?


@kahsa, they are merged for *several hours* now. From my perspective, you are being ridiculously demanding here. Optional fields have to work (which is now more or less done, thanks to @shove70 mostly), and the bugs in them ironed out, before they can be supported in modules like `json2`.

**Comment by spytheman** [comment] 2022-11-17 13:22
> You guys are laughably missing my point.

Which is?

Can you please state *exactly* what is your point, and why are you attacking others in the issues? I am not a mind reader.

**Comment by spytheman** [comment] 2022-11-17 13:23
Please note, that I am all for laughing at myself, as long as I can understand why should I do so?

**Comment by kahsa** [comment] 2022-11-17 13:24
I simply said I would be happy if `json.encode()/decode()`, which is easier to encode/decode, could use the option field to achieve the above behavior.

Why are you guys making that simple story so complicated?

**Comment by spytheman** [comment] 2022-11-17 13:25
Who said that it is wrong?

**Comment by kahsa** [comment] 2022-11-17 13:25
Did I make any demands of ned?

**Comment by spytheman** [comment] 2022-11-17 13:26
> I simply said I would be happy if json.encode()/decode(), which is easier to encode/decode, could use the option field to achieve the above behavior.

That is very reasonable, and given that optional fields now do work more or less, it will be done.

**Comment by kahsa** [comment] 2022-11-17 13:27
Yes, it will be done. I hope it. That is this story. That's all.
I don't talk about json2 at all.

**Comment by ArtemkaKun** [comment] 2022-11-17 13:28
Look @kahsa, the problem is that you required things to make your code work in the right way. But think about this on the other hand - nobody cares about your program besides you.

That's open-source, people work here in their spare time to achieve things they care about (in most cases). Why should, for example, I as a developer, fix this bug for you? If I have the same problem or like you - I would do that for you (or any other person here since we are all developers here). I neither care about this JSON problem nor like you so much to help you with this problem (especially now when you make drama here).

So chill and think. You created an issue on GitHub - thank you for that. Now you can either:
- fix it by yourself
- wait until another developer will fix it

If you want to make V a better programming language - just do that by making contributions. If you are hating others for "why you can't do that simple thing?" - you just make people dislike you, that's all 🤷‍♂️

**Comment by kahsa** [comment] 2022-11-17 13:32
@ArtemkaKun  Are you here to rehash the same story as JalonSolov ?

**Comment by ArtemkaKun** [comment] 2022-11-17 13:33
> Ah, here comes the "open source" person again, but I don't need to be told that.

😂 you are funny. I just want to say that what are you doing now - will not help you with this issue. You probably should choose another strategy.

**Comment by spytheman** [comment] 2022-11-17 13:33
https://www.youtube.com/watch?v=1sONfxPCTU0

As a wise person once said, "Can We All Just Get Along? For The Kids & Old People?"

**Comment by kahsa** [comment] 2022-11-17 13:35
Anyway, the conversation always takes a weird turn when JalonSolov  comes in.
He doesn't have to comment on my posts.

**Comment by spytheman** [comment] 2022-11-17 13:38
> Anyway, the conversation always takes a weird turn when JalonSolov comes in. He doesn't have to comment on my posts.

I beg to differ. In my experience, JalonSolov is not the one to seek drama, while you do @kahsa . I can link to specific instances if you want ? Anyway, we all have our strong and weak sides, we are all human after all.

**Comment by kahsa** [comment] 2022-11-17 13:40
I am not a wise man like you two, and I think it is a waste of time to preach to you.

**Comment by enghitalo** [comment] 2022-11-17 22:32
> I simply said I would be happy if `json.encode()/decode()`, which is easier to encode/decode, could use the option field to achieve the above behavior.
> 
> Why are you guys making that simple story so complicated?
> 

I see at least 3 people on json2 today.  I believe that request is close to be implemented. After the optional field for struct, and after all work of @nedpals everything can be easer now.

I will try implement this next week.

**Comment by kahsa** [comment] 2022-11-18 00:27
Thanks @enghitalo 
For those who need to interact with the API server, the ease of handling json object is a crucial issue.
I understand the convenience of the V developers, but I believe that the silent majority of people are checking like that  very seriously.

**Comment by medvednikov** [comment] 2022-11-19 11:17
@kahsa such personal attacks are not tolerated. I've blocked you for one month.

**Comment by ylluminate** [comment] 2022-11-19 20:19
@kahsa please contextually remember this - no one, it does not appear - has intentionally attacked you. I realize that language and cultural barriers are sometimes difficult to maneuver and it's possible that this is one such case given your tone and framing. 

Please see this, as it's intended, as an opportunity to facilitate a cooldown of the clearly unnecessarily escalated situation. Hopefully you interpret it as such and do not feel overwhelmed and overly angry.


Please remember the singular rule for the V community: "Be nice." I do not personally think @JalonSolov tried to violate this from his remarks, etc.

**Comment by felipensp** [comment] 2023-04-10 19:25
This is as option fields works with json currently.

**Closed by felipensp** 2023-04-10 19:25 UTC
Labels: Feature Request, Unit: cgen, Option Fields
