### ISSUE TITLE
There are two different module resolution for same code.

### ISSUE THREAD

**Issue by zakuro9715** [vlang/v#19402] opened 2023-09-21 11:11 UTC
### Describe the bug

When compiling the same code, module resolution changes depending on whether absolute or relative paths are specified.

### Reproduction Steps

files:
```
cmd/foo/main/main.v
cmd/foo/foo.v
foo/foo.v
v.mod
```

cmd/foo/main.v:
```v
module main
import foo

fn main() {
 println(foo.name)
}
```

cmd/foo/foo.v:
```v
module foo

pub const name = '/cmd/foo'
```

foo/foo.v:
```v
module foo

pub const name = '/foo'
```

---

```sh
$ v run cmd/foo/main/main.v
/foo
$ v run $(pwd)/cmd/foo/main/main.v
/cmd/foo
```

### Expected Behavior

Always resolve to `foo`, not `cmd.foo`.

### Current Behavior

There are two different module resolution

### Possible Solution

This problem is caused by qualify_import.

`v run cmd/foo/main/main.v` -> `import res 3`
```
>  qualify_import: foo                | file_path: cmd/foo/main/main.v                                                     | =>   import_res 3: foo                ; ---, mod_path: foo
```

`v run $(pwd)/cmd/foo/main/main.v` -> `import res 2`
```
>  qualify_import: foo                | file_path: /home/zakuro/src/github.com/zakuro9715/v/same_name_mod/cmd/foo/main/main.v | =>   import_res 2: cmd.foo            ; /home/zakuro/src/github.com/zakuro9715/v/same_name_mod/cmd/foo/main/main.v
```

### Additional Information/Context

This is the cause of #18993 #11348

### V version

V 0.4.1 4f7dbbf

### Environment details (OS name and version, etc.)

```
OS: linux, Ubuntu 22.04.1 LTS (WSL 2)
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 3800X 8-Core Processor

getwd: /home/zakuro/src/github.com/zakuro9715/v
vexe: /home/zakuro/src/github.com/zakuro9715/v/v
vexe mtime: 2023-09-21 10:56:34

vroot: OK, value: /home/zakuro/src/github.com/zakuro9715/v
VMODULES: OK, value: /home/zakuro/.vmodules
VTMP: OK, value: /tmp/v_1000

env VFLAGS: "-cc clang"

Git version: git version 2.34.1
Git vroot status: weekly.2023.35-139-g4f7dbbfa
.git/config present: true

CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!IMPORTANT]
> You can vote for this issue using the 👍 reaction. More votes increase the issue's priority
> for developers.
>
> Take into account that only the 👍 reaction counts as a vote.
> Only reactions to the issue itself will be counted as votes, not comments.

**Comment by ttytm** [comment] 2024-03-10 06:06
Closing as I cannot reproduce this anymore.

Please reach out if you still encounter a problem like this, then we can reopen or work on it in a separate issue.

**Closed by ttytm** 2024-03-10 06:06 UTC
Labels: Bug, Module Lookup Problem
