### ISSUE TITLE
JavaScript like Arrow function

### ISSUE THREAD

**Issue by lithic** [vlang/v#1757] opened 2019-08-27 06:49 UTC

**Comment by Delta456** [comment] 2019-08-27 08:58
Can you give us an example?

**Comment by lithic** [comment] 2019-08-27 10:58
Like how we use them in JavaScript

**Comment by medvednikov** [comment] 2019-08-27 11:43
Yes, this is a duplicate of https://github.com/vlang/v/issues/1066

**Closed by medvednikov** 2019-08-27 11:43 UTC
Labels: feature request
