### ISSUE TITLE
Ternary expression cannot use nested Ifs

### ISSUE THREAD

**Issue by csfore** [vlang/v#17171] opened 2023-01-31 03:41 UTC
### Describe the bug

The ternary expression cannot currently use nested if statements.

### Expected Behavior

The value of the nested `if` statement to be set to the variable.

### Current Behavior

```
error: `if` expression requires an expression as the last statement of every branch
    7 |         if true {
    8 |             1
    9 |         } else {
      |           ~~~~
   10 |             eprintln('Error')
   11 |             return
```

### Reproduction Steps

```
var := if true  {
	0
} else {
	if true {
		1
	} else {
		0
	}
}
```

### V version

V 0.3.3 6b20c57.2d51379

### Environment details (OS name and version, etc.)

```
OS: linux, "Arch Linux"
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 9 5900HX with Radeon Graphics
CC version: cc (GCC) 12.2.1 20230111

getwd: /home/user/Workspaces/V/bug-testing
vmodules: /home/user/.vmodules
vroot: /home/user/v
vexe: /home/user/v/v
vexe mtime: 2023-01-30 21:57:54
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 6b20c57.2d51379

Git version: git version 2.39.1
Git vroot status: 0.3.3-3-g2d51379f
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

**Comment by DevrosTheOne** [comment] 2023-01-31 04:13
No problem on M1 Mac
```
OS: macos, macOS, 13.2, 22D49
CC version: Apple clang version 14.0.0

V full version: V 0.3.3 6b20c57.2d51379
```

**Comment by danieldaeschle** [comment] 2023-01-31 10:11
Your reproduction step has not the same content as the error

**Comment by DevrosTheOne** [comment] 2023-01-31 10:49
Sorry, I skimmed and missed the link between the steps and the error trigger.  
Same output on M1.

**Comment by DevrosTheOne** [comment] 2023-01-31 10:52
> Your reproduction step has not the same content as the error

Sorry, I skimmed the code and missed the intent of the post.

**Comment by danieldaeschle** [comment] 2023-01-31 14:16
I meant @csfore

**Comment by JalonSolov** [comment] 2023-01-31 14:47
Right.  The code in the `Reproduction Steps` section will not produce the error shown.

**Comment by JalonSolov** [comment] 2023-02-01 01:31
It does for me.

**Comment by JalonSolov** [comment] 2023-02-01 01:32
I also think this _should_ work.  Similar thing was fixed in `match` recently... basically the same issue.

**Comment by csfore** [comment] 2023-02-01 15:06
It seems like it shouldn't work, because it's trying to assign nothing to a variable essentially but the error message seems like it's erroring for the wrong reason. The variable doesn't technically exist yet though so I'm not sure what it should do.

**Comment by JalonSolov** [comment] 2023-02-01 16:22
It should work because it is short-circuiting the program flow such that `var` doesn't _need_ to be defined - it is exiting that code flow and returning to the caller.

**Comment by csfore** [comment] 2023-02-01 17:44
Ah, alright. Should I rename the issue to something more appropriate then? As nested If statements do technically work. It's just the short-circuiting that doesn't work.

**Comment by JalonSolov** [comment] 2023-02-01 20:49
:man_shrugging:

**Comment by Delta456** [comment] 2024-06-28 18:56
I will be closing the issue because the program compiles successfully for me.

Feel free to open it again if the problem still exists.

**Closed by Delta456** 2024-06-28 18:56 UTC
Labels: Bug, Status: Confirmed
