### ISSUE TITLE
Sequential bitwise operations fail without parens

### ISSUE THREAD

**Issue by watzon** [vlang/v#3485] opened 2020-01-18 00:49 UTC
**V version:** Master
**OS:** Linux

**What did you do?**
```v
p := [1, 2, 3, 4]
v := u32(p[3]) | u32(p[2]) << 8 | u32(p[1]) << 16 | u32(p[1]) << 24
```

**What did you expect to see?**
33686276
 
**What did you see instead?**
```
syntax error: unexpected `<<`, expecting `)`
   45|          return u32(0), false
   46|  }
   47|  return u32(p[3]) | u32(p[2]) << 8 | u32(p[1]) << 16 | u32(p[1]) << 24
                                           ^
   48| }
   49|
```

**Comment by watzon** [comment] 2020-01-18 00:50
It does work if you put parens around  the left shift operations, but that shouldn't be needed

**Comment by alexesprit** [comment] 2020-04-12 09:14
This example is compilable now, though it returns a wrong result.

A bitwise OR operator has a higher priority over a left shift operator. That's why it doesn't work properly.

**Comment by alexesprit** [comment] 2020-04-16 17:42
Precendence of a left-shift operator was fixed in b33a9fc9, but the the issue is still not resolved. Now the example returns a wrong result because of a first cast to `u32`:
```v
fn main() {
	p := [1, 2, 3, 4]
	v1 := u32(p[3]) | u32(p[2]) << 8 | u32(p[1]) << 16 | u32(p[1]) << 24
	v2 := p[3] | u32(p[2]) << 8 | u32(p[1]) << 16 | u32(p[1]) << 24
	// The result should be 33686276
	println(v1)
	println(v2)
}
```
```
$ vrun test4.v
772
33686276
```

**Comment by orneo1212** [comment] 2020-09-21 07:25
Tested on:
V 0.1.29 bc0b637

```v
p := [1, 2, 3, 4]
v := u32(p[3]) | u32(p[2]) << 8 | u32(p[1]) << 16 | u32(p[1]) << 24
println(v)
```

`v run` give correct result:
```
33686276
```

I think issue can be closed.

**Comment by Delta456** [comment] 2020-09-21 08:16
Yes, this can be closed. Thanks @orneo1212

**Closed by Delta456** 2020-09-21 08:16 UTC
Labels: Bug, Status: Confirmed, Unit: Compiler
