### ISSUE TITLE
V Playground JSON does not compile

### ISSUE THREAD

**Issue by TheTechRobo** [vlang/v#4757] opened 2020-05-06 16:25 UTC
**V version:** Playground
**OS:** macOS

**What did you do?**
Chose the JSON encoder/decoder and pressed Run.

**What did you expect to see?**
Not sure.
 
**What did you see instead?**
>You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by nedpals** [comment] 2020-05-07 03:59
Closed. Duplicate of #4273

**Closed by nedpals** 2020-05-07 03:59 UTC
Labels: Bug
