### ISSUE TITLE
Unknown error in https://vlang.io/play "JSON decoding/encoding"

### ISSUE THREAD

**Issue by andreabravetti** [vlang/v#4892] opened 2020-05-14 07:49 UTC
**What did you do?**
Run "JSON decoding/encoding" in https://vlang.io/play 

**What did you expect to see?**
A result
 
**What did you see instead?**
It print "You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."

It may be related to #4779.

**Comment by dhonx** [comment] 2020-05-14 12:40
Thanks for reporting @andreabravetti... If you want to play around with V, I recommend using https://devbits.app/play for now

**Comment by JalonSolov** [comment] 2020-05-15 01:29
Looks like the only issue is the playground is calling an "old" version of v to run the code.

The json example is (almost... a space here or there...) identical to examples/json.v, which runs fine with the current version of v.

**Comment by medvednikov** [comment] 2020-05-15 02:21
I've updated it to the latest V.

The problem is with the sandbox, it doesn't have permissions to build cJSON.o

**Comment by JalonSolov** [comment] 2020-05-15 02:32
Doh.  Can you put one in place for it to use, or does it need to rebuild it often/every time?

**Comment by medvednikov** [comment] 2020-05-15 02:49
Only once. I'm just at sysadmin stuff and linux accounts. Will figure it out.

**Comment by leahlundqvist** [comment] 2020-12-01 10:43
Closing this as the old playground has been retired.

**Closed by leahlundqvist** 2020-12-01 10:43 UTC
Labels: Bug, OS: Playground, Status: Duplicate
