### ISSUE TITLE
vlang's official website playground Json decoding/encoding has error

### ISSUE THREAD

**Issue by xland** [vlang/v#4717] opened 2020-05-04 23:38 UTC
**V version: don't know
**OS: don't know

**What did you do?**
Click  official website playground Json decoding/encoding button,then click run button.
[https://vlang.io/play](url)

**What did you expect to see?**
Json decoding/encoding code excute correctly.
 
**What did you see instead?**

> You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by xland** [comment] 2020-05-04 23:46
https://github.com/vlang/website/issues/136

**Comment by nedpals** [comment] 2020-05-04 23:49
@xland Playground, in total, is broken right now. Try https://devbits.app/play instead.

**Comment by xland** [comment] 2020-05-05 00:27
@nedpals 

devbits.app playground has error too.(same code)
```
main.v:12:28: warning: use `x := []Type{}` instead of `x := []Type` 
   10 | fn main() {
   11 |     s := '[{ "name":"Frodo", "age":25}, {"name":"Bobby", "age":10}]'
   12 |     mut users := json.decode( []User, s) or {
      |                               ^
   13 |         eprintln('Failed to parse json')
   14 |         return
main.v:11:2: warning: unused variable: `s` 
    9 | 
   10 | fn main() {
   11 |     s := '[{ "name":"Frodo", "age":25}, {"name":"Bobby", "age":10}]'
      |     ^
   12 |     mut users := json.decode( []User, s) or {
   13 |         eprintln('Failed to parse json')
main.v:12:20: error: json.decode: first argument needs to be a type 
   10 | fn main() {
   11 |     s := '[{ "name":"Frodo", "age":25}, {"name":"Bobby", "age":10}]'
   12 |     mut users := json.decode( []User, s) or {
      |                       ~~~~~~~~~~~~~~~~~~
   13 |         eprintln('Failed to parse json')
   14 |         return
main.v:16:14: error: for in: cannot index `void` 
   14 |         return 
   15 |     }
   16 |     for user in users {
      |                 ~~~~~
   17 |         println('$user.name: $user.age')
   18 |     }
main.v:17:18: error: unknown selector expression 
   15 |     }
   16 |     for user in users {
   17 |         println('$user.name: $user.age')
      |                        ~~~~
   18 |     }
   19 |     println('')
main.v:20:17: error: for in: cannot index `void` 
   18 |     }
   19 |     println('')
   20 |     for i, user in users {
      |                    ~~~~~
   21 |         println('$i) $user.name')
   22 |         if !user.can_register() {
main.v:21:22: error: unknown selector expression 
   19 |     println('')
   20 |     for i, user in users {
   21 |         println('$i) $user.name')
      |                            ~~~~
   22 |         if !user.can_register() {
   23 |             println('Cannot register $user.name, they are too young')
main.v:22:12: error: unknown method: `void.can_register` 
   20 |     for i, user in users {
   21 |         println('$i) $user.name')
   22 |         if !user.can_register() {
      |                  ~~~~~~~~~~~~~~~
   23 |             println('Cannot register $user.name, they are too young')
   24 |             continue
main.v:23:35: error: unknown selector expression 
   21 |         println('$i) $user.name')
   22 |         if !user.can_register() {
   23 |             println('Cannot register $user.name, they are too young')
      |                                            ~~~~
   24 |             continue 
   25 |         }
main.v:26:12: error: unknown method: `void.register` 
   24 |             continue 
   25 |         }
   26 |         users[i].register() // `user` is immutable, we have to modify the array 
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   27 |     }
   28 |     // Let's encode users again just for fun
```

**Comment by lutherwenxu** [comment] 2020-05-05 02:19
Duplicate of #4273.

**Closed by lutherwenxu** 2020-05-05 02:19 UTC
Labels: Bug, OS: Playground
