### ISSUE TITLE
V up doesn't work

### ISSUE THREAD

**Issue by bogdanbankov** [vlang/v#7475] opened 2020-12-22 20:28 UTC
**V version:** V 0.1.30 43ff93c
**OS:** Windows 10 Pro 2004 19041.685

**What did you do?**
`v up`

**What did you expect to see?**
It updates
 
**What did you see instead?**
```
cannot compile `C:\v\cmd\tools\vup.v:
recompilation with tcc failed; retrying with cc ...
==================
C:\Users\bogda\AppData\Local\Temp\v\vup.1999995506607316109.tmp.c: In function 'string_trim':
C:\Users\bogda\AppData\Local\Temp\v\vup.1999995506607316109.tmp.c:410:28: error: implicit declaration of function 'array_byte_contains'; did you mean 'array_rune_contains'? [-Werror=implicit-function-declaration]
 #define _IN(typ, val, arr) array_##typ##_contains(arr, val)
                            ^~~~~~
C:\Users\bogda\AppData\Local\Temp\v\vup.1999995506607316109.tmp.c:9311:7: note: in expansion of macro '_IN'
   if (_IN(byte, string_at(s, pos_left), cs_arr)) {
       ^~~
C:\Users\bogda\AppData\Local\Temp\v\vup.1999995506607316109.tmp.c: In function 'os__args_after':
C:\Users\bogda\AppData\Local\Temp\v\vup.1999995506607316109.tmp.c:410:28: error: implicit declaration of function 'array_string_contains'; did you mean 'array_rune_contains'? [-Werror=implicit-function-declaration]
 #define _IN(typ, val, arr) array_##typ##_contains(arr, val)
                            ^~~~~~
C:\Users\bogda\AppData\Local\Temp\v\vup.1999995506607316109.tmp.c:10078:7: note: in expansion of macro '_IN'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang`
```
```

**Comment by spaceface777** [comment] 2020-12-22 20:32
duplicate of #7468

**Closed by spaceface777** 2020-12-22 20:32 UTC
Labels: Bug
