### ISSUE TITLE
'${nums.map(it + 1)}' leads to C error

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#3680] opened 2020-02-08 01:27 UTC
**V version:** `V 0.1.25 ea9961a`
**OS:** 64-bit Debian GNU/Linux 9.11 (stretch)

**What did you do?**

```v
const (
	nums = [[4, 7], [3], [2]]
)

fn main() {
	for num in nums {
		// n := num.map(it + 1)
		// println('Hello, ${n} developers!')
		println('Hello, ${num.map(it + 1)} developers!')
	}
}
```

**What did you expect to see?**

```
Hello, [5, 8]  developers!
Hello, [4]  developers!
Hello, [3]  developers!
```

...which _is_ what I see when I comment out the problematic line and uncomment the 2 equivalent lines (see code, above).
 
**What did you see instead?**

```
==================
expected expression before ‘array’
  string tmp5 = array_int_str(array tmp3 = new_array(0, num .len, sizeof(int));
                              ^~~~~
==================
...
(Use `v -cg` to print the entire error message)

V error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

**Comment by alexesprit** [comment] 2020-02-08 05:24
Duplicate of #2621.

Also, see the explanation of this issue: https://github.com/vlang/v/issues/2953#issuecomment-560347629

**Closed by alexesprit** 2020-02-08 05:24 UTC
Labels: Type: Bug
