### ISSUE TITLE
Error compiling code copied from V's documentation

### ISSUE THREAD

**Issue by dsogari** [vlang/v#13322] opened 2022-01-29 20:43 UTC
**V doctor:**
```
OS: windows, Microsoft Windows 10 Pro v19044 64-bit
Processor: 8 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.

 cmd: cc --version

getwd: D:\v-sample
vmodules: C:\Users\diego\.vmodules
vroot: C:\tools\v
vexe: C:\tools\v\v.exe
vexe mtime: 2022-01-24 12:56:54
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 216a505

Git version: git version 2.34.1.windows.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc: N/A
```

**What did you do?**
`v run .\hello.v`
```v
struct Abc {
	val string
}

struct Xyz {
	foo string
}

type Alphabet = Abc | Xyz

x := Alphabet(Abc{'test'}) // sum type
if x is Abc {
	// x is automatically casted to Abc and can be used here
	println(x)
}
if x !is Abc {
	println('Not Abc')
}
```
Copied from [here](https://github.com/vlang/v/blob/master/doc/docs.md#type-checks-and-casts).

**What did you expect to see?**

```
Abc{
    val: 'test'
}
```

**What did you see instead?**
```
==================
C:/Users/diego/AppData/Local/Temp/v_0/hello.735286170275474811.tmp.c:6723: warning: cast between pointer and integer of different size
C:/Users/diego/AppData/Local/Temp/v_0/hello.735286170275474811.tmp.c:11274: error: cannot convert 'struct main__Abc' to 'struct main__Alphabet'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang```

**Comment by vincenzopalazzo** [comment] 2022-02-03 16:36
This is fixed by the https://github.com/vlang/v/pull/13332 @spytheman ?

**Comment by vincenzopalazzo** [comment] 2022-02-04 00:07
I reproduced the problem, I think the problem is the incapsulation of the c function

```
➜  v git:(master) ✗ ./v self && ./v -cg -cc gcc debug/hello.v
V self compiling ...
V built successfully as executable "v".
/tmp/v_1000/hello.11689309235014473967.tmp.c: In function ‘main__main’:
/tmp/v_1000/hello.11689309235014473967.tmp.c:11150:31: error: incompatible type for argument 1 of ‘main__Alphabet_str’
11150 |   println(main__Alphabet_str((*x._main__Abc)));
      |                              ~^~~~~~~~~~~~~~
      |                               |
      |                               main__Abc {aka struct main__Abc}
/tmp/v_1000/hello.11689309235014473967.tmp.c:1901:49: note: expected ‘main__Alphabet’ {aka ‘struct main__Alphabet’} but argument is of type ‘main__Abc’ {aka ‘struct main__Abc’}
 1901 | static string main__Alphabet_str(main__Alphabet x) { return indent_main__Alphabet_str(x, 0); }
      |                                  ~~~~~~~~~~~~~~~^
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

I would like to drive into this fix

**Comment by dsogari** [comment] 2022-02-08 01:48
Hi everyone! Just a quick question. Should this code compile, even if the `Error` type is not defined?
```v
Error{}.msg
```

**Comment by medvednikov** [comment] 2022-07-11 08:05
Fixed.

`Error` is a builtin type.

**Closed by medvednikov** 2022-07-11 08:05 UTC
Labels: Bug, Status: Confirmed, check-md
