### ISSUE TITLE
Undocumented change in split behavior

### ISSUE THREAD

**Issue by MeWhenI** [vlang/v#21938] opened 2024-07-26 19:18 UTC
### Describe the bug

Between 0.4.6 and 0.4.7, the behavior of `string.split` changed, specifically when splitting on a multi-character delimiter where the source string has two instances of the delimiter right beside eachother.

### Reproduction Steps

Code: https://play.vlang.io/p/9c7af8ea27

```v
println("abcbca".split("bc"))
```

### Expected Behavior

Expected output to match output in 0.4.6: 

```
['a', '', 'a']
```

### Current Behavior

Actual output:

```
['a', 'bca']
```

### Additional Information/Context

A user on Discord indicated this change was introduced in PR #21563.

Also, this bug does not occur with a single-character delimiter. The code
```v
println("abba".split("b"))
```
works as expected, producing
```
['a', '', 'a']
```

### V version

V 0.4.7 52fe7c0

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.7 52fe7c0
OS: linux, Debian GNU/Linux 11 (bullseye) (VM)
Processor: 1 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz

getwd: /home/admin/playground
vexe: /home/admin/v/v
vexe mtime: 2024-07-26 18:25:25

vroot: OK, value: /home/admin/v
VMODULES: OK, value: .vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.30.2
Git vroot status: Error: fatal: detected dubious ownership in repository at '/home/admin/v'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v
.git/config present: true

CC version: cc (Debian 10.2.1-6) 10.2.1 20210110
thirdparty/tcc status: Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc
 Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc

```

**Comment by Delta456** [comment] 2024-07-26 19:23
Closing as duplicate of https://github.com/vlang/v/issues/21936

**Closed by Delta456** 2024-07-26 19:23 UTC
Labels: Bug
