### ISSUE TITLE
C error when leaving off the parentheses on calling a generic function.

### ISSUE THREAD

**Issue by bbodi** [vlang/v#18469] opened 2023-06-16 16:00 UTC
### Describe the bug

```v
struct Arr[T] {
mut:
    data []T
}

fn new_arr[T]() Arr[T] {
    return Arr[T] { }
}

fn main() {
    arr := new_arr[int] // I forgot the ()
    println('Hello')
}
```

### Expected Behavior

Some user friendly error message

### Current Behavior

```
$ v -g run bug.v
bug.v:11:5: warning: unused variable: `arr`
    9 | 
   10 | fn main() {
   11 |     arr := new_arr[int] // I forgot the ()
      |     ~~~
   12 |     println('Hello')
   13 | }
/tmp/v_1000/bug.17236921576658051164.tmp.c:932: error: identifier expected
builder error: 
==================
...
$
```

### Reproduction Steps

Code attached above

### V version

0.3.4 ac32d2a

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 ac32d2a

vexe mtime: 2023-06-16 15:40:56

CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by JalonSolov** [comment] 2023-06-16 16:53
It's always better to give an actually summary in the issue title, as well as a more complete error message.  Gives people more of an idea of where to start looking.

**Comment by Delta456** [comment] 2023-06-16 17:10
Even more minimal reproduction:

```v
fn new_arr() []int {
    return [2 ,3]
}

fn main() {
    arr := new_arr
}
```

**Comment by Delta456** [comment] 2023-06-16 17:24
I think it should work because you are taking the functionality of that function.

**Comment by JalonSolov** [comment] 2023-06-16 17:54
He's trying to call the function to create an array.

**Comment by tobealive** [comment] 2023-06-16 18:20
It's not possible to assign a generic function to a variable. So if a generic function is not called for it's results to get assigned to the variable a proper error is the way to go i guess.

**Comment by tobealive** [comment] 2023-06-16 19:44
Just discovered we have tests for such genric function value assignments with type specifications without calling the function. I thought having read an error message in the checker and that's it's not possible.

https://github.com/vlang/v/blob/master/vlib/v/tests/generics_fn_variable_1_test.v

Need to dig a bit deeper for what's the issue here.

**Closed** 2023-06-18 19:22 UTC
Labels: Bug
