### ISSUE TITLE
net.http hangs 

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#16491] opened 2022-11-20 11:23 UTC
### Describe the bug

Running on MacOS Monterey 12.6, code sample below randomly hangs

```vlang
import net.http
import time

fn main() {
	start := time.ticks()
	res := http.get('https://www.google.com') or { panic('oops') }
	end := time.ticks()
	println('body length:${res.body.len} status:${res.status_code}/${res.status_msg} ticks elapsed:${end - start} ')
}
```
Output:
```
ticks elapsed:124 tatus:200/OK
```

Also note the string interpolation returns the wrong result when the http.get does run successful.

Example runs:
```
time v run netw.v
 ticks elapsed:113 tatus:200/OK
v run netw.v  1.08s user 0.33s system 85% cpu 1.650 total

time v run netw.v
 ticks elapsed:115 tatus:200/OK
v run netw.v  1.06s user 0.32s system 82% cpu 1.674 total

 time v run netw.v
 ticks elapsed:168 tatus:200/OK
v run netw.v  1.09s user 0.33s system 83% cpu 1.697 total

**time v run netw.v
^Cv run netw.v  1.09s user 0.34s system 5% cpu 25.640 total**
```
last run was Ctrl-C'ed as it hung 

### Expected Behavior

Not hanging.

Returning correct string interpolation:
body length:14642 status:200/OK ticks elapsed:107

instead of:
ticks elapsed:124 tatus:200/OK

### Current Behavior

see bug description

### Reproduction Steps

running the code sample on macos (?)

### V version

V 0.3.2 4585488

### Environment details (OS name and version, etc.)

OS: macos, macOS, 12.6, 21G115 Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz CC version: Apple clang version 14.0.0 (clang-1400.0.29.201)

**Comment by JalonSolov** [comment] 2022-11-20 12:55
Looks like you may have been running into a network timeout.  V sets the default timeout to 30 seconds, I believe.

Try again, and let it run longer if it gets "stuck".

**Comment by spytheman** [comment] 2022-11-20 13:54
> Also note the string interpolation returns the wrong result when the http.get does run successful.

`println('body length: ${res.body.len}\nstatus_code: ${res.status_code}\nstatus_msg: ${res.status_msg.hex()}\nticks elapsed: ${end - start}')`

... reveals that the status_msg field contains `OK\r` (OK followed by 0x0D -> Carriage Return, which makes the next text overwrite the current text on the same line)

**Comment by JalonSolov** [comment] 2022-11-20 14:14
Ah, good catch.  Yes, _any_ input you get should be trimmed first.  I'd change that piece to `${res.status_msg.trim().bytes().hex()}`

**Comment by spytheman** [comment] 2022-11-20 14:23
the ending \r is fixed in cb336c7

**Comment by spytheman** [comment] 2022-11-20 14:28
I am still not sure why the timeout happens; on Linux I get this:
```
#0 16:27:28 ᛋ master /v/vnew❱while true; do v crun s.v ; done
body length:18589 status:200/OK ticks elapsed:421 
body length:18556 status:200/OK ticks elapsed:385 
body length:18579 status:200/OK ticks elapsed:408 
body length:18620 status:200/OK ticks elapsed:389 
body length:18576 status:200/OK ticks elapsed:409 
body length:18575 status:200/OK ticks elapsed:412 
body length:18550 status:200/OK ticks elapsed:405 
body length:18582 status:200/OK ticks elapsed:396 
body length:18514 status:200/OK ticks elapsed:397 
body length:18582 status:200/OK ticks elapsed:384 
body length:18560 status:200/OK ticks elapsed:399 
body length:18584 status:200/OK ticks elapsed:394 
body length:18613 status:200/OK ticks elapsed:395 
body length:18546 status:200/OK ticks elapsed:405 
body length:18536 status:200/OK ticks elapsed:404 
body length:18614 status:200/OK ticks elapsed:395 
body length:18601 status:200/OK ticks elapsed:400 
body length:18591 status:200/OK ticks elapsed:399 
body length:18522 status:200/OK ticks elapsed:404 
body length:18563 status:200/OK ticks elapsed:386 
body length:18588 status:200/OK ticks elapsed:410 
```

**Comment by spytheman** [comment] 2022-11-20 14:32
It is a similar result on macos (same home network):
```
0[16:30:02]@m1: (master) ~/v $ while true; do v crun s.v; sleep 0.1; done
body length:18562 status:200/OK ticks elapsed:525
body length:18604 status:200/OK ticks elapsed:495
body length:18608 status:200/OK ticks elapsed:491
body length:18594 status:200/OK ticks elapsed:457
body length:18577 status:200/OK ticks elapsed:521
body length:18608 status:200/OK ticks elapsed:486
body length:18525 status:200/OK ticks elapsed:471
body length:18529 status:200/OK ticks elapsed:490
body length:18584 status:200/OK ticks elapsed:510
body length:18524 status:200/OK ticks elapsed:417
body length:18544 status:200/OK ticks elapsed:440
body length:18548 status:200/OK ticks elapsed:469
body length:18535 status:200/OK ticks elapsed:486
body length:18619 status:200/OK ticks elapsed:504
```

I'll leave the issue opened for a week, if someone can reproduce the timeout, but so far, I am inclined to think that it is a local network/DNS problem 🤔 .

**Comment by mvlootman** [comment] 2022-11-20 14:53
> Looks like you may have been running into a network timeout. V sets the default timeout to 30 seconds, I believe.
> 
> Try again, and let it run longer if it gets "stuck".

Ran it now longer:

time v run netw.v

^Cv run netw.v  1.07s user 0.33s system 1% cpu 1:24.80 total

Stopped after more than a 1 minute. Of course google.com does not take that long to complete the request.
Will try the same with curl as I don't think its a local /dns issue.

**Comment by mvlootman** [comment] 2022-11-20 15:05
Ran a `curl` and `v run` together, the `curl` ran without issue, while the `v run` hangs. 
https://user-images.githubusercontent.com/519064/202909598-5ad8cecd-0ed6-431c-b3d6-da54fd46738f.mp4

**Comment by mvlootman** [comment] 2022-11-20 15:11
> > Also note the string interpolation returns the wrong result when the http.get does run successful.
> 
> `println('body length: ${res.body.len}\nstatus_code: ${res.status_code}\nstatus_msg: ${res.status_msg.bytes().hex()}\nticks elapsed: ${end - start}')`
> 
> ... reveals that the status_msg field contains `OK\r` (OK followed by 0x0D -> Carriage Return, which makes the next text overwrite the current text on the same line)

Nice catch! Mocking the response with a custom struct did not show the interpolation string issue, which make sense now.

**Comment by mvlootman** [comment] 2022-11-20 20:36
> It is a similar result on macos (same home network):
> 
> ```
> 0[16:30:02]@m1: (master) ~/v $ while true; do v crun s.v; sleep 0.1; done
> body length:18562 status:200/OK ticks elapsed:525
> body length:18604 status:200/OK ticks elapsed:495
> body length:18608 status:200/OK ticks elapsed:491
> body length:18594 status:200/OK ticks elapsed:457
> body length:18577 status:200/OK ticks elapsed:521
> body length:18608 status:200/OK ticks elapsed:486
> body length:18525 status:200/OK ticks elapsed:471
> body length:18529 status:200/OK ticks elapsed:490
> body length:18584 status:200/OK ticks elapsed:510
> body length:18524 status:200/OK ticks elapsed:417
> body length:18544 status:200/OK ticks elapsed:440
> body length:18548 status:200/OK ticks elapsed:469
> body length:18535 status:200/OK ticks elapsed:486
> body length:18619 status:200/OK ticks elapsed:504
> ```
> 
> I'll leave the issue opened for a week, if someone can reproduce the timeout, but so far, I am also inclined to think that it is a local network/DNS problem 🤔 .

***

Replacing the call to a local webserver does not show this behavior.
Unclear why the calls to google.com sometimes fail (but not using cURL), but it seems not V related then.
Let's close the issue.

**Closed** 2022-11-20 20:47 UTC
Labels: Bug
