### ISSUE TITLE
Build module error

### ISSUE THREAD

**Issue by thanhngch** [vlang/v#3061] opened 2019-12-12 07:27 UTC
**V version:** V 0.1.23 28f76f1
**OS:** Ubuntu 18.04

**What did you do?**
Create a module  https://vlang.io/docs#modules
After run `v build module ~/code/modules/mymodule` 

**What did you see?**
this show an error
```
Building module "mymodule" (dir="/home/thanh/code/modules/mymodule")...




Generating a V header file for module `/home/thanh/code/modules/mymodule`
/home/thanh/bin/v//home/thanh/code/modules/mymodule
Building /home/thanh/.vmodules//home/thanh/code/modules/mymodule.o...
/tmp/v/mymodule.tmp.c:552:1: error: expected expression before ‘array’
 array arr=
 ^~~~~
/tmp/v/mymodule.tmp.c:796:1: error: expected expression before ‘int’
 int j=
 ^~~
/tmp/v/mymodule.tmp.c:841:1:...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```
It generate file `mymodule.vh` with content 
```
// /home/thanh/code/modules/mymodule module header

module mymodule
```
But I import module `import mymodule`, it show an error: can't find `mymodule`

**What did you expect to see?**
No error on build module and import `mymodule` success.

**Comment by nedpals** [comment] 2019-12-12 21:21
You can just import the module without building it. When it comes to importing, you must store `mymodule.v` into a folder and that folder must be located at the same directory as the file that tries to import `mymodule`.

**Comment by zhylmzr** [comment] 2019-12-13 08:04
Now v seem doesn't lookup module from `~/.vmodules`, the `v build module` generates the obj file only.

**Comment by BrunoS3D** [comment] 2020-01-18 16:55
Upvote
I had the same problem.
Error when trying to import my module:

```console
src/interpolation.v:1:14: cannot import module "mymodule" (not found)
    1| import mymodule
                    ^
    2| 
    3| fn main() {
```

Console output when module build is finished:
```console
Building module "mymodule" (dir="/home/bruno/Área de Trabalho/mymodule")...

Generating a V header file for module `/home/bruno/Área de Trabalho/mymodule`
/home/bruno/code/v//home/bruno/Área de Trabalho/mymodule
Building /home/bruno/.vmodules//home/bruno/Área de Trabalho/mymodule.o...
```

Note: it seems to be an error when exporting the compiled module to its final directory.
The error seems to be here:
```console
/home/bruno/.vmodules//home/bruno/Área de Trabalho/mymodule.o
```

I believe that this type of error is very relevant since it makes it impossible for some developers to bring more functionality to the language. Please pay more attention to this problem, it would be very good to be able to count on your collaboration.

The community thanks.

**Comment by danieldaeschle** [comment] 2021-07-21 09:59
Could you test this with the newest version of V? The commands changed and also the behavior. I can't reproduce it. Otherwise I will close it.

**Closed** 2021-07-22 11:59 UTC
Labels: Bug
