### ISSUE TITLE
Compiler should detect and prevent nil pointers when accessing maps

### ISSUE THREAD

**Issue by elliotchance** [vlang/v#10837] opened 2021-07-16 21:13 UTC
**V doctor:**
```
OS: macos, macOS, 11.4, 20F71
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
CC version: Apple clang version 12.0.5 (clang-1205.0.22.11)

getwd: /Users/elliotc/Library/Mobile Documents/com~apple~CloudDocs/Development/github.com/elliotchance/reflect
vmodules: /Users/elliotc/.vmodules
vroot: /Users/elliotc/Downloads/v
vexe: /Users/elliotc/Downloads/v/v
vexe mtime: 2021-07-12 08:57:42
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 974737f.b5f1cf8

Git version: git version 2.32.0
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc status: thirdparty-macos-amd64 689c8a02-dirty
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg bug.v`
```v
struct Foo {
	bar string
}

fn main() {
	m := map[string]&Foo{}
	e := m['bar']
	println(e.bar)
}

```

**What did you expect to see?**

A compiler error saying there needs to be an `or{}` block to avoid a nil pointer.

**What did you see instead?**
```
Terminated by signal 11 (SIGSEGV)
```

**Comment by dumblob** [comment] 2021-07-19 11:11
I think this is not related to any `nil` pointers. It's just that so far *V* devs decided to make the `or { }` optional (I don't agree with this, but that's how things are if I'm not mistaken). So without me trying it I'd say the same error would pop up in any case (`println()` shouldn't be necessry):

```v
	m := map[string]int
	e := m['bar']
```
But note that it should be possible already now write it safely (it's just not enforced if I remember correctly what *V* devs said):
```v
	m := map[string]int
	e := m['bar'] or { println( 'wrong key!' )
```
Please try that as I might not be fully up to date with the latest *V* development.

**Comment by elliotchance** [comment] 2021-07-19 13:27
From the [V docs](https://github.com/vlang/v/blob/master/doc/docs.md#maps):

> If a key is not found, a zero value is returned by default:

This is reasonable because you can decide what an empty value means to your app - but it's safe. If the type is a pointer there must be an `or{}` clause.

**Comment by dumblob** [comment] 2021-07-19 14:31
I've tried it now. It has nothing to do with `nil`. It behaves for all types the same:

```v
fn main() {
	m := map[string]Foo{}  // no reference this time
	e := m['bar']
	println( 'hello' + e.bar )
}
```
yields:
```
master % 0$ ./main 
hello
master % 0$ echo $?
0
master % 0$
```
And now the thing I was suggesting to try:
```v
fn main() {
	m := map[string]Foo{}  // no reference here
	e := m['bar'] or {
		println( 'fail' )
		return
	}
	println( 'hello' + e.bar )
}
```
```
master % 0$ ./main 
fail
master % 0$ 
```

**Comment by dumblob** [comment] 2021-07-19 14:33
But of course, there has to be some generic enough solution to such problems (as I said above - this all stems from the fact that *V* devs decided to make `or { }` optional for `map` - and I myself also dislike it).

**Comment by elliotchance** [comment] 2021-07-19 14:45
> I've tried it now. It has nothing to do with nil. It behaves for all types the same:

In your example your code does not crash. I'm totally fine with empty values because they are safe, even if they are invalid for the program the compiler should prevent you from creating any code paths that could lead to a segfault (at least that's what I understand from the goals).

**Comment by dumblob** [comment] 2021-07-19 17:25
Oh, I wouldn't have thought you'd be fine with "empty" values. In that case you're right with being concerned only about `nil`.

I wonder though how *V* will want to solve this without introducing any inconsistency (I can't imagine "some maps being safe and some not").

**Comment by elliotchance** [comment] 2021-07-19 18:18
In the simplest case, the compiler can verify if the type is a pointer and enforce that an `or{}` condition is provided.

However, there's another nuanced case here. If the type contains _anything_ that can be dereferenced the same restriction needs to apply, for example:

```v
struct Foo {
  a int
  b &Bar
}

struct Bar {
  c f64
}

fn main() {
	foos := map[string]Foo{}
	foo := foos['baz']
	println(foo.b.c) // b causes nil dereference
}
```

Normally, V would enforce that `Foo.b` is given a value when `Foo` is initialized, but in this case the empty `Foo` exists in an illegal way also potentially leading to a segfault.

**Comment by dumblob** [comment] 2021-07-19 20:11
Don't worry about **how** the compiler can verify that - *V* has so much information that this is not a problem.

The problem is the **decision** on how to design it to not introduce any inconsistencies (as I said above I'm afraid there is no easy solution to the "some maps being safe by default and some not" issue except for enforcing `or{}` at each place of usage).

One idea would actually be to make the `map` into a ["defaultdict"](https://docs.python.org/3/library/collections.html#collections.defaultdict ). It already is a defaultdict under the hood but this would make it possible to specify your own default value. This specification of default value would be optional **but** enforced for reference types (incl. indirect reference types - i.e. structs containing somewhere at any nesting level a reference; special care must be given to sum types which include `| none`).

**Comment by dumblob** [comment] 2021-09-22 07:28
Thinking about this further I'm getting more and more convinced the `defaultdict` solution would be the best course of action.

What do you think @elliotchance @leighmcculloch @spaceface777 ?

**Comment by dumblob** [comment] 2021-09-22 08:04
@danieldaeschle thoughts? (partially related https://github.com/vlang/v/pull/11089 )

**Comment by danieldaeschle** [comment] 2021-09-22 11:56
Yes, this should work like with sum type values.

**Comment by elliotchance** [comment] 2021-09-23 06:40
@dumblob do you have some examples in V of what this would look like?

**Comment by dumblob** [comment] 2021-09-23 07:35
```v
struct Foo {
  a int
  b &Bar
}
struct Bar {
  c f64
}
struct MyDefault {
  d &Bar = Bar{ c: 0.9 }  // default value here
}
fn main() {
  foos := map[string]Foo{ default: Foo{ b: Bar{} } }  // default value
  foo := foos['baz']  // no need for "or { ... }"
  foo2 := foos['baz2']  // default value avoids writing "or { ... }" everywhere
  foo3 := foos['baz3'] or { Foo{ b: Bar{ c: 0.5 } } }  // default value does
      // NOT prevent "or { ... }"
  println( foo.b.c ) // prints "0.0", because the default
      // value is Bar{} whose contents V auto-initializes to zeros

  foos2 := map[string]Foo{}  // no default value here,
      // so the compiler finds out somewhere in the struct tree
      // rooted at Foo{} there is a reference without a default
      // value and enforces you to use "or { ... }" on every
      // place the map is being read
  foo4 := foos2['baz'] or { Foo{ b: Bar{ c: 0.4 } } }
  foo5 := foos2['baz2'] or { Foo{ b: Bar{ c: 0.3 } } }
  println( foo4.b.c )  // prints "0.4"

  foos3 := map[string]MyDefault{}  // no default value here,
      // but the compiler will find out that
      // all references in the struct tree rooted
      // at MyDefault have default values
      // so it won't enforce anything
  foo6 := foos3['baz']
  foo7 := foos3['baz2']
  println( foo6.d.c )  // prints "0.9"
}
```

As you can see **without** the defaultdict semantics it gets extremely verbose soon. If the above behavior will get implemented, *V* will finally **guarantee** there can't be any null dereference when working with maps.

This allows also to obey the `[required]` tag if put next to `b &Bar`. Note, *V* can't unfortunately treat every reference in a struct as `[required]` because of interoperability, performance etc. So we have to balance it on case-by-case basis like we're doing here for `map`s.

**Comment by locriacyber** [comment] 2022-10-08 13:23
It's still not fixed.

```
m := map[string]&Foo{}
e := m['bar'] // unsafe but not considered so
e := m['bar']? // safe
```

**Comment by medvednikov** [comment] 2023-01-15 01:48
Fixed in https://github.com/vlang/v/commit/877a1e511a70e1acffba65584fa619bde55698f7

**Closed by medvednikov** 2023-01-15 01:48 UTC
Labels: Bug

**Comment by dewert99** [comment] 2023-11-11 20:09
I'm not sure the more general issue has been fixed, for example:
```v
struct Foo {
	n &int
}

fn main() {
	x := map[string]Foo{}[""]
	println(x)
	println(*x.n)
}
```
This still complies and produces
Output:

```
/tmp/v_60000/../../../../../../box/code.v:8: at main__main: RUNTIME ERROR: invalid memory access
/tmp/v_60000/../../../../../../tmp/v_60000/code.10347205070839071508.tmp.c:16997: by main
Foo{
    n: &nil
}
Exited with error status 255
```

I would think that `map[string]Foo{}[""]` should only be allowed if `Foo{}` is allowed, ie. not if `Foo` recursively contains reference fields or `[required]` fields.

```
V full version: V 0.4.3 cd337e2
OS: linux, Debian GNU/Linux 11 (bullseye) (VM)
Processor: 1 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz

getwd: /home/admin/playground
vexe: /home/admin/v/v
vexe mtime: 2023-11-11 13:42:45

vroot: OK, value: /home/admin/v
VMODULES: OK, value: /.vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.30.2
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false

CC version: cc (Debian 10.2.1-6) 10.2.1 20210110
thirdparty/tcc: N/A
```

**Comment by elliotchance** [comment] 2023-11-13 15:12
@dewert99 please raise that as a separate bug since this is already closed.
