### ISSUE TITLE
Incorrect the generated C code for nested if expression

### ISSUE THREAD

**Issue by kdmult** [vlang/v#3861] opened 2020-02-27 13:36 UTC
**V version:** V 0.1.25 1c915c3
**OS:** Windows 10

**What did you do?**
Compile program nested_if.v:
```v
module main

fn main() {
	r := if true { if true { 10 } else { 11 } } else { 12 }
	println(r)
}
```

**What did you expect to see?**
%TEMP%\v\nested_if.tmp.c
```c
 void main__main () {
 int r= (( 1 ) ? ( (( 1 ) ? ( 10 ) : ( 11 )) ) : ( 12 )) ;
 println (int_str( r ) ) ;
 }
```
 
**What did you see instead?**
%TEMP%\v\nested_if.tmp.c
```c
 void main__main () {
 (( 1 ) ? ( (( 1 ) ? ( 10 ) : ( 11 )) ) : ( 12 ; 
 }
int r= )) ;
 println (int_str( r ) ) ;
 }
```

**Comment by alexesprit** [comment] 2020-02-27 13:48
Duplicate of #3105.

**Closed by alexesprit** 2020-02-27 13:48 UTC
Labels: Type: Bug
