### ISSUE TITLE
Interface related issues.

### ISSUE THREAD

**Issue by kahsa** [vlang/v#13414] opened 2022-02-09 12:43 UTC
- [x] https://github.com/vlang/v/issues/5535
- [x] https://github.com/vlang/v/issues/10696
- [ ] https://github.com/vlang/v/issues/10980
- [x] https://github.com/vlang/v/issues/11103
- [x] https://github.com/vlang/v/issues/11484
- [x] https://github.com/vlang/v/issues/11499
- [x] https://github.com/vlang/v/issues/11542
- [x] https://github.com/vlang/v/issues/12058
- [x] https://github.com/vlang/v/issues/12127
- [x] https://github.com/vlang/v/issues/12537
- [x] https://github.com/vlang/v/issues/12766
- [x] https://github.com/vlang/v/issues/12834
- [x] https://github.com/vlang/v/issues/12905
- [x] https://github.com/vlang/v/issues/13116
- [ ] https://github.com/vlang/v/issues/13296
- [x] https://github.com/vlang/v/issues/13306
- [x] https://github.com/vlang/v/issues/13411
- [x] https://github.com/vlang/v/issues/13437
- [x] https://github.com/vlang/v/issues/13456
- [x] https://github.com/vlang/v/issues/13467
- [x] https://github.com/vlang/v/issues/13527
- [x] https://github.com/vlang/v/issues/13535

**Comment by medvednikov** [comment] 2022-07-14 06:47
Duplicate of https://github.com/vlang/v/issues/7002

**Closed by medvednikov** 2022-07-14 06:47 UTC
