### ISSUE TITLE
Escape characters \" not working

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3305] opened 2020-01-02 08:36 UTC
**V version:** 
playground

**OS:** 

**What did you do?**
```v
fn main() {
    println("\"V\" is awesome")
} 
```
**What did you expect to see?**
"V" is awesome
 
**What did you see instead?**
You just found a bug.

**Workaround:**
```v
fn main() {
    println('"V" is awesome')  // print "V" is awesome as expected
} 
```

**Comment by alexesprit** [comment] 2020-02-27 13:54
Closed as a duplicate of #2216.

**Closed by alexesprit** 2020-02-27 13:54 UTC
Labels: OS: Playground, Type: Bug
