### ISSUE TITLE
vweb tutorial: Compiling error: ',' expected (got ";")

### ISSUE THREAD

**Issue by GreatGreven** [vlang/v#13979] opened 2022-04-08 21:20 UTC
OS: linux, Ubuntu 20.04.4 LTS (WSL)
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

getwd: /home/egr/workspace/vebb-server
vmodules: /home/egr/.vmodules
vroot: /usr/sbin/v
vexe: /usr/sbin/v/v
vexe mtime: 2022-04-08 19:48:38
is vroot writable: false
is vmodules writable: true
V full version: V 0.2.4 6412f8b.2d867a2

Git version: git version 2.25.1
Git vroot status: weekly.2022.13-92-g2d867a27
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 3654d6a8

**What did you do?**
I tried to follow the [tutorial](https://github.com/vlang/v/tree/master/tutorials/building_a_simple_web_blog_with_vweb) on making a webb-server in V

**What did you expect to see?**
I expected the vweb server to print its start-up messsage "Running a Vweb app on http://localhost:8081"

 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/34370827/162533167-504220a7-21a4-4586-952e-6f5e6f1da12e.png)

**Comment by GreatGreven** [comment] 2022-04-29 07:09
Code pushed to following repo:
[https://github.com/GreatGreven/vebb-server](https://github.com/GreatGreven/vebb-server)

**Comment by Dialga** [comment] 2022-06-23 13:07
Testcase:
```
import sqlite

struct Article {
	id	int
}

pub fn (app &App) find_article(article_id int) ?Article {
	return sql app.db {
		select from Article where id == article_id
	}
}
struct App {
	db sqlite.DB
}
```
```
/usr/lib64/crt1.o: error: Invalid relocation entry [15] '.rela.debug_info' @ 000004f5
tcc: error: file 'crt1.o' not found
/tmp/v_1000/main.17897230013072905456.tmp.c:41334: error: ',' expected (got ";")
```

**Comment by jacksonmowry** [comment] 2024-03-08 12:36
A lot has changed since this issue was posted but I did my best to make the needed changes to both of the examples provided, and I am unable to reproduce the issue in either. I think we are safe to go ahead and close this.

**Comment by JalonSolov** [comment] 2024-03-08 13:13
With no changes to the last example code, V gives nice errors now:
```
x.v:8:9: error: ORM returns a result, so it should have either an `or {}` block, or `!` at the end
    6 | 
    7 | pub fn (app &App) find_article(article_id int) ?Article {
    8 |     return sql app.db {
      |            ~~~~~~~~~~~~
    9 |         select from Article where id == article_id
   10 |     }
x.v:8:9: error: cannot use `[]Article` as type `?Article` in return argument
    6 | 
    7 | pub fn (app &App) find_article(article_id int) ?Article {
    8 |     return sql app.db {
      |            ~~~~~~~~~~~~
    9 |         select from Article where id == article_id
   10 |     }
```

**Closed by JalonSolov** 2024-03-08 13:13 UTC
Labels: Bug, Unit: vweb
