### ISSUE TITLE
Error Interface doesn't work as expected

### ISSUE THREAD

**Issue by ken0x0a** [vlang/v#9329] opened 2021-03-16 16:29 UTC
**V version:**  V full version: V 0.2.2 db9b523.98c611d
**OS:** OS: macos, macOS, 11.2.3,

**What did you do?**
```vlang
module main

fn main() {
	throw_custom_error() or {
		match err {
			MyError {
				println("$err.cod") // compile error!!
			}
			Error {
				println("received default error!!, $err")
			}
			else {
				println("received other error!!, $err")
			}
		}
	}
}

enum MyErrorCode {
	default
	awesome
}
struct MyError {
	msg string
	code int
	c MyErrorCode
}
fn throw_custom_error() ? {
	return IError(MyError { msg: "oops", code: 1 })
}
```

**What did you expect to see?**
`MyErrorCode.default`
 
This behavior is described at https://github.com/vlang/v/pull/9043

**What did you see instead?**
```
custom_error.v:9:19: error: type `IError` has no field or method `cod`
```

**Comment by Gladear** [comment] 2021-03-16 19:47
Duplicate of https://github.com/vlang/v/issues/9061
A PR is already ongoing

**Closed by Gladear** 2021-03-16 19:47 UTC
Labels: Bug
