### ISSUE TITLE
Support generic interfaces

### ISSUE THREAD

**Issue by khaledh** [vlang/v#10258] opened 2021-05-29 21:23 UTC
It would be great to be able to define generic interfaces:

```v
interface Sink<T> {
	write(item T)
}
```

Currently this doesn't work:

```
hello.v:1:15: error: unexpected token `<`, expecting `{`
    1 | interface Sink<T> {
      |               ^
    2 |     write(item T)
    3 | }
```

**Comment by Gladear** [comment] 2021-05-29 21:29
Duplicate of #9735

**Closed by Gladear** 2021-05-29 21:29 UTC
Labels: Feature Request
