### ISSUE TITLE
SDL_MapRGB Missing Param

### ISSUE THREAD

**Issue by kirk-friend** [vlang/v#3787] opened 2020-02-19 23:26 UTC
Missing parameter. 

> Uint32 SDL_MapRGB(const SDL_PixelFormat* format,
>                   **Uint8                  r,**
>                   Uint8                  g, 
>                   Uint8                  b)
>

**Comment by serkonda7** [comment] 2021-04-09 08:17
Closing this due to lacking information how to reproduce.
If you still encounter this error after updating to the latest version (`v up`), please open a new issue.

**Closed by serkonda7** 2021-04-09 08:17 UTC
Labels: Bug
