### ISSUE TITLE
Simple program wont compile, generates a C error

### ISSUE THREAD

**Issue by manfromth3m0oN** [vlang/v#10104] opened 2021-05-14 08:22 UTC
**V doctor:**
```
OS: linux, "Void Linux"
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
CC version: cc (GCC) 10.2.1 20201203

getwd: /home/m0on/projects/v_sort
vmodules: /home/m0on/.vmodules
vroot: /home/m0on/ricingstuff/v
vexe: /home/m0on/ricingstuff/v/v
vexe mtime: 2021-05-14 07:56:59
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 0139836

Git version: git version 2.31.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg v_sort.v`
```v
module main

import rand

fn gen_nums() [10]int {
	mut nums := [10]int{}
	for i in 0 .. 10 {
		nums[i] = rand.int_in_range(0, 10)
	}
	return nums
}

fn main() {
	nums := gen_nums()
	println(nums)
}


```

**What did you expect to see?**

The program to compile 

**What did you see instead?**
```
==================
/usr/lib64/crt1.o: error: Invalid relocation entry [14] '.rela.debug_info' @ 000004f6
tcc: error: file 'crt1.o' not found
/tmp/v/v_sort.7092661630545511290.tmp.c:12311: error: character array initializer must be a literal, optionally enclosed in braces
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

**Comment by spaceface777** [comment] 2021-05-14 13:42
Duplicate of #6051.

**Closed by spaceface777** 2021-05-14 13:42 UTC
