### ISSUE TITLE
Returning a closure and using it results in segmentation fault.

### ISSUE THREAD

**Issue by knarkzel** [vlang/v#12421] opened 2021-11-10 01:18 UTC
**V doctor:**
```
OS: linux, "Arch Linux"
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz
CC version: cc (GCC) 11.1.0

getwd: /home/odd/source/v/vom
vmodules: /home/odd/.vmodules
vroot: /home/odd/source/v/v
vexe: /home/odd/source/v/v/v
vexe mtime: 2021-11-08 15:17:49
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 9b00564.08667c5

Git version: git version 2.33.0
Git vroot status: weekly.2021.45 (2 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg vom.v`
```v
module main

fn take(count int) fn (string) ?[]string {
	return fn [count] (input string) ?[]string {
		if input.len < count {
			return none
		} else {
			return [input[count..], input[..count]]
		}
	}
}

fn main() {
	input := 'hello, world'
	parse := take(5)
	output := parse(input) ?
	println(output)
}

```

**What did you expect to see?**

No segmentation fault, `[', world', 'hello'].

**What did you see instead?**
```
signal 11: segmentation fault
/tmp/v/vom.11937719718747967831.tmp.c:6354: at print_backtrace: Backtrace
/tmp/v/vom.11937719718747967831.tmp.c:6420: by v_segmentation_fault_handler
7f46d0785da0 : by ???
/tmp/v/vom.11937719718747967831.tmp.c:10752: by main__main
/tmp/v/vom.11937719718747967831.tmp.c:11117: by main
```

**Comment by Dialga** [comment] 2021-12-18 01:56
Duplicate of #12877.

**Closed by Dialga** 2021-12-18 01:56 UTC
