### ISSUE TITLE
Playground example is not working

### ISSUE THREAD

**Issue by Sparkenstein** [vlang/v#5057] opened 2020-05-26 18:15 UTC
I believe it was reported earlier as well (See #4273 and #4757 etc) but playground example for json encoding/decoding is not working again.

Steps to reproduce:
 - Visit https://vlang.io/play
 - run json example

**Comment by nedpals** [comment] 2020-05-26 23:33
@Sparkenstein try using https://devbits.app/play

**Comment by Mikilis** [comment] 2020-05-28 15:42
@nedpals wdym? https://devbits.app/play is **Go** playground **not** V

**Comment by Delta456** [comment] 2020-05-28 16:37
@Mikilis there's an option to switch to V as well.

**Comment by Mikilis** [comment] 2020-05-29 09:55
Example working

**Comment by mindplay-dk** [comment] 2020-08-11 15:11
Sample to reproduce the issue:

```v
import json

struct User {
    name string
    age  int

    // Use the `skip` attribute to skip certain fields
    foo string [skip]

    // If the field name is different in JSON, it can be specified
    last_name string [json:lastName]
}

data := '{ "name": "Frodo", "lastName": "Baggins", "age": 25 }'
user := json.decode(User, data) or {
    eprintln('Failed to decode json')
    return
}
println(user.name)
println(user.last_name)
println(user.age)
```

Error displayed:

```
/vlib/json/json_primitives.v:8:3: error: To use @VROOT, you need to have a "v.mod" file in /vlib/json, or in one of its parent folders. 
    6 | #flag -I @VROOT/thirdparty/cJSON
    7 | #flag @VROOT/thirdparty/cJSON/cJSON.o
    8 | #include "cJSON.h"
      |   ~~~~~~~~~~~~~~~~
    9 | #define js_get(object, key) cJSON_GetObjectItemCaseSensitive((object), (key))
   10 | struct C.cJSON {
```

Can confirm the sample runs without errors on `https://devbits.app/play`.

**Comment by mindplay-dk** [comment] 2020-08-14 18:17
Looks like duplicate of #3327 as well as #4892 - probably some of these could be closed.

**Comment by leahlundqvist** [comment] 2020-12-01 10:43
Closing this as the old playground has been retired.

**Closed by leahlundqvist** 2020-12-01 10:43 UTC
Labels: Bug, OS: Playground
