### ISSUE TITLE
array.map() generates compiling error in chained calls

### ISSUE THREAD

**Issue by kevin70g** [vlang/v#3509] opened 2020-01-20 02:16 UTC
array.map() generates compiling error in chained calls.

under windows, two bugs:
1) "UNICODE" redefined warning
2) compiling error
under centos 7.6, only report compiling error

under windows 10 x64, mingw64, gcc:

D:\code\v\vst$ v version
V 0.1.24 760448a

D:\code\v\vst$ gcc --version
gcc (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 6.3.0

D:\code\v\vst$ cat testv.v
fn main() {
  arr := ['a,a', 'b,b']
  for s in arr {
    arr2 := s.split(',').map(it + '1')
    println(arr2)
  }
}

// note: testv.v is unix format and utf-8 encoding.

D:\code\v\vst$ v testv.v
d:\Temp\tmp\v\testv.tmp.c:147:0: warning: "UNICODE" redefined
 #define UNICODE

<command-line>:0:0: note: this is the location of the previous definition
d:\Temp\tmp\v\testv.tmp.c: In function 'm...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

D:\code\v\vst$ v -g testv.v
C compiler=gcc
D:\code\v\vst\testv.v:111:0: warning: "UNICODE" redefined
<command-line>:0:0: note: this is the location of the previous definition
D:\code\v\vst\testv.v: In function 'main__main':
D:\code\v\vst\testv.v:3:25: error: 'string {aka struct string}' has no member named 'data'
   for s in arr {
                         ^
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

under centos 7.6:
[kevin@cent77n1 v]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

[kevin@cent77n1 v]$ v version
V 0.1.24 760448a
[kevin@cent77n1 v]$ v testv.v
/home/kevin/.cache/v/testv.tmp.c: In function ‘main__main’:
/home/kevin/.cache/v/testv.tmp.c:3894:25: error: ‘string’ has no member named ‘data’
  string it = ((string*)s.data)[i];
                   ...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by alexesprit** [comment] 2020-01-20 04:11
Duplicate of #2953.

**Closed** 2020-01-20 04:12 UTC
Labels: Type: Bug
