### ISSUE TITLE
Compile vex based framework code with -prod switch

### ISSUE THREAD

**Issue by asyslinux** [vlang/v#13487] opened 2022-02-16 07:50 UTC
**V version: Latest** 
**OS:Linux Debian(11 amd64, gcc (Debian 10.2.1-6) 10.2.1 20210110)** 

**Code:**
``` 
module main

import nedpals.vex.router
import nedpals.vex.server
import nedpals.vex.ctx

fn main() {
        mut web := router.new()
        web.route(.get, '/', fn (req &ctx.Req, mut res ctx.Resp) {
                println(req)
                res.send_status(200)
        })
        server.serve(web, 7001)
}
```

**What did you do?**

v -prod main.v

**What did you see?**
```
==================
/tmp/v_0/test.17512820484216775925.tmp.c: In function ‘nedpals__vex__router__Router_receive’:
/tmp/v_0/test.17512820484216775925.tmp.c:23156:92: error: field name not in record or union initializer
23156 |    ((string*)map_set(&req.headers, &(string[]){_SLIT("Content-Type")}, &(Array_string[]) { .data)[0]_SLIT("multipart/form-data") });
      |                                                                                            ^
/tmp/v_0/test.17512820484216775925.tmp.c:23156:92: note: (near initialization for ‘(anonymous)’)
/tmp/v_0/test.17512820484216775925.tmp.c:23156:97: error: expected ‘=’ before ‘)’ token
23156 |    ((string*)map_set(&req.headers, &(string[]){_SLIT("Content-Type")}, &(Array_string[]) { .data)[0]_SLIT("multipart/form-data") });
      |                                                                                                 ^
/tmp/v_0/test.17512820484216775925.tmp.c:23156:97: error: expected ‘}’ before ‘)’ token
/tmp/v_0/test.17512820484216775925.tmp.c:23156:130: error: expected ‘)’ before ‘}’ token
23156 |    ((string*)map_set(&req.headers, &(string[]){_SLIT("Content-Type")}, &(Array_string[]) { .data)[0]_SLIT("multipart/form-data") });
      |    ~                                                                                                                             ^
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.
```
**Comments**

I tried compile code with `-prod` option. Without `-prod` swith code is compiled without errors.

**Comment by BenStigsen** [comment] 2022-02-19 17:59
Duplicate of https://github.com/vlang/v/issues/13431

**Closed by BenStigsen** 2022-02-19 17:59 UTC
Labels: Bug
