### ISSUE TITLE
TOML And YAML And MsgPack And SION V Native Support.

### ISSUE THREAD

**Issue by keito940** [vlang/v#1854] opened 2019-09-04 11:06 UTC
TOML Document:[Here](https://github.com/toml-lang/toml)
YAML Document:[Here](https://yaml.org/spec/1.2/spec.html)
MessagePack Document:[Here](https://github.com/msgpack/msgpack/blob/master/spec.md)
SION Document:[Here](https://dankogai.github.io/SION/)

**Comment by dumblob** [comment] 2019-09-04 13:18
Duplicate of https://github.com/vlang/v/issues/1732 ?

**Comment by keito940** [comment] 2019-09-05 08:41
> Duplicate of #1732 ?

No. 
I didn't write it as a copy of # 1732.
I wanted to support serialization other than JSON.

**Comment by keito940** [comment] 2019-09-05 08:44
XML

**Comment by dumblob** [comment] 2019-09-05 10:04
>I wanted to support serialization formats other than JSON.

The discussion there is very general - it's about all formats you could imagine. Feel free to join the discussion there and mention all your formats if you wish to give them priority.

**Comment by lithic** [comment] 2019-09-05 16:27
TOML is easier to use and more understandable than YAML

**Comment by keito940** [comment] 2019-09-08 09:44
TOML Library Create Base Form https://github.com/cktan/tomlc99
Don't Support Encode.
...But I have send Encode Support Issue.

**Comment by keito940** [comment] 2019-09-09 09:10
I found that it was impossible with TOMLC99, so I reorganized the code with reference to the code at https://github.com/BurntSushi/toml.

**Comment by keito940** [comment] 2019-09-09 09:42
As a result of thinking about this, I decided to create a EBNF library and use that EBNF library to build a TOML library.

**Comment by dumblob** [comment] 2019-09-09 09:55
> I decided to create a EBNF library ...

There are many existing and battle-tested ones - see bison, yacc, lex, flex, etc. Don't duplicate this effort, it would be a time loss.

**Comment by keito940** [comment] 2019-09-09 10:06
> There are many existing and battle-tested ones - see bison, yacc, lex, flex, etc. Don't duplicate this effort, it would be a time loss.

Okay.

**Closed** 2019-10-21 15:00 UTC
Labels: feature request

**Comment by nedpals** [comment] 2019-10-21 15:32
Duplicate of #1732
