### ISSUE TITLE
multithread http.get() errors

### ISSUE THREAD

**Issue by sibkod** [vlang/v#19580] opened 2023-10-16 07:25 UTC
### Describe the bug

Various errors occur when executing a get request

### Reproduction Steps

```
module main

import net.http


fn main(){
	mut ch := chan string{}
	mut threads := []thread {}
	for _ in 1 .. 15 {
		threads << spawn  fn(ch chan string){
			for {
				m := <-ch or {
					println('closed')
					break
				}
				res := http.get(m) or {
					println(err)
					continue
				}
				println(res.status_code)
			}
		}(ch)
	}
	for _ in 0..100 {
		s:= "https://google.com"
		ch <- s
	}
	ch.close()
	threads.wait()

}
```

### Expected Behavior

only
```
200
200
```

### Current Behavior

```
SSL handshake failed
response does not start with HTTP/, line: ``
response does not start with HTTP/, line: ``
invalid chunksize
200
200
200
200
200
invalid chunksize
invalid chunksize
SSL handshake failed
```

### V version

V 0.4.2 e0e0987

### Environment details (OS name and version, etc.)

linux fedora38

**Comment by shove70** [comment] 2023-10-18 10:38
This is caused by timeouts caused by security policies on the peer server (e.g., QPS restrictions, etc.).
First, net.http.get, post are read on non-block sockets without using select
Second, net.tcp's select_deadline() method has a slight oversight in handling the result of select()

**Comment by ttytm** [comment] 2023-10-19 08:27
related to https://github.com/vlang/v/issues/18094

**Comment by sibkod** [comment] 2023-10-19 08:39
unfortunately the error remained
 V 0.4.2 07390ef
linux fedora38
```
SSL handshake failed
SSL handshake failed
SSL handshake failed
SSL handshake failed
200
200
200
200
200
200
SSL handshake failed
200
200
200
200
SSL handshake failed
invalid chunksize
200
200
response does not start with HTTP/, line: ``
response does not start with HTTP/, line: ``
response does not start with HTTP/, line: ``
```

**Comment by shove70** [comment] 2023-10-19 11:46
The ```SSL handshake failed``` message is a normal error message that the server has broken the connection due to security policies, QPS restrictions, and so on

```invalid chunksize```, ```response does not start with HTTP/, line: ``` are minor issues with http module, I'll do it.

**Comment by sibkod** [comment] 2023-10-19 11:51
> The `SSL handshake failed` message is a normal error message that the server has broken the connection due to security policies, QPS restrictions, and so on
> 
> `invalid chunksize`, `response does not start with HTTP/, line: ` are minor issues with http module, I'll do it.

I did the same thing on go in 50 threads, there were no such errors

**Comment by JalonSolov** [comment] 2023-10-19 11:55
Go has also had 11 years of release development.  V is still Beta.  The problem will be fixed.

**Comment by sibkod** [comment] 2023-10-19 12:00
> Go has also had 11 years of release development. V is still Beta. The problem will be fixed.

I mean, maybe it's not because of the server response error.

**Comment by spytheman** [comment] 2023-10-19 12:51
Compiling with `-gc none` or with `-d net_blocking_sockets -d use_openssl` fixes it.

The problem is related to an interaction between our lower level code, that wraps mbedtls and openssl, and our garbage collector.

It will be fixed soon.

**Comment by spytheman** [comment] 2023-10-19 12:52
```
#0 15:48:39 ᛋ fix_constant_dependency_order_for_consts_that_use_others_as_method_receivers /v/vnew❱v -gc none run /v/misc/2023_10_19__12/google.v |sort |uniq -c
    100 200
#0 15:48:51 ᛋ fix_constant_dependency_order_for_consts_that_use_others_as_method_receivers /v/vnew❱
#0 15:51:37 ᛋ fix_constant_dependency_order_for_consts_that_use_others_as_method_receivers /v/vnew❱
#0 15:51:38 ᛋ fix_constant_dependency_order_for_consts_that_use_others_as_method_receivers /v/vnew❱
#0 15:51:38 ᛋ fix_constant_dependency_order_for_consts_that_use_others_as_method_receivers /v/vnew❱v -d net_blocking_sockets -d use_openssl run /v/misc/2023_10_19__12/google.v |sort |uniq -c    100 200
#0 15:51:51 ᛋ fix_constant_dependency_order_for_consts_that_use_others_as_method_receivers /v/vnew❱
```

**Comment by sibkod** [comment] 2023-10-19 13:08
> Compiling with `-gc none` or with `-d net_blocking_sockets -d use_openssl` fixes it.
> 
> The problem is related to an interaction between our lower level code, that wraps mbedtls and openssl, and our garbage collector.
> 
> It will be fixed soon.
gc none almost fixed the problem, only such errors remained
```
200
invalid chunksize
invalid chunksize
invalid chunksize

```
-d net_blocking_sockets -d use_openssl

```
200
200
Terminated by signal 13 (SIGPIPE)
```
P.S. Thanks to everyone for such an active participation in solving the problem

**Comment by shove70** [comment] 2023-10-19 16:26
> 200
> 200
> Terminated by signal 13 (SIGPIPE)

```signal 13 (SIGPIPE)``` usually requires "ignore" processing at the beginning of the network application:

V:
```v
#include <signal.h>

[typedef]
struct C.sigset_t {}

fn C.sigaddset(set &C.sigset_t, signum int) int
fn C.sigemptyset(set &C.sigset_t)
fn C.sigprocmask(how int, set &C.sigset_t, oldset &C.sigset_t) int

fn ignore_signal_handler(signal os.Signal) {
	println_t('Exception signal: ${signal}')
}

fn main() {
	// For main thread.
	C.signal(int(os.Signal.pipe), ignore_signal_handler)
	C.signal(int(os.Signal.ill), ignore_signal_handler)
	C.signal(int(os.Signal.urg), ignore_signal_handler)

	// For background threads.
	$if linux {
		mask1 := C.sigset_t{}
		C.sigemptyset(&mask1)
		C.sigaddset(&mask1, int(os.Signal.pipe))
		C.sigaddset(&mask1, int(os.Signal.ill))
		C.sigaddset(&mask1, int(os.Signal.urg))
		C.sigprocmask(0, &mask1, unsafe { nil }) // C.SIG_BLOCK = 0
	}

	...
}
```

Go:
```go
fn main() {
    signal.Ignore(syscall.SIGPIPE, syscall.SIGILL, syscall.SIGURG)

    ...
}
```

D:
```d
void main(string[] args) {
    version (Posix) {
        import core.sys.posix.signal : signal, sigset_t, sigemptyset, sigaddset, sigprocmask, SIG_IGN, SIGPIPE, SIGILL, SIGURG, SIG_BLOCK;

        // For main thread.
        signal(SIGPIPE, SIG_IGN);
        signal(SIGILL,  SIG_IGN);
        signal(SIGURG,  SIG_IGN);

        // For background threads.
        sigset_t mask1;
        sigemptyset(&mask1);
        sigaddset(&mask1, SIGPIPE);
        sigaddset(&mask1, SIGILL);
        sigaddset(&mask1, SIGURG);
        sigprocmask(SIG_BLOCK, &mask1, null);
    }

    ...
}
```

Adding it to the net library as a default option is fine, but it's rarely done, and there are probably scenarios where this shouldn't be done

**Comment by JalonSolov** [comment] 2023-10-19 16:31
Perhaps a trailing struct argument on the connection, normally empty, where you can set signals to ignore?

**Comment by shove70** [comment] 2023-10-19 16:45
SIGPIPE is a signal related to UNIX systems that represents a Broken Pipe. When a process attempts to write data to a write-end of a closed pipe, the kernel sends the SIGPIPE signal to the process to notify it that the pipe has been broken.

SIGPIPE signal typically occurs in the following situations:

Writing to a closed pipe: When a process writes data to a pipe whose write-end has been closed, the kernel sends the SIGPIPE signal. This often happens in inter-process communication between parent and child processes, where the parent closes the write-end and the child process attempts to write to that pipe.

Disconnected network connection: In network programming, when a process writes data to a closed socket, the kernel also sends the SIGPIPE signal. For example, if a process tries to send data to a connection that has been terminated.

By default, if a process receives a SIGPIPE signal and doesn’t handle it, the process will terminate immediately. To avoid abnormal termination due to SIGPIPE signal, it is recommended to handle the signal by either catching it or ignoring it.

-----

Maybe consider ignoring it by default

**Comment by squidink7** [comment] 2023-10-21 02:00
I'm encountering this issue with a [project of mine](https://codeberg.org/sirsegv/figure), but only on Windows. On Linux it seemingly works fine though that might be a coincidence.

**Comment by shove70** [comment] 2023-10-21 02:40
Ok, almost there, a few more PRS and we're almost there

**Closed** 2023-10-30 06:59 UTC
Labels: Bug
