### ISSUE TITLE
compiler should check int overflow

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#137] opened 2019-04-20 11:27 UTC
Compiler should check int overflow, and report an error.

Put follow code into https://vlang.io/play
```
fn main() {
	a := 10000000000
	println(a)
}
```
Then I got `1410065408 `

**Comment by medvednikov** [comment] 2019-04-21 08:36
Duplicate of https://github.com/vlang/v/issues/137

**Closed by medvednikov** 2019-04-21 08:36 UTC
