### ISSUE TITLE
Pressing ctrl-c in repl mode breaks the console

### ISSUE THREAD

**Issue by sereg1k** [vlang/v#2628] opened 2019-11-03 09:56 UTC
**V version:** 0.1.22 [104fab7](https://github.com/vlang/v/commit/104fab7466bf0f2fdf72e86ee917f4f64208cc42)
**OS:** Slackware 14.2 x86_64

**What did you do?**
```
./v
V 0.1.22 104fab7
Use Ctrl-C or `exit` to exit
>>>
```
I press Ctrl-C and after that all the characters in the console become invisible and the Enter key does not work correctly.

If you exit the repl mode with `exit`, then there are no problems.

**Comment by darenliang** [comment] 2019-11-03 21:09
OS: Fedora 31

I can confirm that this is a problem.

**Comment by medvednikov** [comment] 2019-11-03 21:11
@Henrixounez must be a readline issue, works on macOS where readline is disabled.

**Comment by Henrixounez** [comment] 2019-11-04 00:41
This PR should solve the issue, Can you try to see if that resolves correctly your problem ?
I didn't get any issues before on `xfce4-terminal` and `xterm` on my `Fedora 29` so I can't really test for myself.

**Comment by darenliang** [comment] 2019-11-04 01:49
The problem is fixed with the Henrixounez's PR. However, is there a way to insert a new line whenever there is ctrl-c?

**Closed** 2019-11-04 02:05 UTC
Labels: bug
