### ISSUE TITLE
Implement `==` the same way as `str()` is implemented for all types

### ISSUE THREAD

**Issue by hungrybluedev** [vlang/v#4742] opened 2020-05-06 01:50 UTC
In V version 0.1.27, we have the following:

> * Automatic `str()` method generation for every single type, including all arrays and fixed size arrays.

It would be nice to have the same support for `==`. Suggested behaviour:
1. For primitive types, implementation is trivial.
2. For structs, corresponding fields need to be checked.
3. For arrays, corresponding elements need to be checked. Note that elements maybe structs themselves and it depends on 2.

**Edit**: 
1. Adding support for `<` and `>` would be great too.
2. `string` already has `eq()`, `ne()`, `lt()`, `le()`, `gt()` and `ge()`.

**Comment by Delta456** [comment] 2020-05-24 15:19
Duplicate of https://github.com/vlang/v/issues/4365

**Closed by Delta456** 2020-05-24 15:19 UTC
Labels: Feature Request
