### ISSUE TITLE
vfmt os

### ISSUE THREAD

**Issue by kahsa** [vlang/v#6995] opened 2020-11-28 10:33 UTC
**V version:0.1.30 ed39d15** 
**OS:archlinux** 

**What did you do?**
```
module main

fn main() {
	os := MyStruct{}
}
```
vfmt above is ok, but after adding this line `os.add()` ...

```
module main

fn main() {
	os := MyStruct{}
	os.add()  // <<< add this line and vfmt...
}
```
then..
```
import os  //<<<< vfmt added

module main

fn main() {
	os := MyStruct{}
	os.add() // <<< add this line and vfmt...
}
```

**What did you expect to see?**

 
**What did you see instead?**

**Comment by Delta456** [comment] 2020-11-28 10:38
It happens because `vfmt` thinks that a vlib module is used if the name are same. It's a feature and it is not recommended to use vlib names as far as I know.

**Comment by JalonSolov** [comment] 2020-11-28 15:19
Some sort of error message should be given, instead of doing a "blind insert" of the import.  There is one if you try to compile the code.
```v
foo.v:4:8: error: unknown struct: MyStruct
    2 |
    3 | fn main() {
    4 |     os := MyStruct{}
      |           ~~~~~~~~~~
    5 |     os.add()
    6 | }
foo.v:5:5: error: unknown method: `MyStruct.add`
    3 | fn main() {
    4 |     os := MyStruct{}
    5 |     os.add()
      |        ~~~~~
    6 | }
    7 |
```

**Comment by Delta456** [comment] 2020-11-28 16:23
I think we will have to a deep check as this will also work for third part modules too and I think it can be solved by checking every single function, struct and consts defined inside the module.

**Comment by serkonda7** [comment] 2021-05-22 14:57
duplicate of #9713

**Closed by serkonda7** 2021-05-22 14:57 UTC
Labels: Bug, Unit: vfmt
