### ISSUE TITLE
Default values in sub structures not respected

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#6498] opened 2020-09-27 15:03 UTC
### Version
V: 0.1.29 b999d01

### Description
Default values of sub structures are not respected

```
module main

enum Enum {
	one
	two
}

struct Foo {
	e Enum = Enum.two
	b Bar
}

struct Bar {
	e Enum = Enum.two
}

fn main() {
	f := Foo{}
	println(f.e) // Prints two ✅ 
	println(f.b.e) // Prints one 🔴 
	b := Bar{}
	println(b.e) // Prints two ✅ 
}
```

**Comment by spaceface777** [comment] 2020-09-27 16:48
Duplicate of #6339.

**Closed by spaceface777** 2020-09-27 16:48 UTC
Labels: Bug
