### ISSUE TITLE
Printing inside `$if` produces C error

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vlang/v#6648] opened 2020-10-19 14:10 UTC
**V version:** 0.1.29 c3626bf.0d31b39
**OS:** linux, Ubuntu 20.04.1 LTS

**What did you do?**
```V
$if linux && x64 {
    println('64-bit Linux.')
}
```

**What did you expect to see?**
64-bit Linux.
 
**What did you see instead?**
```
v -cg run ./bug.v 
/tmp/v/bug.tmp.c: In function ‘strconv__v_sprintf’:
/tmp/v/bug.tmp.c:3543:7: warning: variable ‘th_separator’ set but not used [-Wunused-but-set-variable]
 3543 |  bool th_separator = false;
      |       ^~~~~~~~~~~~
/tmp/v/bug.tmp.c: In function ‘print_backtrace_skipping_top_frames_linux’:
/tmp/v/bug.tmp.c:5015:26: warning: passing argument 1 of ‘backtrace’ from incompatible pointer type [-Wincompatible-pointer-types]
 5015 |  int nr_ptrs = backtrace(buffer, 100);
      |                          ^~~~~~
      |                          |
      |                          unsigned char **
In file included from /tmp/v/bug.tmp.c:121:
/usr/include/execinfo.h:27:30: note: expected ‘void **’ but argument is of type ‘unsigned char **’
   27 | extern int backtrace (void **__array, int __size) __nonnull ((1));
      |                       ~~~~~~~^~~~~~~
/tmp/v/bug.tmp.c:5022:40: warning: passing argument 1 of ‘backtrace_symbols’ from incompatible pointer type [-Wincompatible-pointer-types]
 5022 |  charptr* csymbols = backtrace_symbols(&buffer[skipframes], nr_actual_frames);
      |                                        ^~~~~~~~~~~~~~~~~~~
      |                                        |
      |                                        unsigned char **
In file included from /tmp/v/bug.tmp.c:121:
/usr/include/execinfo.h:32:15: note: expected ‘void * const*’ but argument is of type ‘unsigned char **’
   32 | extern char **backtrace_symbols (void *const *__array, int __size)
      |               ^~~~~~~~~~~~~~~~~
/tmp/v/bug.tmp.c: In function ‘DenseArray_zeros_to_end’:
/tmp/v/bug.tmp.c:5590:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘u32’ {aka ‘unsigned int’} [-Wsign-compare]
 5590 |  for (int i = 0; i < d->len; ++i) {
      |                    ^
/tmp/v/bug.tmp.c: At top level:
/tmp/v/bug.tmp.c:7980:10: error: expected declaration specifiers or ‘...’ before ‘tos_lit’
 7980 |  println(tos_lit("64-bit Linux."));
      |          ^~~~~~~
builder error: 
==================
C error. This should never happen.

```

**Comment by Delta456** [comment] 2020-10-19 15:02
Can you try updating your v version? I think this got fixed recently.

**Comment by spaceface777** [comment] 2020-10-19 15:20
Duplicate of #6419.

**Closed by spaceface777** 2020-10-19 15:20 UTC
Labels: Bug
