### ISSUE TITLE
Cannot run tests in project folders ending with .v

### ISSUE THREAD

**Issue by bombsimon** [vlang/v#4043] opened 2020-03-16 17:42 UTC
**V version:** V 0.1.25 cff6f4a
**OS:** macOS 10.15.3

**What did you do?**
Created a project with the suffix `.v`.

**What did you expect to see?**
The tests to work.
 
**What did you see instead?**
An error:

```sh
$ v test ./
---------------------------- Testing... --------------------------
FAIL    25 ms [1/1] my_module_test.v
`/tmp/v-test.v/my_module_test.v`
 (
/tmp/v-test.v:1:0: invalid character ``
)
------------------------------------------------------------------
      26 ms <=== total time spent running V _test.v files
                 ok, fail, total =     0,     1,     1
```

**Steps to reproduce**

* Create a folder suffixed with `.v` - `mkdir v-test.v`
* Add these files:
```sh
==> my_module.v <==
module my_module

fn add(a, b int) int {
        return a + b
}

==> my_module_test.v <==
module my_module

fn test_add() {
        assert add(1, 2) == 3
}
```
* Try to run the test - `v test ./`

**Workaround**

* Re-name the project folder - `cd .. && mv v-test.v v-test`
* Run the test again - `cd v-test && v test ./`

Output:

```sh
$ v test ./
---------------------------- Testing... --------------------------
OK   468 ms [1/1] my_module_test.v
------------------------------------------------------------------
     469 ms <=== total time spent running V _test.v files
                 ok, fail, total =     1,     0,     1
```

**Comment by RiordanIX** [comment] 2020-03-16 18:31
I had the same thing, but I had panic. Probably has something to do with different file-system structure.
Anyways, I think the issue is checking whether the thing named `*.v` is a directory.

**Comment by RiordanIX** [comment] 2020-03-19 04:05
I have a fix for this, but do we want to print an error message and abort instead?
This also happens when you do:
`v -o /path/to/dir_ending_in.v/foo /path/to/dir_ending_in.v/foo.v`

**Closed** 2020-03-19 06:07 UTC
Labels: Type: Bug
