### ISSUE TITLE
compile with llvm on window10, lld can not link to glfw3.dll

### ISSUE THREAD

**Issue by gshields** [vlang/v#3658] opened 2020-02-05 10:03 UTC
using bash, windows10, llvm from https://github.com/mstorsjo/llvm-mingw/releases 
$ v -cg ./users.v
C compiler=gcc
warning: E:\p-tools\v\vlib\time\time.v:218:16: you are calling an unsafe function outside of an unsafe block
warning: E:\p-tools\v\vlib\os\os.v:126:18: you are calling an unsafe function outside of an unsafe block
warning: E:\p-tools\v\vlib\os\os.v:688:15: you are calling an unsafe function outside of an unsafe block
warning: E:\p-tools\v\vlib\os\os.v:711:23: you are calling an unsafe function outside of an unsafe block
warning: E:\p-tools\v\vlib\os\os_windows.v:207:26: you are calling an unsafe function outside of an unsafe block
warning: E:\p-tools\v\vlib\glm\glm.v:280:26: you are calling an unsafe function outside of an unsafe block
warning: ./users.v:51:2: reference field `App*.window` must be initialized
warning: ./users.v:145:5: reference field `ui.PictureConfig.ref` must be initialized
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:145:9: warning: 'UNICODE' macro redefined [-Wmacro-redefined]
#define UNICODE
        ^
<command line>:1:9: note: previous definition is here
#define UNICODE 1
        ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:3180:58: warning: incompatible pointer types passing 'int *' to parameter of type 'LPDWORD' (aka 'unsigned long *') [-Wincompatible-pointer-types]
 WriteConsole ( output_handle ,  wide_str ,  wide_len ,  & bytes_written ,  0 ) ;
                                                         ^~~~~~~~~~~~~~~
E:\p-tools\llvm-mingw\include\wincon.h:264:122: note: passing argument to parameter 'lpNumberOfCharsWritten' here
  WINBASEAPI WINBOOL WINAPI WriteConsoleW(HANDLE hConsoleOutput,CONST VOID *lpBuffer,DWORD nNumberOfCharsToWrite,LPDWORD lpNumberOfCharsWritten,LPVOID lpReserved);
                                                                                                                         ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:3183:58: warning: incompatible pointer types passing 'int *' to parameter of type 'LPDWORD' (aka 'unsigned long *') [-Wincompatible-pointer-types]
 WriteFile ( output_handle , (char*) s .str ,  s .len ,  & bytes_written ,  0 ) ;
                                                         ^~~~~~~~~~~~~~~
E:\p-tools\llvm-mingw\include\fileapi.h:179:109: note: passing argument to parameter 'lpNumberOfBytesWritten' here
  WINBASEAPI WINBOOL WINAPI WriteFile (HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
                                                                                                            ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:3561:55: warning: format specifies type 'unsigned int' but the argument has type 'i64' (aka 'long long') [-Wformat]
int count= sprintf ( ((charptr)( hex ) ) ,  "0x%x" ,  n ) ;
                                               ~~     ^
                                               %llx
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:3567:56: warning: format specifies type 'unsigned long' but the argument has type 'u64' (aka 'unsigned long long') [-Wformat]
int count= sprintf ( ((charptr)( hex ) ) ,  "0x%lx" ,  n ) ;
                                               ~~~     ^
                                               %llx
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:5704:24: warning: overlapping comparisons always evaluate to false [-Wtautological-overlap-compare]
return  ( ( x >= 0x89  &&  x <= 0x13 )  ||  x == 0x20 ) == 1 ;
            ~~~~~~~~~~~^~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6782:39: warning: passing 'char *' to parameter of type 'const stbi_uc *' (aka 'const unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
 res .data  =  stbi_load_from_memory ((char*) buf ,  3812 ,  & res .width ,  & res .height ,  & res .nr_channels ,  flag ) ;
                                      ^~~~~~~~~~~
E:\p-tools\v\thirdparty\stb_image\stb_image.h:375:68: note: passing argument to parameter 'buffer' here
STBIDEF stbi_uc *stbi_load_from_memory   (stbi_uc           const *buffer, int len   , int *x, int *y, int *channels_in_file, int desired_channels);
                                                                   ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:7703:63: warning: incompatible pointer types passing 'int *' to parameter of type 'LPDWORD' (aka 'unsigned long *') [-Wincompatible-pointer-types]
 ReadConsole ( h_input , (char*) buf ,  max_line_chars * 2 ,  & bytes_read ,  0 ) ;
                                                              ^~~~~~~~~~~~
E:\p-tools\llvm-mingw\include\wincon.h:262:114: note: passing argument to parameter 'lpNumberOfCharsRead' here
  WINBASEAPI WINBOOL WINAPI ReadConsoleW(HANDLE hConsoleInput,LPVOID lpBuffer,DWORD nNumberOfCharsToRead,LPDWORD lpNumberOfCharsRead,LPVOID lpReserved);
                                                                                                                 ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:7710:52: warning: incompatible pointer types passing 'int *' to parameter of type 'LPDWORD' (aka 'unsigned long *') [-Wincompatible-pointer-types]
bool res= ReadFile ( h_input , (char*) pos ,  1 ,  & bytes_read ,  0 ) ;
                                                   ^~~~~~~~~~~~
E:\p-tools\llvm-mingw\include\fileapi.h:171:106: note: passing argument to parameter 'lpNumberOfBytesRead' here
  WINBASEAPI WINBOOL WINAPI ReadFile (HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
                                                                                                         ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8444:7: warning: incompatible pointer types initializing 'HWND *' (aka 'struct HWND__ **') with an expression of type 'HWND' (aka 'struct HWND__ *') [-Wincompatible-pointer-types]
HWND* hwnd= CreateWindowEx ( 0 ,  wndclass .lpszClassName ,  wndclass .lpszClassName ,  0 ,  0 ,  0 ,  0 ,  0 ,  HWND_MESSAGE ,  NULL ,  NULL ,  NULL ) ;
      ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8449:13: warning: incompatible pointer types assigning to 'HWND' (aka 'struct HWND__ *') from 'HWND *' (aka 'struct HWND__ **'); dereference with * [-Wincompatible-pointer-types]
 cb ->hwnd  =  hwnd ;
            ^  ~~~~
               *
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8523:2: warning: non-void function does not return a value [-Wreturn-type]
 }
 ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8700:31: warning: incompatible integer to pointer conversion assigning to 'f32 *' (aka 'float *') from 'int' [-Wint-conversion]
 res [/*ptr!*/ 0 ]/*rf32 1*/  =  1 ;
                              ^  ~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8701:31: warning: incompatible integer to pointer conversion assigning to 'f32 *' (aka 'float *') from 'int' [-Wint-conversion]
 res [/*ptr!*/ 5 ]/*rf32 1*/  =  1 ;
                              ^  ~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8702:32: warning: incompatible integer to pointer conversion assigning to 'f32 *' (aka 'float *') from 'int' [-Wint-conversion]
 res [/*ptr!*/ 10 ]/*rf32 1*/  =  1 ;
                               ^  ~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8703:32: warning: incompatible integer to pointer conversion assigning to 'f32 *' (aka 'float *') from 'int' [-Wint-conversion]
 res [/*ptr!*/ 15 ]/*rf32 1*/  =  1 ;
                               ^  ~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8807:7: warning: incompatible integer to pointer conversion initializing 'void *' with an expression of type 'int' [-Wint-conversion]
void* ok= gladLoadGL ( ) ;
      ^   ~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8830:34: warning: incompatible pointer types passing 'byte **' (aka 'unsigned char **') to parameter of type 'const GLchar *const *' (aka 'const char *const *') [-Wincompatible-pointer-types]
 glShaderSource ( shader ,  a ,  & source .str ,  b ) ;
                                 ^~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8830:51: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const GLint *' (aka 'const int *'); take the address with & [-Wint-conversion]
 glShaderSource ( shader ,  a ,  & source .str ,  b ) ;
                                                  ^
                                                  &
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8856:45: warning: passing 'byte [512]' to parameter of type 'GLchar *' (aka 'char *') converts between pointers to integer types with different sign [-Wpointer-sign]
 glGetShaderInfoLog ( shader ,  512 ,  0 ,  info_log ) ;
                                            ^~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8861:48: warning: passing 'byte [1024]' to parameter of type 'GLchar *' (aka 'char *') converts between pointers to integer types with different sign [-Wpointer-sign]
 glGetProgramInfoLog ( program ,  1024 ,  0 ,  info_log ) ;
                                               ^~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8907:43: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const void *' [-Wint-conversion]
 glDrawElements ( mode ,  count ,  typ ,  indices ) ;
                                          ^~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8933:74: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const void *' [-Wint-conversion]
 glVertexAttribPointer ( index ,  size ,  typ ,  normalized ,  stride ,  ptr ) ;
                                                                         ^~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9068:23: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'GLFWcursor *' (aka 'struct GLFWcursor *') [-Wint-conversion]
 glfwSetCursor ( 0 ,  GLFW_IBEAM_CURSOR ) ;
                      ^~~~~~~~~~~~~~~~~
E:\p-tools\v\thirdparty\glfw\GLFW/glfw3.h:1051:37: note: expanded from macro 'GLFW_IBEAM_CURSOR'
#define GLFW_IBEAM_CURSOR           0x00036002
                                    ^~~~~~~~~~
E:\p-tools\v\thirdparty\glfw\GLFW/glfw3.h:4329:60: note: passing argument to parameter 'cursor' here
GLFWAPI void glfwSetCursor(GLFWwindow* window, GLFWcursor* cursor);
                                                           ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9071:30: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'GLFWcursor *' (aka 'struct GLFWcursor *') [-Wint-conversion]
 glfwSetCursor ( w ->data ,  GLFW_IBEAM_CURSOR ) ;
                             ^~~~~~~~~~~~~~~~~
E:\p-tools\v\thirdparty\glfw\GLFW/glfw3.h:1051:37: note: expanded from macro 'GLFW_IBEAM_CURSOR'
#define GLFW_IBEAM_CURSOR           0x00036002
                                    ^~~~~~~~~~
E:\p-tools\v\thirdparty\glfw\GLFW/glfw3.h:4329:60: note: passing argument to parameter 'cursor' here
GLFWAPI void glfwSetCursor(GLFWwindow* window, GLFWcursor* cursor);
                                                           ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9080:14: warning: initializing 'GLFWvidmode *' (aka 'struct GLFWvidmode *') with an expression of type 'const GLFWvidmode *' (aka 'const struct GLFWvidmode *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
GLFWvidmode* mode= glfwGetVideoMode ( glfwGetPrimaryMonitor ( ) ) ;
             ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9443:23: warning: passing 'int *' to parameter of type 'GLuint *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
 glGenTextures ( 1 ,  & texture ) ;
                      ^~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9470:7: warning: incompatible integer to pointer conversion initializing 'void *' with an expression of type 'FT_Error' (aka 'int') [-Wint-conversion]
void* ret= FT_Init_FreeType ( & ft ) ;
      ^    ~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9493:7: warning: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
 ret  =  ((int)( FT_New_Face ( ft , (char*) font_path .str ,  0 ,  & face ) ) ) ;
      ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9701:79: warning: incompatible pointer types passing 'void (ui__Button *, ui__MouseEvent *, ui__Window *)' (aka 'void (struct ui__Button *, struct ui__MouseEvent *, struct ui__Window *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_click , ui__btn_click , b ) ;
                                                                              ^~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9801:79: warning: incompatible pointer types passing 'void (ui__CheckBox *, ui__MouseEvent *, ui__Window *)' (aka 'void (struct ui__CheckBox *, struct ui__MouseEvent *, struct ui__Window *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_click , ui__cb_click , cb ) ;
                                                                              ^~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9856:79: warning: incompatible pointer types passing 'void (ui__Dropdown *, ui__MouseEvent *)' (aka 'void (struct ui__Dropdown *, struct ui__MouseEvent *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_click , ui__dd_click , dd ) ;
                                                                              ^~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9857:82: warning: incompatible pointer types passing 'void (ui__Dropdown *, ui__KeyEvent *)' (aka 'void (struct ui__Dropdown *, struct ui__KeyEvent *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_key_down , ui__dd_key_down , dd ) ;
                                                                                 ^~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:9858:84: warning: incompatible pointer types passing 'void (ui__Dropdown *, ui__MouseEvent *)' (aka 'void (struct ui__Dropdown *, struct ui__MouseEvent *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_mouse_move , ui__dd_mouse_move , dd ) ;
                                                                                   ^~~~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:10294:79: warning: incompatible pointer types passing 'void (ui__Radio *, ui__MouseEvent *)' (aka 'void (struct ui__Radio *, struct ui__MouseEvent *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_click , ui__radio_click , r ) ;
                                                                              ^~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:10418:79: warning: incompatible pointer types passing 'void (ui__Slider *, ui__MouseEvent *)' (aka 'void (struct ui__Slider *, struct ui__MouseEvent *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_click , ui__slider_click , s ) ;
                                                                              ^~~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:10419:82: warning: incompatible pointer types passing 'void (ui__Slider *, ui__KeyEvent *)' (aka 'void (struct ui__Slider *, struct ui__KeyEvent *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_key_down , ui__slider_key_down , s ) ;
                                                                                 ^~~~~~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:10420:84: warning: incompatible pointer types passing 'void (ui__Slider *, ui__MouseEvent *)' (aka 'void (struct ui__Slider *, struct ui__MouseEvent *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_mouse_move , ui__slider_mouse_move , s ) ;
                                                                                   ^~~~~~~~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:10718:79: warning: incompatible pointer types passing 'void (ui__Switch *, ui__MouseEvent *, ui__Window *)' (aka 'void (struct ui__Switch *, struct ui__MouseEvent *, struct ui__Window *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_click , ui__sw_click , s ) ;
                                                                              ^~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:10771:79: warning: incompatible pointer types passing 'void (ui__TextBox *, ui__MouseEvent *)' (aka 'void (struct ui__TextBox *, struct ui__MouseEvent *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_click , ui__tb_click , tb ) ;
                                                                              ^~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:10772:82: warning: incompatible pointer types passing 'void (ui__TextBox *, ui__KeyEvent *, ui__Window *)' (aka 'void (struct ui__TextBox *, struct ui__KeyEvent *, struct ui__Window *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_key_down , ui__tb_key_down , tb ) ;
                                                                                 ^~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:10773:80: warning: incompatible pointer types passing 'void (ui__TextBox *, ui__KeyEvent *, ui__Window *)' (aka 'void (struct ui__TextBox *, struct ui__KeyEvent *, struct ui__Window *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_key_up , ui__tb_key_up , tb ) ;
                                                                               ^~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:10774:84: warning: incompatible pointer types passing 'void (ui__TextBox *, ui__MouseEvent *)' (aka 'void (struct ui__TextBox *, struct ui__MouseEvent *)') to parameter of type 'EventHandlerFn' (aka 'void (*)(void *, void *, void *)') [-Wincompatible-pointer-types]
 eventbus__Subscriber_subscribe_method ( subscriber ,  ui__events .on_mouse_move , ui__tb_mouse_move , tb ) ;
                                                                                   ^~~~~~~~~~~~~~~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:6857:99: note: passing argument to parameter 'handler' here
 void eventbus__Subscriber_subscribe_method (eventbus__Subscriber* s, string name, EventHandlerFn handler, void* receiver) {
                                                                                                  ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:11459:19: warning: incompatible pointer types passing 'char *' to parameter of type 'LPCWSTR' (aka 'const unsigned short *') [-Wincompatible-pointer-types]
 MessageBox ( 0 , (char*) s .str , (char*) title .str ,  MB_OK ) ;
                  ^~~~~~~~~~~~~~
E:\p-tools\llvm-mingw\include\winuser.h:3567:55: note: passing argument to parameter 'lpText' here
  WINUSERAPI int WINAPI MessageBoxW(HWND hWnd,LPCWSTR lpText,LPCWSTR lpCaption,UINT uType);
                                                      ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:11459:36: warning: incompatible pointer types passing 'char *' to parameter of type 'LPCWSTR' (aka 'const unsigned short *') [-Wincompatible-pointer-types]
 MessageBox ( 0 , (char*) s .str , (char*) title .str ,  MB_OK ) ;
                                   ^~~~~~~~~~~~~~~~~~
E:\p-tools\llvm-mingw\include\winuser.h:3567:70: note: passing argument to parameter 'lpCaption' here
  WINUSERAPI int WINAPI MessageBoxW(HWND hWnd,LPCWSTR lpText,LPCWSTR lpCaption,UINT uType);
                                                                     ^
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:11638:4073: warning: incompatible pointer types initializing 'ButtonClickFn' (aka 'void (*)(void *, void *)') with an expression of type 'void (App *)' (aka 'void (struct App *)') [-Wincompatible-pointer-types]
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:11638:5631: warning: incompatible pointer types initializing 'DrawFn' (aka 'void (*)(void *)') with an expression of type 'void (App *)' (aka 'void (struct App *)') [-Wincompatible-pointer-types]
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:11905:43: warning: incompatible pointer types passing 'wchar_t **' (aka 'unsigned short **') to parameter of type 'byteptr *' (aka 'unsigned char **') [-Wincompatible-pointer-types]
   os__args = os__init_os_args_wide(argc, argv);
                                          ^~~~
C:\Users\ghs\AppData\Local\Temp\v\users.tmp.c:8163:57: note: passing argument to parameter 'argv' here
 array_string os__init_os_args_wide (int argc, byteptr* argv) {
                                                        ^
48 warnings generated.
lld: error: lld doesn't support linking directly against E:\p-tools\v\thirdparty\glfw\glfw3.dll, use an import library
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by vitalyster** [comment] 2020-02-05 10:16
Duplicate of #3449

**Closed by vitalyster** 2020-02-05 10:16 UTC
Labels: Type: Bug
