### ISSUE TITLE
unnecessary mut

### ISSUE THREAD

**Issue by kahsa** [vlang/v#7125] opened 2020-12-04 09:17 UTC
```v
struct Strct {
}

fn (mut s Strct) func() {
	println('')
}
```
In this case, cheker should warn that the mut is unnecessary ?

**Comment by medvednikov** [comment] 2020-12-04 09:24
Good one, I think it actually did in the old parser.

**Comment by spytheman** [comment] 2020-12-05 09:43
In the old parser, it indeed warned about that:
s.v:
```v
struct Strct {}
fn (s mut Strct) func() {
        println('func called')
}
fn main(){
        mut s := Strct{}
        s.func()
}
```
... produces with new v vs oldv:
```shell
0[11:42:14]delian@nemesis: /v/pv $ ./v version
V 0.1.30 0dfcacd
0[11:42:18]delian@nemesis: /v/pv $ /v/oldv/v version
V 0.1.25 f657c4b
0[11:42:22]delian@nemesis: /v/pv $ 
0[11:42:26]delian@nemesis: /v/pv $ ./v run ss.v 
ss.v:2:7: warning: use `(mut f Foo)` instead of `(f mut Foo)`
    1 | struct Strct {}
    2 | fn (s mut Strct) func() {
      |       ~~~
    3 |     println('func called')
    4 | }
func called
0[11:42:33]delian@nemesis: /v/pv $ 
0[11:42:34]delian@nemesis: /v/pv $ /v/oldv/v run ss.v 
warning: ss.v:5:2: `s` is declared as mutable, but it was never changed
func called
0[11:42:40]delian@nemesis: /v/pv $
```

**Comment by crthpl** [comment] 2021-04-29 05:58
Duplicate of #7943

That one is more official (it is marked as a feature request, and it is opened by daniel).

**Closed by crthpl** 2021-04-29 05:58 UTC
Labels: Bug
