### ISSUE TITLE
Can not convert array to string

### ISSUE THREAD

**Issue by aguspiza** [vlang/v#766] opened 2019-06-28 15:30 UTC
**V version: 0.1.8** 
**OS: ubunti 16.04** 

**What did you do?**
```
//os_test.v
const( ARRLEN = 16)

fn test_arrconst() {
    mut arr := [ byte(0) ; ARRLEN]
    str := tos(arr,ARRLEN)
    assert str.len == ARRLEN 
} 
```
**What did you expect to see?**
Compile and pass test
 
**What did you see instead?**
Compiler error:
```
pass=2 fn=`test_arrconst`
panic: os_test.v:5
Fn "tos" wrong arg #1. Expected "byte*" (s)  but got "[]byte"
```

**Comment by athif23** [comment] 2019-06-28 17:48
From what I know, it's clear that you need to pass a "byte" type to the first argument, but you pass an array of "byte" instead. So, I think it's not a bug. That's just how it is.

**Comment by aguspiza** [comment] 2019-06-28 18:19
So:
arr = [ byte(1), 2, 3 ]         //type []byte acording to docs
arr2 = [3]byte                   //type byteptr ??
arr3 = [ byte(0) ; 3 ]          //type []byte

arr and arr3 can not be converted to string with tos() while arr2 does.

I was trying another notation to use a const for the length of the array because of #762

**Comment by medvednikov** [comment] 2019-06-28 18:20
`string()` should work with all of this. Thanks, will fix.

**Comment by ntrel** [comment] 2019-07-10 09:04
Use `arr.data`. This code works:
```
    mut arr := [ byte(0) ; ARRLEN]
    str := tos(arr.data, ARRLEN)
```

> string() should work with all of these

Closing this in favour of #934.

**Comment by medvednikov** [comment] 2019-08-04 07:52
Fixed:

`str := string(bytes_array)`

**Closed by medvednikov** 2019-08-04 07:52 UTC
Labels: bug
