### ISSUE TITLE
const prefix causes fmt and test fails dependent on the working dir 

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#9286] opened 2021-03-13 10:20 UTC
**V version:** V 0.2.2 f648e3f
**OS:** Manajro

**Here are two CI  runs from my termtable module:**
1. With unformatted code <https://github.com/serkonda7/termtable/actions/runs/648745656>
Here tests pass inside and outside the folder.
But the fmt job passes inside the directory too, which it shouldn't as my consts are not prefixed.

2. With formatted code <https://github.com/serkonda7/termtable/actions/runs/648743979>
Here both fmt jobs pass.
But the tests from inside the folder fails *due to the prefixed consts*.

**What did you expect to see?**
In the first case, all fmt jobs should fail.
In the second case all tests should pass.

**Comment by serkonda7** [comment] 2021-03-15 10:57
Can't we just change the const naming back to `UPPERCASE`?

**Comment by ttytm** [comment] 2024-03-21 22:01
Closing as the issue is dated without a reproducible case. Please don't hesitate to reach out again when you experience further issues or provide reproducible case then we'll reopen.

**Closed by ttytm** 2024-03-21 22:01 UTC
Labels: Bug
