### ISSUE TITLE
Compiler C Error When Assigning `byte` Array to Variable

### ISSUE THREAD

**Issue by theonewolf** [vlang/v#9292] opened 2021-03-13 16:01 UTC
```
> v doctor
OS: linux, Ubuntu 20.04.1 LTS (WSL 2)
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

getwd: /home/wolf/Development/v-ffsem
vmodules: /home/wolf/.vmodules
vroot: /home/wolf/v
vexe: /home/wolf/v/v
vexe mtime: 2021-03-13 15:53:47
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 167dcc4

Git version: git version 2.25.1
Git vroot status: weekly.2021.10-85-g167dcc41
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```

**What did you do?**

I wrote this program:

```v
fn test() [8]byte {
        mut mask := [8]byte{init: 0}
        return mask
}

fn main() {
        mask := test() // if you comment out this line, it will build fine
        println(mask)
}
```

Sadly this is a blocker to my progress so far in building a small V library.

**What did you expect to see?**

I expected the program to compile properly.
 
**What did you see instead?**

I saw an error message warning me to file a bug report, as I am not working with any amount of C interop (the code above is the entirety of the program):

```
> v test.v -cg
/tmp/v/test.18310010692477586442.tmp.c:8729: error: character array initializer must be a literal, optionally enclosed in braces
builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by theonewolf** [comment] 2021-03-13 16:14
Looking at the underlying generated C code, I believe we are hitting this problem?

https://stackoverflow.com/a/16728715

**Comment by ntrel** [comment] 2021-03-13 17:39
Duplicate of #6051

**Closed** 2021-03-13 17:39 UTC
Labels: Bug
