### ISSUE TITLE
Alias bug

### ISSUE THREAD

**Issue by maurizio-ferreira** [vlang/v#11194] opened 2021-08-15 20:06 UTC
**V doctor:**
```
OS: linux, Ubuntu 20.04.2 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

getwd: /home/maurizio/Documenti/Progetti/V/Renderer
vmodules: /home/maurizio/.vmodules
vroot: /home/maurizio/Pubblici/v
vexe: /home/maurizio/Pubblici/v/v
vexe mtime: 2021-08-15 20:04:36
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 900c37a.ea4f6fd

Git version: git version 2.25.1
Git vroot status: weekly.2021.32-73-gea4f6fd4
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg Renderer.v`
```v

struct Quad { 
  mut:
   x f64
   y f64
   z f64
   w f64
}

type Point  = Quad
type Vector = Quad



fn new_point (x f64, y f64, z f64 ) &Point {
  return & Point {x,y,z,1}
}


fn new_vector (x f64, y f64, z f64 ) &Vector {
  return & Vector {x,y,z,0}
}


fn main() {
 mut n  := new_point (1,2,3)
 println(n)
  
}





```

**What did you expect to see?**

**What did you see instead?**
```
==================
/tmp/v/Renderer.9942594025608408767.tmp.c:10352: error: cannot convert 'struct main__Quad *' to 'struct main__Quad'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

**Comment by JalonSolov** [comment] 2021-08-15 20:13
V should definitely give an error for this.

The problem is in the `println(n)` statement in your `fn main()`.  You told it `new_point()` returns a reference to a `Quad`, but then tried to print it as if it _was_ a `Quad` (that's what the error message means.

Your code is easily fixed by changing
```v
        println(n)
```
to
```v
        println(*n)
```
V will take a little longer.  :-)

**Closed** 2022-07-11 17:04 UTC
Labels: Bug, Status: Confirmed
