### ISSUE TITLE
I might have found a bug.

### ISSUE THREAD

**Issue by xywf221** [vlang/v#122] opened 2019-04-18 01:45 UTC
I am run the example code for the fib, web tips me `You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`

**Comment by arhen** [comment] 2019-04-18 07:11
put your code here. how can we evaluate your code?

**Comment by xywf221** [comment] 2019-04-18 09:14
> put your code here. how can we evaluate your code?

hi example code that here
```
const (
        MAX = 15 
)

struct Fib {
        nums []int
}

fn (fib mut Fib) calc(n int) int {
        if n <= 1 {
                return n
        }
        if fib.nums[n] != 0 {
                return fib.nums[n]
        }
        fib.nums[n] = fib.calc(n - 1) + fib.calc(n - 2)
        return fib.nums[n]
}

fn main() {
        mut fib := Fib {
                nums: [0; MAX]
        }
        for i := 0; i < MAX; i++ {
                println(fib.calc(i))
        }
}
```

**Comment by medvednikov** [comment] 2019-04-18 09:58
Duplicate of

https://github.com/vlang/v/issues/114

Will fix today.

**Closed by medvednikov** 2019-04-18 09:58 UTC

**Comment by medvednikov** [comment] 2019-04-18 10:11
Fixed.

**Comment by xywf221** [comment] 2019-04-18 10:15
This is going to look great.
