### ISSUE TITLE
panic compiling ui demo

### ISSUE THREAD

**Issue by Chronophylos** [vlang/v#14917] opened 2022-07-02 00:16 UTC
**V doctor:**
```
OS: linux, "Arch Linux"
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
CC version: cc (GCC) 12.1.0

getwd: /home/chrono/Repos/roller
vmodules: /home/chrono/.vmodules
vroot: /home/chrono/Repos/v
vexe: /home/chrono/Repos/v/v
vexe mtime: 2022-07-02 00:15:19
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 1b46383.5b97ad1

Git version: git version 2.37.0
Git vroot status: 0.3-14-g5b97ad15
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 827f7452

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg main.v`
```v
import ui

fn main() {
	ui.window(
    width: 600
    height: 400
    title: 'V UI Demo'
    children: [
		ui.row(
			margin: ui.Margin{10, 10, 10, 10}
			children: [
				ui.column(
					width: 200
					spacing: 13
					children: [
						ui.textbox(
							max_len: 20
							width: 200
							placeholder: 'First name'
							text: &app.first_name
						),
						ui.textbox(
							max_len: 50
							width: 200
							placeholder: 'Last name'
							text: &app.last_name
						)
					]
				)
			]
		)
	]
)
}
```

**What did you expect to see?**

not a panic

**What did you see instead?**
```
================ V panic ================
   module: v.ast
 function: default_table_panic_handler()
  message: sym: invalid type (typ=ast.Type(0x0 = 0) idx=0). Compiler bug. This should never happen. Please report the bug using `v bug file.v`.

     file: /home/chrono/Repos/v/vlib/v/ast/table.v:82
   v hash: 5b97ad1
=========================================
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/builtin/builtin.c.v:53: at panic_debug: Backtrace
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/ast/table.v:82: by v__ast__default_table_panic_handler
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/ast/table.v:88: by v__ast__Table_panic
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/ast/table.v:722: by v__ast__Table_sym
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/checker.v:3226: by v__checker__Checker_prefix_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/checker.v:2219: by v__checker__Checker_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/struct.v:379: by v__checker__Checker_struct_init
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/checker.v:2279: by v__checker__Checker_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/fn.v:832: by v__checker__Checker_fn_call
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/fn.v:394: by v__checker__Checker_call_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/checker.v:2095: by v__checker__Checker_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/containers.v:113: by v__checker__Checker_array_init
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/checker.v:2056: by v__checker__Checker_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/struct.v:379: by v__checker__Checker_struct_init
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/checker.v:2279: by v__checker__Checker_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/fn.v:832: by v__checker__Checker_fn_call
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/fn.v:394: by v__checker__Checker_call_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/checker.v:2095: by v__checker__Checker_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/containers.v:113: by v__checker__Checker_array_init
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/checker.v:2056: by v__checker__Checker_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/struct.v:379: by v__checker__Checker_struct_init
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/checker.v:2279: by v__checker__Checker_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/fn.v:832: by v__checker__Checker_fn_call
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/fn.v:394: by v__checker__Checker_call_expr
/tmp/v_1000/../../../../../../home/chrono/Repos/v/vlib/v/checker/checker.v:2095: by v__checker__Checker_expr
```

**Comment by tobealive** [comment] 2023-07-01 02:34
Closing this as the issue is not reproducible with the current version of V.

Feel free to reach out if you experience further issues @Chronophylos.

**Closed by tobealive** 2023-07-01 02:34 UTC
Labels: Bug
