### ISSUE TITLE
vfmt: replaces @VEXE with the path

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#5341] opened 2020-06-10 22:00 UTC
**V version:** latest
**OS:** Ubuntu 20.04

**What did you do?**
`v fmt -w cmd/tools/vdoc.v`

**What did you expect to see?**
`@VEXE`
 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/30751516/84323124-82f7f400-ab76-11ea-86a3-563a8d0696ef.png)

**Comment by nedpals** [comment] 2020-06-10 23:09
Closed. Duplicate of #5308

**Closed** 2020-06-10 23:09 UTC
Labels: Bug
