### ISSUE TITLE
HTML parser broken on some cases

### ISSUE THREAD

**Issue by Hunam6** [vlang/v#10576] opened 2021-06-26 01:25 UTC
**V version:** V 0.2.2 6890756
**OS:** Windows 10 64-bit

**Summary**
The HTML parser bug with an HTML string containing a script tag with `"''"` inside, I'm pretty sure the problem comes from [this function](https://github.com/vlang/v/blob/02f4f635cff081de8539fb9542515650ad97f80a/vlib/net/html/parser.v#L110) (if that can save some time).

**What did you do?**
`file.v`
```v
import net.html
println(html.parse_file('file.html'))
```
`file.html`
```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>minecraft</title>
	<script>
		console.log("''")
	</script>
</head>
<body>
	<h1>hey</h1>
</body>
</html>
```

**What did you expect to see?**
```
net.html.DocumentObjectModel{
    root: &<!doctype html><html lang="en" ><head>       <meta charset="UTF-8" > </meta><title>minecraft</title><script>              console.log("''") </script></head><body>  <h1>hey</h1></body></html></!doctype>
    constructed: true
    btree: net.html.BTree{
        all_tags: [<!doctype html></!doctype>, <html lang="en" ></html>, <head> </head>, <meta charset="UTF-8" >        </meta>, <title>minecraft</title>, <script>          console.log("''") </script>, <body>        </body>, <h1>hey</h1>]
        node_pointer: 6
        childrens: [[1], [2, 6], [3, 4, 5], [], [], [], [7]]
        parents: [0, 0, 1, 2, 2, 2, 1, 6]
    }
    all_tags: [<!doctype html><html lang="en" ><head>   <meta charset="UTF-8" > </meta><title>minecraft</title><script>              console.log("''") </script></head><body>  <h1>hey</h1></body></html></!doctype>, <html lang="en" ><head>   <meta charset="UTF-8" > </meta><title>minecraft</title><script>              console.log("''") </script></head><body>  <h1>hey</h1></body></html>, <head>       <meta charset="UTF-8" > </meta><title>minecraft</title><script>              console.log("''") </script></head>, <meta charset="UTF-8" >       </meta>, <title>minecraft</title>, <script>           console.log("''") </script>, <body>       <h1>hey</h1></body>, <h1>hey</h1>]
    all_attributes: {'lang': [<html lang="en" ><head>   <meta charset="UTF-8" > </meta><title>minecraft</title><script>              console.log("''") </script></head><body>  <h1>hey</h1></body></html>], '': [<html lang="en" ><head>        <meta charset="UTF-8" > </meta><title>minecraft</title><script>              console.log("''") </script></head><body>  <h1>hey</h1></body></html>, <meta charset="UTF-8" >      </meta>], 'charset': [<meta charset="UTF-8" >   </meta>]}
    close_tags: {'/!document': true, '/title': true, '/head': true, '/h1': true, '/body': true, '/html': true}
    attributes: {'lang': ['en'], '': [''], 'charset': ['UTF-8']}
    tag_attributes: {'lang': [[<html lang="en" ><head>  <meta charset="UTF-8" > </meta><title>minecraft</title><script>              console.log("''") </script></head><body>  <h1>hey</h1></body></html>]], '': [[<html lang="en" ><head>      <meta charset="UTF-8" > </meta><title>minecraft</title><script>              console.log("''") </script></head><body>  <h1>hey</h1></body></html>, <meta charset="UTF-8" >      </meta>], []], 'charset': [[<meta charset="UTF-8" >     </meta>]]}
    tag_type: {'html': [<html lang="en" ><head> <meta charset="UTF-8" > </meta><title>minecraft</title><script>              console.log("''") </script></head><body>  <h1>hey</h1></body></html>], 'head': [<head>     <meta charset="UTF-8" > </meta><title>minecraft</title><script>              console.log("''") </script></head>], 'meta': [<meta charset="UTF-8" >     </meta>], 'title': [<title>minecraft</title>], 'script': [<script>            console.log("''") </script>], 'body': [<body>     <h1>hey</h1></body>], 'h1': [<h1>hey</h1>]}
    debug_file: os.File{
        cfile: 0
        fd: 0
        is_opened: false
    }
}
```
 
**What did you see instead?**
```
net.html.DocumentObjectModel{
    root: &<!doctype html><html lang="en" ></html><head>        </head><meta charset="UTF-8" >  </meta><title>minecraft</title><script></script></!doctype>
    constructed: true
    btree: net.html.BTree{
        all_tags: [<!doctype html></!doctype>, <html lang="en" ></html>, <head> </head>, <meta charset="UTF-8" >        </meta>, <title>minecraft</title>, <script></script>]
        node_pointer: 0
        childrens: [[1, 2, 3, 4, 5]]
        parents: [0, 0, 0, 0, 0, 0]
    }
    all_tags: [<!doctype html><html lang="en" ></html><head>    </head><meta charset="UTF-8" >  </meta><title>minecraft</title><script></script></!doctype>, <html lang="en" ></html>, <head></head>, <meta charset="UTF-8" > </meta>, <title>minecraft</title>, <script></script>]
    all_attributes: {'lang': [<html lang="en" ></html>], '': [<html lang="en" ></html>, <meta charset="UTF-8" > </meta>], 'charset': [<meta charset="UTF-8" >   </meta>]}
    close_tags: {'/!document': true, '/title': true}
    attributes: {'lang': ['en'], '': [''], 'charset': ['UTF-8']}
    tag_attributes: {'lang': [[<html lang="en" ></html>]], '': [[<html lang="en" ></html>, <meta charset="UTF-8" >      </meta>], []], 'charset': [[<meta charset="UTF-8" >     </meta>]]}
    tag_type: {'html': [<html lang="en" ></html>], 'head': [<head>      </head>], 'meta': [<meta charset="UTF-8" >      </meta>], 'title': [<title>minecraft</title>], 'script': [<script></script>]}
    debug_file: os.File{
        cfile: 0
        fd: 0
        is_opened: false
    }
}
```

**Comment by Jictyvoo** [comment] 2021-12-02 04:47
As you say, the problem is basically when the parser identifies that the tag is a "code" tag and it's elements should not be parsed.

To help further, the verification if the tag is a "code tag" is in this line:
https://github.com/vlang/v/blob/02f4f635cff081de8539fb9542515650ad97f80a/vlib/net/html/parser.v#L187

Which enter in the state checked in this line
https://github.com/vlang/v/blob/02f4f635cff081de8539fb9542515650ad97f80a/vlib/net/html/parser.v#L120

I gonna make a PR next days to fix this and other problems with the parser. Sorry for the delay

**Closed** 2023-05-07 00:55 UTC
Labels: Bug
