### ISSUE TITLE
fmt return error(edit: and is unhelpfull)

### ISSUE THREAD

**Issue by MatejMagat305** [vlang/v#17145] opened 2023-01-28 16:31 UTC
### Describe the bug

I'm working on vcl some add, and I get error which I do not understand why it is here

### Expected Behavior

v fmt . -w 
done (edit: more suitable error)

### Current Behavior

image.c.v:113:3: error: invalid expression: unexpected keyword `return`
  111 |         unsafe { &region[0] }, 0, 0, unsafe { &data[0] }, 0, unsafe { nil }, unsafe { nil })
  112 |     if ret != CL_SUCCESS { // (edit: this is error it is without C.
  113 |         return vclError(ret)
      |         ~~~~~~
  114 |     }
  115 |     return data

### Additional Information/Context

I will no update this branch ...

### V version

V 0.3.2 d3e4058

### Environment details (OS name and version, etc.)

OS: linux, Kali GNU/Linux Rolling
Processor: 32 cpus, 64bit, little endian, AMD Ryzen 9 5950X 16-Core Processor
CC version: cc (Debian 12.2.0-13) 12.2.0

getwd: /home/matejmag/.vmodules/vsl/vcl
vmodules: /home/matejmag/.vmodules
vroot: /home/matejmag/Documents/v
vexe: /home/matejmag/Documents/v/v
vexe mtime: 2023-01-28 16:17:14
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 1d4fd53.d3e4058

Git version: git version 2.39.0
Git vroot status: weekly.2023.04-18-gd3e4058a
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by ttytm** [comment] 2024-03-21 07:24
Unfortunately, cannot look into issues due to missing reproduction steps. The experienced problem might be fixed with latest V already. Please leave a note if you experience further issues.

**Closed by ttytm** 2024-03-21 07:24 UTC
Labels: Bug
