### ISSUE TITLE
JSON decoding/encoding from https://vlang.io/play

### ISSUE THREAD

**Issue by Bablzz** [vlang/v#3849] opened 2020-02-26 08:15 UTC
**V version:** 
From https://vlang.io/play

**OS:** 
https://vlang.io/play

**What did you do?**
Run example "JSON decoding/encoding" 

**What did you expect to see?**
Something interesting
 
**What did you see instead?**
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by alexesprit** [comment] 2020-02-26 10:00
Closed as a duplicate of #3327.

**Closed by alexesprit** 2020-02-26 10:00 UTC
Labels: Status: Duplicate, Type: Bug
