### ISSUE TITLE
The Problem with file extensions

### ISSUE THREAD

**Issue by pranavbaburaj** [vlang/v#8878] opened 2021-02-21 11:56 UTC
![Verilog](https://raw.githubusercontent.com/pranavbaburaj/pranavbaburaj/main/v.png)
As you can see in the below picture, the file extension of vlang files clashes with the Verilog files.

Hope this will be fixed

**Comment by alic110** [comment] 2021-02-21 12:45
this is not a bug and it is a personal problem.

**Comment by nsauzede** [comment] 2021-02-21 13:04
I confirm, V lang will not change its extension :-)
closing as invalid/wontfix

**Closed by nsauzede** 2021-02-21 13:04 UTC
Labels: Bug
