### ISSUE TITLE
V is unable to differentiate a function call from a variable even if it has parentheses

### ISSUE THREAD

**Issue by Hunam6** [vlang/v#14055] opened 2022-04-16 22:12 UTC
```
OS: macos, macOS, 12.3.1, 21E258
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 13.1.6 (clang-1316.0.21.2)

getwd: /Users/hunam/Documents/dev/go2v
vmodules: /Users/hunam/.vmodules
vroot: /Applications/v
vexe: /Applications/v/v
vexe mtime: 2022-04-16 22:06:24
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 1fc54a1.4f14f77

Git version: git version 2.32.0 (Apple Git-132)
Git vroot status: weekly.2022.15-65-g4f14f771
.git/config present: true
thirdparty/tcc status: thirdparty-unknown-unknown de82a130
```

**What did you do?**
```v
fn main() {
	aaa := 'fds'
	println(aaa) // works
	println(aaa()) // should work too
}

fn aaa() string {
	return 'aaa'
}
```

**What did you expect to see?**
From a user point of view, on line 4, it's easy to tell that I'm calling the function, thanks to the parentheses. The compiler should be able to detect those parentheses too.
 
**What did you see instead?**
```v
v.v:4:10: error: ambiguous call to: `aaa`, may refer to fn `aaa` or variable `aaa`
    2 |     aaa := 'fds'
    3 |     println(aaa)
    4 |     println(aaa())
      |             ~~~~~
    5 | }
    6 |
```

**Comment by Thor-x86** [comment] 2022-04-17 00:48
I don't think it's a bug, since other programming language will throw an error too like `TypeError: "aaa" is not a function` on JavaScript

**Comment by Wajinn** [comment] 2022-04-17 01:17
> I don't think it's a bug, since other programming language will throw an error too like `TypeError: "aaa" is not a function` on JavaScript

I agree.  Think it's good that you get an error.  That's because you could assign a function to the variable, within a function (nested function).  Since V doesn't provide closures on all supported OSes, this is arguably the next best thing.  If they did, what Hunam6 is calling a bug, then I don't see how nested functions would be possible.

```
fn main() {
	mut aaa := fn() string {
	return 'aaa'
	}
	bbb := 'stuff'

	println(aaa()) 
	println(bbb)
}
```

**Comment by vincenzopalazzo** [comment] 2022-04-17 07:41
I don't think also that this is bug, the error is clear here `error: ambiguous call to: `aaa`, may refer to fn `aaa` or variable `aaa`` and I would like to stay with this code.

Messy code is buggy code!

**Comment by JalonSolov** [comment] 2022-04-17 13:24
That's actually untrue.  It's not ambiguous because the variable is referred to as `aaa`, while the function is `aaa()`.  The parentheses let's you tell them apart.

**Comment by JalonSolov** [comment] 2022-04-17 13:27
> > I don't think it's a bug, since other programming language will throw an error too like `TypeError: "aaa" is not a function` on JavaScript
> 
> I agree. Think it's good that you get an error. That's because you could assign a function to the variable, within a function (nested function). Since V doesn't provide closures on all supported OSes, this is arguably the next best thing. If they did, what Hunam6 is calling a bug, then I don't see how nested functions would be possible or at least it would be harder to implement.
> 
> ```
> fn main() {
> 	mut aaa := fn() string {
> 	return 'aaa'
> 	}
> 	bbb := 'stuff'
> 
> 	println(aaa()) 
> 	println(bbb)
> }
> ```

Now add
```v
fn aaa() {
        return 'aaa'
}
```
to your example.  That should still be something the compiler can figure out, due to scope.

**Comment by Wajinn** [comment] 2022-04-17 15:17
>...the error is clear here `error: ambiguous call to: `aaa`, may refer to fn `aaa`or variable`aaa`` ...
> Messy code is buggy code!

Agree.  No function was assigned to the variable.  There is no reason for aaa to be aaa().  I would think the intention is for the user to actually assign a function to the variable, thus aaa() would be valid.

For aaa() to be valid, think we should actually do- 
``
	mut aaa := fn() string {
	return 'aaa'
	}
```
If we can just arbitrarily make variables into functions without actually assigning functions to the variable, we are creating ambiguous situations.  I think the compiler should complain when we are ambiguous.

**Comment by medvednikov** [comment] 2022-04-17 15:32
It's by design.

Makes code more readable and easier to understand.

Also yes, what happens if the local var is a function pointer.

**Comment by medvednikov** [comment] 2022-04-17 15:33
We don't allow variable shadowing for the same reason.

**Comment by JalonSolov** [comment] 2022-04-17 15:41
So to state it explicitly - In V, you cannot have a variable with the same name as a function in the same scope.  Correct?

**Comment by medvednikov** [comment] 2022-04-17 16:05
Yes, that would be better.

**Comment by JalonSolov** [comment] 2022-04-17 16:07
Well... namespace or module probably better than scope, but ok then.

**Closed** 2022-08-17 08:18 UTC
Labels: Bug
