### ISSUE TITLE
Compiler Error When Returning Multiple Values Inlcuding Sum Type

### ISSUE THREAD

**Issue by rymaju** [vlang/v#10003] opened 2021-05-04 18:23 UTC
**V version: V 0.2.2 818983d** 
**OS: Ubuntu 20.04.1 LTS** 

**What did you do?**
Attempted to write a function that returned sum type and another type as multiple return values from a function.

**What did you expect to see?**
Expected to get the intended behavior for returning multiple values.
 
**What did you see instead?**
Instead, got compiler error:
```
/tmp/v/../../../../../../home/rymaju/v-lisp/minimal.v:13: error: cannot convert 'struct array' to 'int *'
builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.
```

Here is a minimal example of the error for reproducibility:
```v

// Represents an N-ary tree
type N_Tree = int | []N_Tree

struct Result {
	tree N_Tree
	number int
}

fn create_tree() (N_Tree, int) {
	mut tree := []N_Tree{}
	tree << 1
	return tree, 1 //this is where the error is reported
}

create_tree()
```

It seems that the bug only occurs when returning multiple values, when changing the return type to simply return an `N_Tree` and only returning `tree`, the program compiles and runs successfully.

**Comment by Dialga** [comment] 2022-05-21 18:41
Duplicate of #12927, fixed by #12930 [6eb44f4](https://github.com/vlang/v/commit/6eb44f472aaf7a9966c8b8297c2d5d62946e7a52) on 22nd December 2021.

**Closed by Dialga** 2022-05-21 18:41 UTC
Labels: Bug
