### ISSUE TITLE
Runtime error when pushed in array some structure fileds, error clone() not displayed

### ISSUE THREAD

**Issue by Lathanao** [vlang/v#9374] opened 2021-03-19 10:10 UTC
V full version: V 0.2.2 2e84773
OS: linux, "Manjaro Linux"

**What did you do?**
```v
module main

struct Product {
mut:
	schema1 []string = ['id']
	schema2 []string = ['sku']
}

pub fn (p Product) do_somthing() Product {
	mut schema := p.schema1
	schema << p.schema2
	return p
}

fn  main() {
	mut p := Product{}
	println(p.do_somthing())
}
```

**What did you expect to see?**
The Product structure
 
**What did you see instead?**
```
7ffff7de2ad3 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v/struct_generic_iterator_without_generic_bug_array.13372961394880386484.tmp.c:1694: by strings__Builder_write_string
/tmp/v/struct_generic_iterator_without_generic_bug_array.13372961394880386484.tmp.c:4927: by Array_string_str
/tmp/v/struct_generic_iterator_without_generic_bug_array.13372961394880386484.tmp.c:1526: by indent_main__Product_str
/tmp/v/struct_generic_iterator_without_generic_bug_array.13372961394880386484.tmp.c:1517: by main__Product_str
/tmp/v/struct_generic_iterator_without_generic_bug_array.13372961394880386484.tmp.c:8736: by main__main
/tmp/v/struct_generic_iterator_without_generic_bug_array.13372961394880386484.tmp.c:8821: by main
```

**Addendum**
With:
```v
mut schema := p.schema1.clone()
```
The code works well.

The clone() is missing, and the error should be the same than:
```v
module main

fn  main() {

	schema1 := ['id']
	schema2 := ['sku']

	mut schema := schema1
	schema << schema2
}
```
get error like:
```
test/bug.v:8:13: error: use `array2 := array1.clone()` instead of `array2 := array1` (or use `unsafe`)
    6 |     schema2 := ['sku']
    7 | 
    8 |     mut schema := schema1
      |                ~~
    9 |     schema << schema2
   10 | }
````

**Comment by crthpl** [comment] 2021-05-16 23:11
Closing as duplicate of #10011, since it has more discussion.

**Closed by crthpl** 2021-05-16 23:11 UTC
Labels: Bug
