### ISSUE TITLE
Crash when call deep (nested) generic function

### ISSUE THREAD

**Issue by ken0x0a** [vlang/v#9148] opened 2021-03-06 04:32 UTC
**V version:** 
V full version: V 0.2.2 db9b523.204f57d
**OS:** 

**What did you do?**

```vlang
module main

struct MyStruct {}

struct MyStruct2 {}

fn main() {
	m1 := MyStruct{}
	m2 := MyStruct2{}
	generic(m1)
	generic(m2) // comment out this line to avoid crash
}

fn generic<T>(t T) {
	generic2<T>(t)
}

fn generic2<T>(t T) {
}
```

**What did you expect to see?**

finish without any errors.
 
**What did you see instead?**

Output with `v run generic_build_crash.v
```
==================
                                               ^
/var/folders/g7/dmx2lf49447f1yqr7d96n4000000gp/T/v/generic_build_crash.5253629881079391606.tmp.c:8667:2: error: implicit declaration of function 'main__generic2_T_main__MyStruct2' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        main__generic2_T_main__MyStruct2(t);
        ^
2 warnings and 1 error generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

Output with `v -v run generic_build_crash.v

```
builder.compile() pref:
all .v files before:
v.pref.lookup_path: ['/Users/username/src/v/vlib', '/Users/username/.vmodules']
v_files_from_dir ("/Users/username/src/v/vlib/builtin")
>>> should_compile_filtered_files: res: ['/Users/username/src/v/vlib/builtin/array.v', '/Users/username/src/v/vlib/builtin/builtin.c.v', '/Users/username/src/v/vlib/builtin/builtin.v', '/Users/username/src/v/vlib/builtin/builtin_nix.c.v', '/Users/username/src/v/vlib/builtin/cfns.c.v', '/Users/username/src/v/vlib/builtin/chan.v', '/Users/username/src/v/vlib/builtin/float.v', '/Users/username/src/v/vlib/builtin/int.v', '/Users/username/src/v/vlib/builtin/map.v', '/Users/username/src/v/vlib/builtin/option.v', '/Users/username/src/v/vlib/builtin/rune.v', '/Users/username/src/v/vlib/builtin/sorted_map.v', '/Users/username/src/v/vlib/builtin/string.v', '/Users/username/src/v/vlib/builtin/utf8.c.v', '/Users/username/src/v/vlib/builtin/utf8.v']
get_v_files(study/issue/generic_build_crash.v)
> just compile one file: "study/issue/generic_build_crash.v"
user_files: ['study/issue/generic_build_crash.v']
x: "/Users/username/code/lang/v/study/issue/modules"
v.module_search_paths:
['/Users/username/code/lang/v/study/issue', '/Users/username/code/lang/v/study/issue/modules', '/Users/username/src/v/vlib', '/Users/username/.vmodules']
all .v files:
['/Users/username/src/v/vlib/builtin/array.v', '/Users/username/src/v/vlib/builtin/builtin.c.v', '/Users/username/src/v/vlib/builtin/builtin.v', '/Users/username/src/v/vlib/builtin/builtin_nix.c.v', '/Users/username/src/v/vlib/builtin/cfns.c.v', '/Users/username/src/v/vlib/builtin/chan.v', '/Users/username/src/v/vlib/builtin/float.v', '/Users/username/src/v/vlib/builtin/int.v', '/Users/username/src/v/vlib/builtin/map.v', '/Users/username/src/v/vlib/builtin/option.v', '/Users/username/src/v/vlib/builtin/rune.v', '/Users/username/src/v/vlib/builtin/sorted_map.v', '/Users/username/src/v/vlib/builtin/string.v', '/Users/username/src/v/vlib/builtin/utf8.c.v', '/Users/username/src/v/vlib/builtin/utf8.v', 'study/issue/generic_build_crash.v']
build_c(/var/folders/g7/dmx2lf49447f1yqr7d96n4000000gp/T/v/generic_build_crash.4671738952717760644.tmp.c)
  >> trying to find strings in /Users/username/src/v/strings ..
  >> trying to find strings in /Users/username/code/lang/v/study/issue/strings ..
  >> trying to find strings in /Users/username/code/lang/v/study/issue/modules/strings ..
  >> trying to find strings in /Users/username/src/v/vlib/strings ..
  << found /Users/username/src/v/vlib/strings .
v_files_from_dir ("/Users/username/src/v/vlib/strings")
>>> should_compile_filtered_files: res: ['/Users/username/src/v/vlib/strings/builder.v', '/Users/username/src/v/vlib/strings/similarity.v', '/Users/username/src/v/vlib/strings/strings.c.v', '/Users/username/src/v/vlib/strings/strings.v']
  >> trying to find strconv in /Users/username/src/v/strconv ..
  >> trying to find strconv in /Users/username/code/lang/v/study/issue/strconv ..
  >> trying to find strconv in /Users/username/code/lang/v/study/issue/modules/strconv ..
  >> trying to find strconv in /Users/username/src/v/vlib/strconv ..
  << found /Users/username/src/v/vlib/strconv .
v_files_from_dir ("/Users/username/src/v/vlib/strconv")
>>> should_compile_filtered_files: res: ['/Users/username/src/v/vlib/strconv/atof.v', '/Users/username/src/v/vlib/strconv/atofq.v', '/Users/username/src/v/vlib/strconv/atoi.v', '/Users/username/src/v/vlib/strconv/f32_str.v', '/Users/username/src/v/vlib/strconv/f64_str.v', '/Users/username/src/v/vlib/strconv/format.v', '/Users/username/src/v/vlib/strconv/ftoa.v', '/Users/username/src/v/vlib/strconv/number_to_base.v', '/Users/username/src/v/vlib/strconv/structs.v', '/Users/username/src/v/vlib/strconv/tables.v', '/Users/username/src/v/vlib/strconv/utilities.v']
  >> trying to find hash in /Users/username/src/v/hash ..
  >> trying to find hash in /Users/username/code/lang/v/study/issue/hash ..
  >> trying to find hash in /Users/username/code/lang/v/study/issue/modules/hash ..
  >> trying to find hash in /Users/username/src/v/vlib/hash ..
  << found /Users/username/src/v/vlib/hash .
v_files_from_dir ("/Users/username/src/v/vlib/hash")
>>> should_compile_filtered_files: res: ['/Users/username/src/v/vlib/hash/hash.v', '/Users/username/src/v/vlib/hash/wyhash.c.v', '/Users/username/src/v/vlib/hash/wyhash.v']
  >> trying to find math.bits in /Users/username/src/v/math/bits ..
  >> trying to find math.bits in /Users/username/code/lang/v/study/issue/math/bits ..
  >> trying to find math.bits in /Users/username/code/lang/v/study/issue/modules/math/bits ..
  >> trying to find math.bits in /Users/username/src/v/vlib/math/bits ..
  << found /Users/username/src/v/vlib/math/bits .
v_files_from_dir ("/Users/username/src/v/vlib/math/bits")
>>> should_compile_filtered_files: res: ['/Users/username/src/v/vlib/math/bits/bits.v', '/Users/username/src/v/vlib/math/bits/bits_tables.v']
------ resolved dependencies graph: ------

 * strconv -> strings
 * strconv -> math.bits
 * builtin -> strings
 * builtin -> strconv
 * builtin -> hash
 * main -> builtin

------------------------------------------
------ imported modules: ------
['strings', 'hash', 'math.bits', 'strconv', 'builtin', 'main']
-------------------------------
10.015   ms SCAN
21.534   ms PARSE
inferred `main.generic<main.MyStruct>`
inferred `main.generic<main.MyStruct2>`
10.138   ms CHECK
gen fn `main.generic` for type `main.generic`
gen fn `main.generic` for type `main.generic`
gen fn `main.generic2` for type `main.generic2`
26.967   ms C GEN
builder.cc() pref.out_name="/Users/username/code/lang/v/study/issue/generic_build_crash"
build_thirdparty_obj_files: v.table.cflags: []
cc() isprod=false outname=/Users/username/code/lang/v/study/issue/generic_build_crash

=====================
> C compiler cmd: cc "@/var/folders/g7/dmx2lf49447f1yqr7d96n4000000gp/T/v/generic_build_crash.4671738952717760644.tmp.c.rsp"
=====================
162.681  ms C  cc
==================
                                               ^
/var/folders/g7/dmx2lf49447f1yqr7d96n4000000gp/T/v/generic_build_crash.4671738952717760644.tmp.c:8667:2: error: implicit declaration of function 'main__generic2_T_main__MyStruct2' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        main__generic2_T_main__MyStruct2(t);
        ^
2 warnings and 1 error generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by Gladear** [comment] 2021-03-07 21:18
Duplicate of https://github.com/vlang/v/issues/8424

**Closed by Gladear** 2021-03-07 21:18 UTC
Labels: Bug
