### ISSUE TITLE
List filter issue

### ISSUE THREAD

**Issue by anwarsky** [vlang/v#3331] opened 2020-01-05 05:29 UTC
**V version:** 0.1.24
**OS:** Ubuntu 19.09
**What did you do?**
```v
println([1, -1, 2, 3, 4, 5].filter(it % 2 == 0))
```
**What did you expect to see?**
```
[2, 4]
```
**What did you see instead?**
```
V panic: substr(0, 10) out of bounds (len=0)
```

**Comment by dhonx** [comment] 2020-01-05 10:30
https://devbits.app/play/IlszP60JnI7j
```v
a := [1, -1, 2, 3, 4, 5]
b := a.filter(it % 2 == 0)
println(b)
```
```
[2, 4]
```

**Comment by Contextualist** [comment] 2020-01-07 04:44
Duplicate of #2621

**Comment by alexesprit** [comment] 2020-02-08 05:22
Closed as a duplicate.

**Closed by alexesprit** 2020-02-08 05:22 UTC
Labels: Type: Bug
