### ISSUE TITLE
json problem of encode and decode

### ISSUE THREAD

**Issue by zhou26192619** [vlang/v#3838] opened 2020-02-25 13:23 UTC
**V version:** 
V 0.1.25 f6c2b3a
**OS:** 
manjaro
**What did you do?**

         mut uu:=map[string]string
	uu['name']='dddd'
	data := json.encode(uu)
	println(data) //the result is {}

	str:='{"name":"lily"}'
	user := json.decode(map[string]string, str) or {
		panic(err)
	}
	println(user)  //the result is {}

**What did you expect to see?**
the right object
 
**What did you see instead?**
{}
{}

**Comment by nedpals** [comment] 2020-02-29 02:45
Decoding json with map strings aren't possible yet in V for now.

**Comment by alexesprit** [comment] 2020-02-29 12:52
Closed as a duplicate of #3367.

**Closed by alexesprit** 2020-02-29 12:52 UTC
Labels: Type: Bug
