### ISSUE TITLE
Syntax check omission in vstring to &char()

### ISSUE THREAD

**Issue by shove70** [vlang/v#14921] opened 2022-07-02 11:54 UTC
**V version:** 0.3.0 ec75860
**OS:** MacOS 12.4

```
ptr := &char('') // => C error. This is a compiler bug
// ptr := &char(''.str) // => OK.
```

```
==================
   ^~~~~~~~~~~~~~~
/tmp/v_501/app.13678786744596750034.tmp.c:12009:22: error: operand of type 'string' (aka 'struct string') where arithmetic or pointer type is required
        char* ptr = ((char*)(_SLIT("")));
                            ^~~~~~~~~~~
1 warning and 1 error generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by JalonSolov** [comment] 2022-07-02 12:19
Th error is correct, though V should catch it and give a better message.

A string in V is a struct, so you cannot cast it to a simple character pointer.

The `.str` field in the struct is a NUL-terminated character array (just like a C string), which is why the commented line works.

**Comment by shove70** [comment] 2022-07-04 00:10
> Th error is correct, though V should catch it and give a better message.
> 
> A string in V is a struct, so you cannot cast it to a simple character pointer.
> 
> The `.str` field in the struct is a NUL-terminated character array (just like a C string), which is why the commented line works.

Of course, but the V compiler should catch and terminate the compilation process.

**Comment by JalonSolov** [comment] 2022-07-12 12:51
Let's leave it open until the problem is fixed in V.

**Closed** 2022-09-11 10:54 UTC
Labels: Bug, Status: Confirmed
