### ISSUE TITLE
vfmt shouldn't do a new line on structs etc if they're empty

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7454] opened 2020-12-21 20:36 UTC
**What did you do?**
`v fmt`
```v
enum Color {}

struct Tmp {}

fn main() {
}
```

**What did you expect to see?**
```v
enum Color {}

struct Tmp {}

fn main() {
}
```
 
**What did you see instead?**
```v
enum Color {
}

struct Tmp {
}

fn main() {
}
```

**Comment by serkonda7** [comment] 2020-12-21 20:46
Duplicate of #7117

**Closed by serkonda7** 2020-12-21 20:46 UTC
Labels: Bug

**Comment by danieldaeschle** [comment] 2020-12-21 21:28
thanks
