### ISSUE TITLE
using int as variable names crashes compiler

### ISSUE THREAD

**Issue by BlackEspresso** [vlang/v#155] opened 2019-04-21 07:46 UTC
using a variable called 'int' leads to an compile error. other basic types like i8,string, ... can be used as variable names. 
```
fn main() {
	int := 9
	println(int)
}
```

**Comment by medvednikov** [comment] 2019-04-21 07:55
Duplicate of https://github.com/vlang/v/issues/102

**Closed by medvednikov** 2019-04-21 07:55 UTC
