### ISSUE TITLE
Compile-time out-of-bounds panic

### ISSUE THREAD

**Issue by codingconcepts** [vlang/v#3239] opened 2019-12-27 19:41 UTC
**V version:** `0.1.23 6363118`
**OS:** macos High Sierra 10.13.6

**What did you do?**

Tried to build the following program:
```v
fn main() {
	mut a := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
	a = a.filter(it % 2 == 0)

	println(a)
}
```

The following program builds and executes as expected:
```v
fn main() {
	a := [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
	b := a.filter(it % 2 == 0)

	println(b)
}
```

**What did you expect to see?**
A successful compilation resulting in an executable.
 
**What did you see instead?**
```
================ V panic ================
   module: builtin
 function: substr()
     file: /Users/me/v/vlib/builtin/string.v
     line: 483
  message: substr(0, 6) out of bounds (len=0)
=========================================
0   v                                   0x000000010d1a4918 panic_debug + 312
1   v                                   0x000000010d1aa5ea string_substr + 250
2   v                                   0x000000010d1ac49c string_substr2 + 76
3   v                                   0x000000010d1c5c97 compiler__CGen_set_placeholder + 311
4   v                                   0x000000010d1cfbdf compiler__Parser_gen_array_filter + 767
5   v                                   0x000000010d1db9e2 compiler__Parser_dot + 610
6   v                                   0x000000010d21d6c4 compiler__Parser_var_expr + 1972
7   v                                   0x000000010d1db0d9 compiler__Parser_get_var_type + 505
8   v                                   0x000000010d1d73c4 compiler__Parser_name_expr + 3188
9   v                                   0x000000010d1e19cb compiler__Parser_factor + 2219
10  v                                   0x000000010d1e105f compiler__Parser_unary + 399
11  v                                   0x000000010d1e0679 compiler__Parser_term + 57
12  v                                   0x000000010d1dfe1b compiler__Parser_indot_expr + 43
13  v                                   0x000000010d1d53d9 compiler__Parser_expression + 57
14  v                                   0x000000010d1d424b compiler__Parser_bterm + 43
15  v                                   0x000000010d1c545f compiler__Parser_bool_expression + 79
16  v                                   0x000000010d21a984 compiler__Parser_assign_statement + 1668
17  v                                   0x000000010d21f608 compiler__Parser_index_expr + 5704
18  v                                   0x000000010d21d93f compiler__Parser_var_expr + 2607
19  v                                   0x000000010d1db0d9 compiler__Parser_get_var_type + 505
20  v                                   0x000000010d1d73c4 compiler__Parser_name_expr + 3188
21  v                                   0x000000010d1e19cb compiler__Parser_factor + 2219
22  v                                   0x000000010d1e105f compiler__Parser_unary + 399
23  v                                   0x000000010d1e0679 compiler__Parser_term + 57
24  v                                   0x000000010d1dfe1b compiler__Parser_indot_expr + 43
25  v                                   0x000000010d1d53d9 compiler__Parser_expression + 57
26  v                                   0x000000010d1d424b compiler__Parser_bterm + 43
27  v                                   0x000000010d1c545f compiler__Parser_bool_expression + 79
28  v                                   0x000000010d1f80b7 compiler__Parser_statement + 791
29  v                                   0x000000010d1cc726 compiler__Parser_statements_no_rcbr + 134
30  v                                   0x000000010d1ea0b9 compiler__Parser_fn_decl + 11353
31  v                                   0x000000010d201510 compiler__Parser_parse + 2128
32  v                                   0x000000010d1fff65 compiler__V_parse + 325
33  v                                   0x000000010d202b7f compiler__V_compile + 3311
34  v                                   0x000000010d22cc43 main__main + 1907
35  v                                   0x000000010d22f25e main + 78
36  v                                   0x000000010d1a42d4 start + 52
```

When running in the playground I get the following error:
```
Warning: 'v' is a directory
addr2line: Warning: 'v' is a directory
```

**Comment by alexesprit** [comment] 2020-04-11 21:04
The issue is fixed in a new backend.

**Closed by alexesprit** 2020-04-11 21:04 UTC
Labels: Bug
