### ISSUE TITLE
Can not make on macOS 10.11

### ISSUE THREAD

**Issue by guizhenwei** [vlang/v#7396] opened 2020-12-18 18:08 UTC
**V version:** 
**OS: macOS 10.11.6 (EI Captain)** 

**What did you do?**
git pull from master
cd v
make

**What did you expect to see?**
Install V on macOS 10.11.
 
**What did you see instead?**
```
$ make
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread 
./vc/v.c:17475:16: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        clock_gettime(CLOCK_MONOTONIC, &ts);
                      ^
./vc/v.c:17481:16: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &ts);
                      ^
./vc/v.c:17489:16: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &ts);
                      ^
./vc/v.c:17503:16: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &ts);
                      ^
4 errors generated.
make: *** [all] Error 1
```

**Comment by guizhenwei** [comment] 2021-01-27 16:41
And it should be the same reason for issue #6605

**Comment by crthpl** [comment] 2021-03-19 02:10
duplicate of #6605, should be closed

**Closed** 2021-03-19 02:29 UTC
Labels: Bug
